force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <description>Used to manage payment requests for approval, typically for promotional and/or exceptional payments.</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Amount_Dollars__c</fullName>
    <description>The dollar amount for the payment request.</description>
    <inlineHelpText>The dollar amount for the payment request.</inlineHelpText>
    <label>Amount (Dollars)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Points__c.field-meta.xml
<CustomField>
    <fullName>Amount_Points__c</fullName>
    <description>The point amount for the payment request.</description>
    <inlineHelpText>The point amount for the payment request.</inlineHelpText>
    <label>Amount (Points)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor to whom this request relates.</description>
    <inlineHelpText>The Donor to whom this request relates.</inlineHelpText>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Advances the state of the request, controlled by approval processes and automation.</description>
    <inlineHelpText>Advances the state of the request, controlled by approval processes and automation.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentRequestTriggerHandlerTest.cls
/**
 * Created by joshlequire1 on 7/5/23.
 */

@IsTest
public without sharing class PaymentRequestTriggerHandlerTest {

    @IsTest
    // There's not really a great way to test this, but it needs coverage. So, let's make sure we can create and update records.
    static void coverMarketingCloud() {
        Account donorAccount = TestUtil.createDonor('123');
        insert donorAccount;
        Id donorContactId = [SELECT PersonContactId FROM Account WHERE Id = :donorAccount.Id][0].PersonContactId;

        Payment_Request__c newPaymentRequest = new Payment_Request__c(
            Name = 'Test Payment Request',
            Status__c = 'New',
            Amount_Dollars__c = 100,
            Amount_Points__c = 50,
            Donor__c = donorContactId
        );

        insert newPaymentRequest;

        Assert.isNotNull(newPaymentRequest.Id);

        Payment_Request__c updatePaymentRequest = new Payment_Request__c(
            Id = newPaymentRequest.Id,
            Status__c = 'Approved'
        );

        update updatePaymentRequest;

        Assert.areEqual('Approved', updatePaymentRequest.Status__c);

    }

}