force-app/main/default/objects/Campaign/fields/Enable_Payment_Requests__c.field-meta.xml
<CustomField>
    <fullName>Enable_Payment_Requests__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Incentive Type Campaigns, indicates if Payment Requests should be created automatically when new Campaign Levels are achieved for Campaign Members.</description>
    <inlineHelpText>For Incentive Type Campaigns, indicates if Payment Requests should be created automatically when new Campaign Levels are achieved for Campaign Members.</inlineHelpText>
    <label>Enable Payment Requests</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Member_Incentive_Life_Days__c.field-meta.xml
<CustomField>
    <fullName>Member_Incentive_Life_Days__c</fullName>
    <description>Indicates the numbers of days since joining the Campaign that the member is eligible for the incentive.</description>
    <inlineHelpText>Indicates the numbers of days since joining the Campaign that the member is eligible for the incentive.</inlineHelpText>
    <label>Member Incentive Life (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/Campaign_Level__c.object-meta.xml
<CustomObject>
    <description>Indicates levels of achievement and payment for incentive type Campaigns.</description>
    <label>Campaign Level</label>
    <nameField>
        <label>Campaign Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Level__c/fields/Award_Dollar_Amount__c.field-meta.xml
<CustomField>
    <fullName>Award_Dollar_Amount__c</fullName>
    <description>Indicates the dollar amount award for the incentive level.</description>
    <inlineHelpText>Indicates the dollar amount award for the incentive level.</inlineHelpText>
    <label>Award (Dollar Amount)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Award_Point_Amount__c.field-meta.xml
<CustomField>
    <fullName>Award_Point_Amount__c</fullName>
    <description>Indicates the point amount award for the incentive level.</description>
    <inlineHelpText>Indicates the point amount award for the incentive level.</inlineHelpText>
    <label>Award (Point Amount)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Campaign to which this Level belongs. Campaign MUST be an `Incentive` Type to link correctly.</description>
    <inlineHelpText>The Campaign to which this Level belongs. Campaign MUST be an `Incentive` Type to link correctly.</inlineHelpText>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an Incentive Type Campaign to link this Level.</errorMessage>
        <filterItems>
            <field>Campaign.Type</field>
            <operation>equals</operation>
            <value>Incentive</value>
        </filterItems>
        <infoMessage>Please select an Incentive Type Campaign to link this Level.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Levels</relationshipLabel>
    <relationshipName>Campaign_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the incentive level is active or not. Allows for editing incentives, activating, and deactivating.</description>
    <inlineHelpText>Indicates if the incentive level is active or not. Allows for editing incentives, activating, and deactivating.</inlineHelpText>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Minimum_Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Donation_Amount__c</fullName>
    <description>Indicates the number of eligible donations for a member of the Campaign to reach to get this incentive.</description>
    <inlineHelpText>Indicates the number of eligible donations for a member of the Campaign to reach to get this incentive.</inlineHelpText>
    <label>Minimum Donation Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Next_Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Next_Campaign_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the next incentive level that follows this Campaign Level.</description>
    <inlineHelpText>Indicates the next incentive level that follows this Campaign Level.</inlineHelpText>
    <label>Next Campaign Level</label>
    <referenceTo>Campaign_Level__c</referenceTo>
    <relationshipLabel>Next Campaign Levels</relationshipLabel>
    <relationshipName>Campaign_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current Campaign Level for this Member, if applicable (for incentive Campaigns only).</description>
    <inlineHelpText>Current Campaign Level for this Member, if applicable (for incentive Campaigns only).</inlineHelpText>
    <label>Campaign Level</label>
    <referenceTo>Campaign_Level__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Eligible_Donation_Count__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Donation_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date. This is set automatically by code, based on Status = Complete and Outcome = Donation visits for the Campaign Member Contact.</description>
    <inlineHelpText>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date.</inlineHelpText>
    <label>Eligible Donation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerHandler.cls
/**
 * Created by joshlequire1 on 5/31/23.
 */

public without sharing class CampaignMemberTriggerHandler extends TriggerFactory.BaseHandler {

    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        incentiveCampaignPromotion((Map<Id, CampaignMember>) newMap, (Map<Id, CampaignMember>) oldMap);
    }

    // Move to helper class if & when necessary.
    // We're trusting that DonorCompInvocable.updateCampaignVisitCounter is firing only on ACTIVE Incentive Type Campaigns.
    public static void incentiveCampaignPromotion(Map<Id, CampaignMember> newCampaignMemberMap, Map<Id, CampaignMember> oldCampaignMemberMap) {
        Set<Id> campaignsToCheck = new Set<Id>();
        Map<Id, CampaignMember> campaignMemberMap = new Map<Id, CampaignMember>();
        Map<String, Campaign_Level__c> campaignLevelMap = new Map<String, Campaign_Level__c>();
        List<CampaignMember> campaignMemberUpdates = new List<CampaignMember>();

        for (CampaignMember cm : newCampaignMemberMap.values()) {
            CampaignMember oldCampaignMember = oldCampaignMemberMap.get(cm.Id);
            if ((cm.Eligible_Donation_Count__c > oldCampaignMember.Eligible_Donation_Count__c) ||
                (cm.Eligible_Donation_Count__c >= 1 && oldCampaignMember.Eligible_Donation_Count__c == null)) {
                campaignsToCheck.add(cm.CampaignId);
                campaignMemberMap.put(cm.Id, cm);
            }
        }

        if (campaignsToCheck.isEmpty()) {
            return;
        }

        // We're trusting that DonorCompInvocable.updateCampaignVisitCounter is firing only on ACTIVE Incentive Type Campaigns
        for (Campaign_Level__c cl : [
            SELECT Id,
                Award_Point_Amount__c,
                Award_Dollar_Amount__c,
                Campaign__c,
                Minimum_Donation_Amount__c,
                Next_Campaign_Level__c,
                Campaign__r.Enable_Payment_Requests__c,
                Campaign__r.Member_Incentive_Life_Days__c
            FROM Campaign_Level__c
            WHERE Campaign__c IN :campaignsToCheck AND
            isActive__c = TRUE
        ]) {
            campaignLevelMap.put(String.valueOf(cl.Campaign__c + '-' + cl.Minimum_Donation_Amount__c), cl);
        }

        for (CampaignMember cm : campaignMemberMap.values()) {
            Campaign_Level__c clDetail = campaignLevelMap.get(String.valueOf(cm.CampaignId + '-' + cm.Eligible_Donation_Count__c));
            if (clDetail != null &&
                ((Date.valueOf(cm.CreatedDate).daysBetween(Date.today()) <= clDetail.Campaign__r.Member_Incentive_Life_Days__c) ||
                    clDetail.Campaign__r.Member_Incentive_Life_Days__c == null)
            ) {
                CampaignMember cmUpdate = new CampaignMember(
                    Id = cm.Id,
                    Campaign_Level__c = clDetail.Id
                );
                campaignMemberUpdates.add(cmUpdate);
            }
        }

        if (!campaignMemberUpdates.isEmpty()) {
            update campaignMemberUpdates;
        }
    }
}