force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Level__c/Level__c.object-meta.xml
<CustomObject>
    <description>Loyalty tier levels</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Level__c/fields/Donation_Payment__c.field-meta.xml
<CustomField>
    <fullName>Donation_Payment__c</fullName>
    <description>The amount of payout ADJUSTMENT for each Donation for a Donor at this Level from the base RATE</description>
    <inlineHelpText>The amount of payout ADJUSTMENT for each Donation for a Donor at this Level from the base RATE</inlineHelpText>
    <label>Donation Payment Adjustment</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Level__c/fields/Donation_Points__c.field-meta.xml
<CustomField>
    <fullName>Donation_Points__c</fullName>
    <description>The number of points payout for each Donation by a Donor at this Level</description>
    <label>Donation Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Level__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type associated with this set of loyalty Levels</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Levels</relationshipLabel>
    <relationshipName>Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Payment rates for a Center&apos;s Donation Types</description>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Base_Payment__c.field-meta.xml
<CustomField>
    <fullName>Base_Payment__c</fullName>
    <description>The base amount per unit donation collected</description>
    <inlineHelpText>The base amount per unit donation collected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The donation type for this rate</description>
    <inlineHelpText>The donation type for this rate</inlineHelpText>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Unit of measure</description>
    <inlineHelpText>Unit of measure</inlineHelpText>
    <label>UOM</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RateSelector.cls
public without sharing class RateSelector {
    @AuraEnabled
    public static Rate getCenterRate(Id centerId, String targetDonationType) {
        List<Rate__c> targetCenterRateRecord;
        Level__c defaultLevel;

        try {
            defaultLevel = LoyaltyLevelService.getDefault();

            targetCenterRateRecord = [
                SELECT Id, Base_Payment__c, Donation_Type__r.Name, Center__c, UOM__c 
                FROM Rate__c 
                WHERE Center__c = :centerId AND 
                    Donation_Type__c IN (SELECT Id FROM Donation_Type__c WHERE Name = :targetDonationType)
                LIMIT 1
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        if (targetCenterRateRecord.isEmpty()) {
            throw new AuraHandledException('No rate found for ' + targetDonationType + ' at ' + centerId);
        }

        Rate targetCenterRate = new Rate(targetCenterRateRecord[0]);
        if (defaultLevel != null) {
            targetCenterRate.basePayment += defaultLevel.Donation_Payment__c;
            targetCenterRate.basePoints += defaultLevel.Donation_Points__c;
        }

        return targetCenterRate;
    }

    public class Rate {
        @AuraEnabled
        public String id {get; set;}

        @AuraEnabled
        public String center {get; set;}

        @AuraEnabled
        public String donationType {get; set;}

        @AuraEnabled
        public Decimal basePayment {get; set;}

        @AuraEnabled
        public Decimal basePoints {get; set;}

        @AuraEnabled
        public String uom {get; set;}

        public Rate(Rate__c rate) {
            this.id = rate.Id;
            this.center = rate.Center__c;
            this.donationType = rate.Donation_Type__r.Name;
            this.basePayment = rate.Base_Payment__c;
            this.uom = rate.UOM__c;

            this.basePoints = 0;
        }
    }
}