force-app/main/default/objects/PaymentService__mdt/PaymentService__mdt.object-meta.xml
<CustomObject>
    <description>Payment services supported for Proesis</description>
    <label>PaymentService</label>
    <pluralLabel>PaymentServices</pluralLabel>
</CustomObject>

force-app/main/default/objects/PaymentService__mdt/fields/ImplementationApexClass__c.field-meta.xml
<CustomField>
    <fullName>ImplementationApexClass__c</fullName>
    <label>ImplementationApexClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PaymentServiceInjector.cls
public with sharing class PaymentServiceInjector {
    public static object getService(String paymentMethod) {
        Type t;
        Map<String, String> mapServiceNameByClassName = new Map<String, String>();

        for(PaymentService__mdt service : [ select DeveloperName, ImplementationApexClass__c from PaymentService__mdt WITH SECURITY_ENFORCED ]) {
            mapServiceNameByClassName.put(service.DeveloperName, service.ImplementationApexClass__c);
        }

        String className = mapServiceNameByClassName.get(paymentMethod);
        if(className != null) {
            t = Type.forName(className);
        } else {
            t = Type.forName(mapServiceNameByClassName.get('Default'));
        }
        if (t == null) {
            throw new UnsupportedOperationException('No service found for payment method: ' + paymentMethod);
        }
        return t.newInstance();
    }

}