force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Datetime__c</fullName>
    <description>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</description>
    <inlineHelpText>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</inlineHelpText>
    <label>Appointment Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/VisitDatetimeComparer.cls
public class VisitDatetimeComparer implements Comparable {
    public Visit__c visitRecord;

    public VisitDatetimeComparer(Visit__c visitRecord) {
        this.visitRecord = visitRecord;
    }

    public Integer compareTo(Object compareTo) {
        VisitDatetimeComparer compareToVisit = (VisitDatetimeComparer)compareTo;

        if (visitRecord.Appointment_Datetime__c < compareToVisit.visitRecord.Appointment_Datetime__c) {
            return -1;
        }

        if (visitRecord.Appointment_Datetime__c > compareToVisit.visitRecord.Appointment_Datetime__c) {
            return 1;
        }
        
        return 0;
    }
}