force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>ErrorLog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ShortMessage__c.field-meta.xml
<CustomField>
    <fullName>ShortMessage__c</fullName>
    <description>Short Title of the Error</description>
    <inlineHelpText>Short Title of the Error</inlineHelpText>
    <label>Short Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Message</description>
    <inlineHelpText>Type of Error Message</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ErrorLogDefaults__c/ErrorLogDefaults__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Error Log Defaults</label>
</CustomObject>

force-app/main/default/objects/ErrorLogDefaults__c/fields/DaysBeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>DaysBeforeDelete__c</fullName>
    <defaultValue>90</defaultValue>
    <description>How many days before we delete a record?</description>
    <inlineHelpText>How many days before we delete a record?</inlineHelpText>
    <label>Days Before Delete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeleteErrorLogBatchableTest.cls
@IsTest
private without sharing class DeleteErrorLogBatchableTest {


	@IsTest
	static void testBehaviorWithOrgDefaults() {

		ErrorLogDefaults__c def = ErrorLogDefaults__c.getOrgDefaults();

		def.DaysBeforeDelete__c = 90.0;
		upsert def;

		List<ErrorLog__c> errorLogs = new List<ErrorLog__c>();

		//Created too recently
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Keep 1', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));
		//Will be deleted
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Delete 1', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Delete 2', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));

		insert errorLogs;

		Test.setCreatedDate(errorLogs[0].Id, Datetime.now().addDays(-100));
		Test.setCreatedDate(errorLogs[1].Id, Datetime.now().addDays(-101));

		Test.startTest();

		DeleteErrorLogBatchable deleteErrorLogsBatch = new DeleteErrorLogBatchable();

		Database.executeBatch(deleteErrorLogsBatch, 10);

		Test.stopTest();

		errorLogs = [
				SELECT Id
				FROM ErrorLog__c
		];

		System.assertEquals(1, errorLogs.size());


	}

	@IsTest
	static void testBehaviorWithoutOrgDefaults() {

		List<ErrorLog__c> errorLogs = new List<ErrorLog__c>();

		//Created too recently
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Keep 1', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));
		//Will be deleted
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Delete 1', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));
		errorLogs.add(new ErrorLog__c(ShortMessage__c = 'Delete 2', Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR));

		insert errorLogs;

		Test.setCreatedDate(errorLogs[0].Id, Datetime.now().addDays(-100));
		Test.setCreatedDate(errorLogs[1].Id, Datetime.now().addDays(-101));

		Test.startTest();

		DeleteErrorLogBatchable deleteErrorLogsBatch = new DeleteErrorLogBatchable();

		Database.executeBatch(deleteErrorLogsBatch, 10);

		Test.stopTest();

		errorLogs = [
				SELECT Id
				FROM ErrorLog__c
		];

		System.assertEquals(1, errorLogs.size());


	}	

	@IsTest
	static void testSchedulable() {

		Test.startTest();

		DeleteErrorLogBatchable.selfSchedule();

		Test.stopTest();

	}
}