force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>ErrorLog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/AdditionalInfo__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInfo__c</fullName>
    <description>Additional info about the error, record details, or JSON payload</description>
    <inlineHelpText>Additional info about the error, record details, or JSON payload</inlineHelpText>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ErrorDate__c.field-meta.xml
<CustomField>
    <fullName>ErrorDate__c</fullName>
    <description>Date/Time where the error occurred</description>
    <inlineHelpText>Date/Time where the error occurred</inlineHelpText>
    <label>Error Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/LongMessage__c.field-meta.xml
<CustomField>
    <fullName>LongMessage__c</fullName>
    <description>Error Message with all the details</description>
    <inlineHelpText>Error Message with all the details</inlineHelpText>
    <label>Long Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Action or Code Area that led to the error</description>
    <inlineHelpText>Action or Code Area that led to the error</inlineHelpText>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Identifying Info of the Record (if any) that threw this error. May not be an id if it&apos;s an insert call</description>
    <inlineHelpText>Identifying Info of the Record (if any) that threw this error. May not be an id if it&apos;s an insert call</inlineHelpText>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ShortMessage__c.field-meta.xml
<CustomField>
    <fullName>ShortMessage__c</fullName>
    <description>Short Title of the Error</description>
    <inlineHelpText>Short Title of the Error</inlineHelpText>
    <label>Short Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Message</description>
    <inlineHelpText>Type of Error Message</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogServiceTest.cls
@IsTest
private without sharing class ErrorLogServiceTest {

	@TestSetup
	static void setup() {
		//Nothing to do in this case
	}

	@IsTest
	static void testNormalCreation() {
		ErrorLog__c log1 = ErrorLogService.createErrorLog('a', 'b',  CONSTANTS.ERRORLOG_TYPE_WARNING,'c', 'd');

		System.assertEquals('a', log1.RecordId__c);
		System.assertEquals('b', log1.Origin__c);
		System.assertEquals('c', log1.ShortMessage__c);
		System.assertEquals('d', log1.LongMessage__c);
		System.assertEquals(CONSTANTS.ERRORLOG_TYPE_WARNING, log1.Type__c);
	}

	@IsTest
	static void testCreationFromException() {
		ErrorLog__c log1;

		try {
			throw new ErrorLogServiceTestException('PEPE');
		} catch (Exception e) {
			log1 = ErrorLogService.createErrorLogFromException('a', 'b', CONSTANTS.ERRORLOG_TYPE_ERROR, e);
		}

		System.assertEquals('a', log1.RecordId__c);
		System.assertEquals('b', log1.Origin__c);
		System.assertEquals('PEPE', log1.ShortMessage__c);
		System.assertEquals(CONSTANTS.ERRORLOG_TYPE_ERROR, log1.Type__c);
	}

	@IsTest
	static void testLogError() {
		Test.startTest();
		ErrorLogService.logError('0012200000Ve6t9','Unit Test','Short Message','Long Message','addInfo');
		Test.stopTest();
		List<ErrorLog__c> logs = [Select RecordId__c,ErrorDate__c,Origin__c,ShortMessage__c,LongMessage__c,Type__c,AdditionalInfo__c From ErrorLog__c];
		System.assertEquals('0012200000Ve6t9', logs[0].RecordId__c);
		System.assertEquals('Unit Test', logs[0].Origin__c);
		System.assertEquals('Short Message', logs[0].ShortMessage__c);
		System.assertEquals('Long Message', logs[0].LongMessage__c);
		System.assertEquals('addInfo', logs[0].AdditionalInfo__c);
	}

	public class ErrorLogServiceTestException extends Exception {}
}