force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <description>All messages for users of the mobile Donor app</description>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the Center, specifically for Center related broadcast (or other) messages, to show what messages where emitted from a Center.</description>
    <inlineHelpText>Indicates the Center, specifically for Center related broadcast (or other) messages, to show what messages where emitted from a Center.</inlineHelpText>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Messages</relationshipLabel>
    <relationshipName>CenterMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Indicates the date the message will expire.</description>
    <inlineHelpText>Indicates the date the message will expire.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/isViewed__c.field-meta.xml
<CustomField>
    <fullName>isViewed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the recipient viewed this message?</description>
    <label>is Viewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Viewed_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Datetime__c</fullName>
    <description>The datetime this message was viewed</description>
    <label>Viewed Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/NotificationsControllerTest.cls
@isTest
public with sharing class NotificationsControllerTest {

    @isTest
    static void testHasUnreadNotificationsTrue() {
        User experienceUser = TestUtil.createExperienceUser();

        System.runAs(TestUtil.createAdminUser()) {
            Message__c message = new Message__c();
            message.Donor__c = experienceUser.ContactId;
            message.Name = 'Subject';
            message.Body__c = 'Body';
            message.Expiration_Date__c = Date.today().addDays(5);
            insert message;
        }

        System.runAs(experienceUser) {
            Boolean hasUnreadNotifications = NotificationsController.hasUnreadNotifications();

            System.assertEquals(true, hasUnreadNotifications);
        }
    }

    @isTest
    static void testHasUnreadNotificationsFalse() {
        User experienceUser = TestUtil.createExperienceUser();

        System.runAs(TestUtil.createAdminUser()) {
            Message__c message = new Message__c();
            message.Donor__c = experienceUser.ContactId;
            message.Name = 'Subject';
            message.Body__c = 'Body';
            message.Expiration_Date__c = Date.today().addDays(-5);
            insert message;
        }

        System.runAs(experienceUser) {
            Boolean hasUnreadNotifications = NotificationsController.hasUnreadNotifications();

            System.assertEquals(false, hasUnreadNotifications);
        }
    }

    @isTest
    static void testHasUnreadNotificationsException() {
        TestUtil.throwException = true;

        System.runAs(TestUtil.createExperienceGuestUser()) {
            Boolean exceptionThrown = false;

            try {
                NotificationsController.hasUnreadNotifications();
            } catch (Exception e) {
                exceptionThrown = true;
            }

            System.assert(exceptionThrown);
        }
    }

    @isTest
    static void testGetNotificationsDonor() {
        User experienceUser = TestUtil.createExperienceUser();

        System.runAs(TestUtil.createAdminUser()) {
            Message__c message = new Message__c();
            message.Donor__c = experienceUser.ContactId;
            message.Name = 'Subject';
            message.Body__c = 'Body';
            message.Expiration_Date__c = Date.today().addDays(5);

            Message__c expiredMessage = new Message__c();
            expiredMessage.Donor__c = experienceUser.ContactId;
            expiredMessage.Name = 'Expired Subject';
            expiredMessage.Body__c = 'Expired Body';
            expiredMessage.Expiration_Date__c = Date.today().addDays(-5);

            insert new List<Message__c>{message, expiredMessage};
        }

        System.runAs(experienceUser) {
            List<NotificationsController.Notification> notifications = NotificationsController.getNotifications(null);

            System.assertEquals(1, notifications.size());
            System.assertEquals('Subject', notifications[0].subject);
            System.assertEquals('Body', notifications[0].body);
        }
    }

    @isTest
    static void testGetNotificationsCenter() {
        User experienceUser = TestUtil.createExperienceUser();
        Account center;

        System.runAs(TestUtil.createAdminUser()) {
            center = TestUtil.createMiramarCenter();
            insert center;

            Message__c message = new Message__c();
            message.Center__c = center.Id;
            message.Name = 'Subject';
            message.Body__c = 'Body';
            message.Expiration_Date__c = Date.today().addDays(5);

            Message__c expiredMessage = new Message__c();
            expiredMessage.Center__c = center.Id;
            expiredMessage.Name = 'Expired Subject';
            expiredMessage.Body__c = 'Expired Body';
            expiredMessage.Expiration_Date__c = Date.today().addDays(-5);

            insert new List<Message__c>{message, expiredMessage};
        }

        System.runAs(experienceUser) {
            List<NotificationsController.Notification> notifications = NotificationsController.getNotifications(center.Id);

            System.assertEquals(1, notifications.size());
            System.assertEquals('Subject', notifications[0].subject);
            System.assertEquals('Body', notifications[0].body);
        }
    }

    @isTest
    static void testGetNotificationsException() {
        TestUtil.throwException = true;

        System.runAs(TestUtil.createExperienceGuestUser()) {
            Boolean exceptionThrown = false;

            try {
                NotificationsController.getNotifications(null);
            } catch (Exception e) {
                exceptionThrown = true;
            }

            System.assert(exceptionThrown);
        }
    }

    @isTest
    static void testViewNotification() {
        User adminUser = TestUtil.createAdminUser();
        User experienceUser = TestUtil.createExperienceUser();
        Message__c message;

        System.runAs(adminUser) {
            message = new Message__c();
            message.Donor__c = experienceUser.ContactId;
            message.Name = 'Subject';
            message.Body__c = 'Body';
            message.Expiration_Date__c = Date.today().addDays(5);
            insert message;
        }

        System.runAs(experienceUser) {
            NotificationsController.Notification notification = NotificationsController.viewNotification(message.Id);

            System.assertEquals('Subject', notification.subject);
            System.assertEquals('Body', notification.body);
        }

        System.runAs(adminUser) {
            Message__c updatedMessage = [SELECT isViewed__c, Viewed_Datetime__c FROM Message__c WHERE Id = :message.Id];

            System.assertEquals(true, updatedMessage.isViewed__c);
            System.assertNotEquals(null, updatedMessage.Viewed_Datetime__c);
        }
    }

    @isTest
    static void testViewNotificationsException() {
        TestUtil.throwException = true;

        System.runAs(TestUtil.createExperienceGuestUser()) {
            Boolean exceptionThrown = false;

            try {
                NotificationsController.viewNotification(null);
            } catch (Exception e) {
                exceptionThrown = true;
            }

            System.assert(exceptionThrown);
        }
    }

}