force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Date_Center__c.field-meta.xml
<CustomField>
    <fullName>Date_Center__c</fullName>
    <description>Date of this appointment in the center&apos;s time zone.</description>
    <label>Date (Center)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration in minutes, set by the Schedule Template used to generate the Schedule</description>
    <label>Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Time_Center__c.field-meta.xml
<CustomField>
    <fullName>Time_Center__c</fullName>
    <description>Time of this appointment in the center&apos;s time zone.</description>
    <label>Time (Center)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>The beginning date for the Schedule inclusive.</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day for this Schedule inclusive.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AppointmentTriggerHandlerTest.cls
@isTest
public with sharing class AppointmentTriggerHandlerTest {

    @isTest
    static void testSetCenterDateAndTime() {
        User experienceUser = TestUtil.createExperienceUser();

        System.runAs(TestUtil.createAdminUser()) {
            Account center = TestUtil.createMiramarCenter();
            insert center;

            Schedule__c schedule = new Schedule__c(
                Center__c = center.Id,
                Begin_Date__c = Date.newInstance(2023, 1, 10).addDays(-10),
                End_Date__c = Date.newInstance(2023, 1, 10).addDays(30)
            );
            insert schedule;

            Appointment__c appointment = new Appointment__c();
            appointment.Schedule__c = schedule.Id;
            appointment.Datetime__c = DateTime.newInstance(2023, 1, 10, 10, 0, 0);
            appointment.Duration__c = 10;
            appointment.Capacity__c = 5;
            insert appointment;

            Appointment__c updatedAppointment = [SELECT Date_Center__c, Time_Center__c FROM Appointment__c WHERE Id = :appointment.Id];

            System.assertEquals(Util.getTimeZoneDate(appointment.Datetime__c, experienceUser.TimeZoneSidKey), updatedAppointment.Date_Center__c);
            System.assertEquals(Util.getTimeZoneTime(appointment.Datetime__c, experienceUser.TimeZoneSidKey), updatedAppointment.Time_Center__c);
        }
    }

}