force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/Donor.recordType-meta.xml
<RecordType>
    <fullName>Donor</fullName>
    <active>true</active>
    <label>Donor</label>
    
</RecordType>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>The beginning date for the Schedule inclusive.</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day for this Schedule inclusive.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduleUtils_Test.cls
@isTest
public with sharing class ScheduleUtils_Test {
    
    @TestSetup
    static void makeData(){
        Id centerRecordTypeID =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Center').getRecordTypeId();
        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();

        system.debug('centerRecordTypeID' + centerRecordTypeID);
        system.debug('personAccountRecordTypeId' + personAccountRecordTypeId);


        // Create Donors
        Account[] donors = new Account[]{
            new Account(
                FirstName = 'Danny',
                LastName = 'Donor',
                RecordTypeID = personAccountRecordTypeId,
                ExternalID__c = 'donor-12345'
            ),
            new Account(
                FirstName = 'Betty',
                LastName = 'Bleeder',
                RecordTypeID = personAccountRecordTypeId,
                ExternalID__c = 'donor-67890'
            )
        };

        upsert donors ExternalID__c;

        //Create Donation Centers
        Account[] centers = new Account[]{
            new Account(
                Name = 'Center 1',
                RecordTypeID = centerRecordTypeID,
                ShippingStreet = '111 1st St',
                ExternalID__c = 'center-111'
            ),
            new Account(
                Name = 'Center 2',
                RecordTypeID = centerRecordTypeID,
                ShippingStreet = '222 @nd St',
                ExternalID__c = 'center-222'
            ),
            new Account(
                Name = 'Center 3',
                RecordTypeID = centerRecordTypeID,
                ShippingStreet = '333 3rd St',
                ExternalID__c = 'center-333'
            )
        };

        upsert centers ExternalID__c; 


        Schedule__c[] schedules = new Schedule__c[]{
            new Schedule__c(
                Center__c = centers[0].Id, 
                Begin_Date__c = Date.today().addDays(-10),
                End_Date__c = Date.today().addDays(30)
            ),
            new Schedule__c(
                Center__c = centers[1].Id,
                Begin_Date__c = Date.today().addDays(-10),
                End_Date__c = Date.today().addDays(30)
            ),
            new Schedule__c(
                Center__c = centers[2].Id,
                Begin_Date__c = Date.today().addDays(-10),
                End_Date__c = Date.today().addDays(30)
            )
        };

        insert schedules;
    }
    
    
    @isTest
    static void ScheduleUtils_Test() {

        Appointment__c[] appointments;
        Test.startTest();

        // create a set of appointment slots
        Date startDate =  Date.newInstance(2023, 1, 10);
        Date endDate = startDate.addDays(30);
        Id loyaltyTier = null;
        Integer intervalsPerHour = 6; //10 minutes apart
        Integer slotsPerInterval = 1;

        Account center1 = [SELECT Id FROM Account WHERE Name = 'Center 1'];

        //scheduleRange(Id centerId, Date startDate, Date endDate, Id loyaltyTier, Integer intervalsPerHour, Integer slotsPerInterval)
        appointments = ScheduleUtils.scheduleRange(center1.id,startDate,endDate,loyaltyTier,intervalsPerHour,slotsPerInterval);

        insert appointments;

        Test.stopTest();
        system.assertEquals(1980,appointments.size());
    }
}