force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Level__c/Level__c.object-meta.xml
<CustomObject>
    <description>Loyalty tier levels</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Level__c/fields/Donation_Payment__c.field-meta.xml
<CustomField>
    <fullName>Donation_Payment__c</fullName>
    <description>The amount of payout ADJUSTMENT for each Donation for a Donor at this Level from the base RATE</description>
    <inlineHelpText>The amount of payout ADJUSTMENT for each Donation for a Donor at this Level from the base RATE</inlineHelpText>
    <label>Donation Payment Adjustment</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Level__c/fields/Donation_Points__c.field-meta.xml
<CustomField>
    <fullName>Donation_Points__c</fullName>
    <description>The number of points payout for each Donation by a Donor at this Level</description>
    <label>Donation Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Level__c/fields/Donation_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Donation_Threshold__c</fullName>
    <description>Number of donations where Level is valid e.g. 31 means the Level applies at 31st donation.</description>
    <inlineHelpText>The donation number where this Level applies</inlineHelpText>
    <label>Donation Threshold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Level__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type associated with this set of loyalty Levels</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Levels</relationshipLabel>
    <relationshipName>Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Payment rates for a Center&apos;s Donation Types</description>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Base_Payment__c.field-meta.xml
<CustomField>
    <fullName>Base_Payment__c</fullName>
    <description>The base amount per unit donation collected</description>
    <inlineHelpText>The base amount per unit donation collected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The donation type for this rate</description>
    <inlineHelpText>The donation type for this rate</inlineHelpText>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Unit of measure</description>
    <inlineHelpText>Unit of measure</inlineHelpText>
    <label>UOM</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RateSelectorTest.cls
@IsTest
public without sharing class RateSelectorTest {
    private static final String TEST_DONATION_TYPE = 'Normal Plasma';
    private static final Integer TEST_BASE_PAYMENT = 50;
    private static final String TEST_UOM = 'visit';

    @TestSetup
    static void createTestData() {
        Account testCenter = TestUtil.createMiramarCenter();
        insert testCenter;

        Donation_Type__c testDonationType = new Donation_Type__c(Name = TEST_DONATION_TYPE);
        insert testDonationType;

        Rate__c testRate = new Rate__c(
            Donation_Type__c = testDonationType.Id,
            Center__c = testCenter.Id,
            Base_Payment__c = TEST_BASE_PAYMENT,
            UOM__c = TEST_UOM,
            Type__c = 'Base'
        );
        insert testRate;

        Level__c defaultLevel = new Level__c(
            Name = 'Default',
            Donation_Threshold__c = 0,
            Donation_Payment__c = TEST_BASE_PAYMENT,
            Donation_Points__c = TEST_BASE_PAYMENT
        );
        insert defaultLevel;
    }

    @IsTest 
    static void testGetCenterRate() {
        Account center = [SELECT Id FROM Account WHERE RecordType.DeveloperName = 'Center' LIMIT 1];
        Rate__c targetRateRecord = [SELECT Id FROM Rate__c WHERE Center__c = :center.Id LIMIT 1];
        RateSelector.Rate foundRate;

        Test.startTest();
        foundRate = RateSelector.getCenterRate(center.Id, TEST_DONATION_TYPE);
        Test.stopTest();

        Assert.isNotNull(foundRate, 'A rate should have been returned');
        Assert.areEqual(foundRate.basePayment, TEST_BASE_PAYMENT * 2, 'The base payment should have been returned');
        Assert.areEqual(foundRate.basePoints, TEST_BASE_PAYMENT, 'The base points should have been returned');
        Assert.areEqual(foundRate.uom, TEST_UOM, 'The uom should have been returned');
        Assert.areEqual(foundRate.donationType, TEST_DONATION_TYPE, 'The donation type should have been returned');
        Assert.areEqual(foundRate.center, center.Id, 'The center Id should have been returned');
        Assert.areEqual(foundRate.id, targetRateRecord.Id, 'The rate Id should have been returned');
    }
}