force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Volume__c.field-meta.xml
<CustomField>
    <fullName>Donation_Volume__c</fullName>
    <description>Donation in cc</description>
    <label>Donation Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EndOfDayVisitBatchable.cls
public without sharing class EndOfDayVisitBatchable implements Database.Batchable<SObject>, Schedulable, Database.Stateful {
    final static String VISIT_STATUS_NEW = 'New';
    final static String VISIT_STATUS_SCHEDULED = 'Scheduled';
    final static String VISIT_STATUS_CHECKED_IN = 'Checked-In';
    final static String VISIT_STATUS_COMPLETE = 'Complete';

    Group proesisOperationsQueue; // Fallback queue in case a center manager queue can't be found
    Map<String, Group> centerManagerQueues;

    public static void run() {
        Database.executeBatch(new EndOfDayVisitBatchable());
    }

    public void execute(SchedulableContext sc) {
		EndOfDayVisitBatchable endOfDayVisitBatchable = new EndOfDayVisitBatchable();

		Database.executeBatch(endOfDayVisitBatchable, 200);
	}

    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Initialize the center manager queues
        centerManagerQueues = new Map<String, Group>();

        for (Group targetedQueue : [SELECT Id, DeveloperName FROM Group WHERE Type = 'Queue' AND (DeveloperName LIKE 'Center_Manager_%' OR DeveloperName = 'Proesis_Operations')]) {
            if (targetedQueue.DeveloperName == 'Proesis_Operations') {
                proesisOperationsQueue = targetedQueue;
            } else if (targetedQueue.DeveloperName.startsWith('Center_Manager_')) {
                centerManagerQueues.put(targetedQueue.DeveloperName, targetedQueue);
            }
        }

        // Query all incomplete visits in the past so we can update them
        Set<String> visitStatuses = new Set<String>{ VISIT_STATUS_NEW, VISIT_STATUS_SCHEDULED, VISIT_STATUS_CHECKED_IN };

        return Database.getQueryLocator([
            SELECT Id, Outcome__c, Status__c, Donation_Volume__c, Center_Donation_Type__r.Center__r.Name, Donor__c
            FROM Visit__c
            WHERE Appointment__r.Datetime__c < :System.now() AND
                (Outcome__c = null OR Status__c IN :visitStatuses)
        ]);
    }

    public void execute(Database.BatchableContext context, List<Visit__c> visits) {
		Savepoint sp = Database.setSavepoint();
        try {
            process_visits(visits);
        } catch (Exception e) {
            Database.rollback(sp);
            System.abortJob(context.getJobId());
        }
	}

    public void process_visits(List<Visit__c> visits) {
        List<Task> tasksToInsert = new List<Task>();

        for(Visit__c visit: visits) {
            String visitStatus = visit.Status__c;

            if (visitStatus != VISIT_STATUS_COMPLETE) {
                if (visitStatus == VISIT_STATUS_NEW) {
                    visit.Outcome__c = 'Canceled';
                } else if (visitStatus == VISIT_STATUS_SCHEDULED) {
                    visit.Outcome__c = 'No Show';
                } else if (visitStatus == VISIT_STATUS_CHECKED_IN) {
                    visit.Outcome__c = 'No Donation';
                }

                visit.Status__c = VISIT_STATUS_COMPLETE;
            } else {
                if (visit.Donation_Volume__c == null || visit.Donation_Volume__c <= 0) {
                    visit.Outcome__c = 'No Donation';
                    continue;
                }
                
                visit.Outcome__c = 'Donation';

                // Make a task noting a visit with a donation was made but wasn't recorded
                Group targetQueue = centerManagerQueues.get('Center_Manager_' + visit.Center_Donation_Type__r.Center__r.Name.replaceAll(' ', '_'));
                if (targetQueue == null && proesisOperationsQueue != null) {
                    targetQueue = proesisOperationsQueue;
                } else {
                    throw new QueryException('No queue found for center ' + visit.Center_Donation_Type__r.Center__r.Name);
                }

                tasksToInsert.add(new Task(
                    WhoId = visit.Donor__c,
                    WhatId = visit.Id,
                    Subject = Constants.UNMARKED_DONATION_TASK_SUBJECT,
                    Description = Constants.UNMARKED_DONATION_TASK_DESCRIPTION,
                    OwnerId = targetQueue.Id
                ));
            }
        }

        if (!tasksToInsert.isEmpty()) {
            insert tasksToInsert;
        }

        update visits;
    }

	public void finish(Database.BatchableContext BC) {

	}

    public static void scheduleDaily() {

		EndOfDayVisitBatchable endOfDayVisitBatchable = new EndOfDayVisitBatchable();

		String suffix = '';
		if (Test.isRunningTest()) {
			suffix = ' - ' + String.valueOf((Math.random() * 100));
		}

		//Nightly at 12am
		String CRON_TIME = '0 0 0 * * ?';

		System.schedule('End of Day Visit Status Updates' + suffix, CRON_TIME, endOfDayVisitBatchable);
	}
    
}