force-app/main/default/objects/Account/fields/Center_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Center_Timezone__c</fullName>
    <label>Center Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Chicago</fullName>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <description>Capacity - Booked</description>
    <formula>Capacity__c - Booked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The available Appointment slots</inlineHelpText>
    <label>Availability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Availability_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Availability_Loyalty__c</fullName>
    <formula>Capacity_Loyalty__c - Booked_Loyalty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Availability Loyalty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Booked__c.field-meta.xml
<CustomField>
    <fullName>Booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Visits booked into this Appointment slot. Will be updated by the API for scheduling a Visit.</description>
    <label>Booked</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Booked_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Booked_Loyalty__c</fullName>
    <label>Booked Loyalty</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Capacity_Loyalty__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Loyalty__c</fullName>
    <description>Using the Custom Setting for percentage of overage, calculates the capacity for accommodating loyalty donors for a given Appointment slot</description>
    <formula>CEILING ( $Setup.Loyalty__c.Appointment_Capacity_Factor__c * Capacity__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Using the Custom Setting for percentage of overage, calculates the capacity for accommodating loyalty donors for a given Appointment slot</inlineHelpText>
    <label>Capacity Loyalty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Loyalty_Level__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loyalty Level</label>
    <referenceTo>Level__c</referenceTo>
    <relationshipLabel>Donors</relationshipLabel>
    <relationshipName>Donors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Rescheduled_Visit__c.field-meta.xml
<CustomField>
    <fullName>Rescheduled_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This refers to the new Visit created when an existing Visit is rescheduled.</description>
    <label>Rescheduled Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Rescheduled Visits</relationshipLabel>
    <relationshipName>Rescheduled_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CoreSchedulerHandler.cls
public without sharing class CoreSchedulerHandler {
    public static void rescheduleVisit(RescheduleRequest rescheduleRequest) {
        rescheduleVisits(new RescheduleBatchRequest(new List<RescheduleRequest>{ rescheduleRequest }));
    }
    
    public static void rescheduleVisits(RescheduleBatchRequest rescheduleBatchRequest) {
        rescheduleBatchRequest.initializeRescheduleRequestData();

        List<Visit__c> visitsToUpdate = new List<Visit__c>();
        List<Visit__c> visitsToInsert = new List<Visit__c>();
        List<Task> tasksToUpdate = new List<Task>();

        for(RescheduleRequest request : rescheduleBatchRequest.rescheduleRequests) {
            visitsToInsert.add(request.createNewVisit());
            visitsToUpdate.add(request.markOriginalVisitAsRescheduled());
        }

        if (visitsToUpdate.size() > 0) {
            update visitsToUpdate;
        }

        if (visitsToInsert.size() > 0) {
            createVisits(visitsToInsert);
        }

        // We need to insert the new visits before we can reparent the tasks
        for(RescheduleRequest request : rescheduleBatchRequest.rescheduleRequests) {
            tasksToUpdate.addAll(request.reparentTasksToNewVisit());
        }

        if (tasksToUpdate.size() > 0) {
            update tasksToUpdate;
        }
    }

    public static Visit__c createVisit(Visit__c newVisit) {
        return createVisits(new List<Visit__c> { newVisit })[0];
    }

    public static List<Visit__c> createVisits(List<Visit__c> newVisits) {
        Set<Id> appointmentIds = new Set<Id>();
        Set<Id> donorIds = new Set<Id>();
        List<FdaVisitValidator.FdaValidationRequest> fdaVisitValidationRequests = new List<FdaVisitValidator.FdaValidationRequest>();

        for(Visit__c visit : newVisits) {
            appointmentIds.add(visit.Appointment__c);
            donorIds.add(visit.Donor__c);
            fdaVisitValidationRequests.add(new FdaVisitValidator.FdaValidationRequest(visit.Appointment__c, visit.Donor__c, visit.Center_Donation_Type__c));
        }

        FdaVisitValidator validatorInstance = new FdaVisitValidator(fdaVisitValidationRequests);
        fdaVisitValidationRequests = validatorInstance.validateCreateVisitRequests();
        
        for(FdaVisitValidator.FdaValidationRequest request : fdaVisitValidationRequests) {
            if (request.validationResult != null && !request.validationResult.isValid) {
                throw new CoreScheduleException(request.validationResult.errorMessage);
            }
        }

        Map<Id, Appointment__c> appointments = new Map<Id, Appointment__c>([SELECT Id, Availability__c, Availability_Loyalty__c, Datetime__c, Schedule__r.Center__r.Center_Timezone__c FROM Appointment__c WHERE Id IN :appointmentIds FOR UPDATE]);
        Map<Id, Contact> donors = new Map<Id, Contact>([SELECT Id, Loyalty_Level__c FROM Contact WHERE Id IN :donorIds]);

        Map<Id, Decimal> appointmentAvailabilities = new Map<Id, Decimal>();
        Map<Id, Decimal> appointmentLoyaltyAvailabilities = new Map<Id, Decimal>();

        for(Visit__c visit : newVisits) {
            Appointment__c appointment = appointments.get(visit.Appointment__c);
            Contact donor = donors.get(visit.Donor__c);

            Integer donorLoyaltyLevel = LoyaltyLevelService.getLoyaltyLevel(donor.Loyalty_Level__c);
            Boolean qualifiesForLoyalty = donorLoyaltyLevel > 0;

            Decimal availabilityAdjustment = appointmentAvailabilities.containsKey(visit.Appointment__c) ? appointmentAvailabilities.get(visit.Appointment__c) : 0;
            Decimal loyaltyAvailabilityAdjustment = appointmentLoyaltyAvailabilities.containsKey(visit.Appointment__c) ? appointmentLoyaltyAvailabilities.get(visit.Appointment__c) : 0;

            Decimal adjustedAvailability = appointment.Availability__c - availabilityAdjustment;
            Decimal adjustedLoyaltyAvailability = appointment.Availability_Loyalty__c - loyaltyAvailabilityAdjustment;

            if (adjustedAvailability == 0 && (!qualifiesForLoyalty || (qualifiesForLoyalty && adjustedLoyaltyAvailability == 0))) {
                throw new CoreScheduleException(Constants.OVER_CAPACITY_ADD_VISIT_EXCEPTION_MESSAGE);
            } else {
                if (adjustedAvailability > 0) {
                    appointmentAvailabilities.put(visit.Appointment__c, availabilityAdjustment + 1);
                } else if (qualifiesForLoyalty && adjustedLoyaltyAvailability > 0) {
                    appointmentLoyaltyAvailabilities.put(visit.Appointment__c, loyaltyAvailabilityAdjustment + 1);
                }
            }
        }

        insert newVisits;
        return newVisits;
    }

    public static void cancelVisit(Id visitId) {
        cancelVisits(new List<Id> { visitId });
    }

    public static void cancelVisits(List<Id> visitIds) {
        List<Visit__c> visitsToUpdate = new List<Visit__c>();

        for(Id visitId : visitIds) {
            visitsToUpdate.add(new Visit__c(
                Id = visitId,
                Status__c = 'Complete',
                Outcome__c = 'Canceled'
            ));
        }

        update visitsToUpdate;
    }

    public class RescheduleBatchRequest {
        public List<RescheduleRequest> rescheduleRequests;
    
        public RescheduleBatchRequest(List<RescheduleRequest> rescheduleRequests) {
            this.rescheduleRequests = rescheduleRequests;
        }
    
        private void initializeRescheduleRequestData() {
            // Query all the required data
            Set<Id> appointmentSlotIds = new Set<Id>();
            Set<Id> visitIds = new Set<Id>();
    
            for(RescheduleRequest request : rescheduleRequests) {
                appointmentSlotIds.add(request.newAppointmentSlotId);
                visitIds.add(request.originalVisitId);
            }
    
            Map<Id, Appointment__c> appointmentSlots = new Map<Id, Appointment__c>([SELECT Id, Booked__c, Booked_Loyalty__c, Capacity__c, Capacity_Loyalty__c FROM Appointment__c WHERE Id IN :appointmentSlotIds]);
            Map<Id, Visit__c> visits = new Map<Id, Visit__c>([
                SELECT Id, Center_Donation_Type__c, Appointment__c, Appointment__r.Booked__c, Appointment__r.Booked_Loyalty__c,
                    Appointment__r.Capacity__c, Appointment__r.Capacity_Loyalty__c, Donor__r.Loyalty_Level__c, 
                    (
                        SELECT Id 
                        FROM Tasks
                    ) 
                FROM Visit__c 
                WHERE Id IN :visitIds
            ]);
    
            for(RescheduleRequest request : rescheduleRequests) {
                request.populateData(appointmentSlots.get(request.newAppointmentSlotId), visits.get(request.originalVisitId));
            }
        }
    }
    
    public class RescheduleRequest {
        public Id originalVisitId;
        public Id newAppointmentSlotId;
    
        private Contact donor;
        private Appointment__c oldAppointmentSlot;
        private Appointment__c newAppointmentSlot;
    
        private Visit__c originalVisit;
        private Visit__c newVisit;
    
        public RescheduleRequest(Id originalVisitId, Id newAppointmentSlotId) {
            this.originalVisitId = originalVisitId;
            this.newAppointmentSlotId = newAppointmentSlotId;
        }
    
        public void populateData(Appointment__c newAppointmentSlot, Visit__c originalVisit) {
            this.donor = originalVisit.Donor__r;
            this.newAppointmentSlot = newAppointmentSlot;
            this.oldAppointmentSlot = originalVisit.Appointment__r;
            this.originalVisit = originalVisit;
        }
    
        public Visit__c createNewVisit() {
            this.newVisit = originalVisit.clone(false, true, false, false);
    
            newVisit.Rescheduled_Visit__c = originalVisit.Id;
            newVisit.Appointment__c = newAppointmentSlot.Id;
            newVisit.Status__c = 'Scheduled';
    
            return this.newVisit;
        }
    
        public List<Task> reparentTasksToNewVisit() {
            if (originalVisit.Tasks != null && originalVisit.Tasks.size() > 0) {
                for (Task task : originalVisit.Tasks) {
                    task.WhatId = newVisit.Id;
                }
            }
    
            return originalVisit.Tasks;
        }
    
        public Visit__c markOriginalVisitAsRescheduled() {
            originalVisit.Status__c = 'Complete';
            originalVisit.Outcome__c = 'Rescheduled';
    
            return originalVisit;
        }
    }

    public class CoreScheduleException extends Exception { }
}