force-app/main/default/objects/Account/fields/CenterId__c.field-meta.xml
<CustomField>
    <fullName>CenterId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The unique external identifier for Centers</description>
    <externalId>true</externalId>
    <label>CenterId</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/First_Visit_Code__c.field-meta.xml
<CustomField>
    <fullName>First_Visit_Code__c</fullName>
    <externalId>true</externalId>
    <label>First Visit Code</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <description>The services offered at a given donation Center</description>
    <label>Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Center_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration in minutes, set by the Schedule Template used to generate the Schedule</description>
    <label>Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/Business_Hours__c.object-meta.xml
<CustomObject>
    <description>Hours of business available for scheduling Donors</description>
    <label>Business Hours</label>
    <nameField>
        <label>Business Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Hours__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Hours</relationshipLabel>
    <relationshipName>Business_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <description>Closing time</description>
    <label>Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>1-based index of Days of Week</description>
    <label>Index</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <description>Open time</description>
    <label>Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the setup of a new Donation Type for a Center without affecting processing until active=True</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>The beginning date for the Schedule inclusive.</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day for this Schedule inclusive.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of donation for this Visit</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Center_Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Donation</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: New Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: Annual Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: Consultation</fullName>
    </customValue>
    <description>The types of services offered by a Donation Center</description>
    <masterLabel>Center Services</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestUtil.cls
public with sharing class TestUtil {

    public static Boolean throwException = false;

    public static User createAdminUser() {
        UserRole userRole = new UserRole(
            Name = 'AdminTest'
        );
        insert userRole;

        String userEmail = 'admin@' + UserInfo.getOrganizationId() + '.test.com';

        User user = new User(
            FirstName = 'Admin',
            LastName = 'User',
            Email = userEmail,
            Username = userEmail,
            Alias = 'admin',
            Phone = '800-555-1212',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            UserRoleId = userRole.Id
        );
        insert user;

        PermissionSet adminPermissionSet = [SELECT Id FROM PermissionSet WHERE Label = :Constants.ADMIN_PERMISSION_SET_NAME];

        insert new PermissionSetAssignment(
            PermissionSetId = adminPermissionSet.Id,
            AssigneeId = user.Id
        );

        return user;
    }

    public static User createExperienceUser() {
        UserRole userRole = new UserRole(
            Name = 'Test'
        );
        insert userRole;

        String userWithRoleEmail = 'userwithrole@' + UserInfo.getOrganizationId() + '.test.com';

        User userWithRole = new User(
            FirstName = 'Role',
            LastName = 'User',
            Email = userWithRoleEmail,
            Username = userWithRoleEmail,
            Alias = 'withrole',
            Phone = '800-555-1212',
            ProfileId = UserInfo.getProfileId(),
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            UserRoleId = userRole.Id
        );
        insert userWithRole;

        Account account;
        Contact contact;
        User experienceUser;

        System.runAs(userWithRole) {
            Account = new Account(
                FirstName = 'Test',
                LastName = 'Last',
                First_Visit_Code__c = ScheduleUtils.createFirstVisitCode(),
                RecordTypeId = Constants.DONOR_RECORD_TYPE_ID
            );
            insert account;

            String experienceUserEmail = 'experience@' + UserInfo.getOrganizationId() + '.test.com';

            experienceUser = new User(
                FirstName = 'Experience',
                LastName = 'User',
                Email = experienceUserEmail,
                Username = experienceUserEmail + Constants.USERNAME_SUFFIX,
                Alias = 'experien',
                Phone = '800-555-1212',
                ProfileId = [SELECT Id FROM Profile WHERE Name = :Constants.EXPERIENCE_USER_PROFILE_NAME].Id,
                TimeZoneSidKey = 'America/New_York',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'ISO-8859-1',
                LanguageLocaleKey = 'en_US',
                ContactId = [SELECT PersonContactId FROM Account WHERE Id = :account.Id LIMIT 1].PersonContactId
            );
            insert experienceUser;
        }

        return experienceUser;
    }

    public static User createExperienceGuestUser() {
        return new User(Id = UserInfo.getUserId());
    }

    public static User createExperienceUserFromContactId(Id contactId) {
        String experienceUserEmail = 'experience@' + UserInfo.getOrganizationId() + 'contactId.test.com';
        User experienceUser = new User(
            FirstName = 'Experience',
            LastName = 'User2',
            Email = experienceUserEmail,
            Username = experienceUserEmail,
            Alias = 'expe2',
            Phone = '800-555-1212',
            ProfileId = [SELECT Id FROM Profile WHERE Name = :Constants.EXPERIENCE_USER_PROFILE_NAME].Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            ContactId = contactId
        );
        insert experienceUser;
        return experienceUser;
    }

    public static Account createHQCenter() {
        return new Account(
            Name = 'Proesis HQ',
            RecordTypeId = Constants.CENTER_RECORD_TYPE_ID,
            BillingPostalCode = '33023',
            BillingCountry = 'US',
            CenterId__c = 'center-111',
            Services__c = 'Donation;Medical: New Donor;Medical: Annual Physical;Medical: Consultation',
            Site = 'P-00',
            IsActive__c = false
        );
    }

    public static Account createMiramarCenter() {
        return new Account(
            Name = 'Proesis Miramar',
            RecordTypeId = Constants.CENTER_RECORD_TYPE_ID,
            BillingStreet = '7901 Riviera Blvd',
            BillingCity = 'Miramar',
            BillingState = 'FL',
            BillingPostalCode = '33023',
            BillingCountry = 'US',
            Geolocation__Latitude__s = 25.973030,
            Geolocation__Longitude__s = -80.242049,
            CenterId__c = 'center-222',
            Services__c = 'Donation;Medical: New Donor;Medical: Annual Physical;Medical: Consultation',
            Site = 'P-01',
            IsActive__c = true
        );
    }

    public static Account createDallasCenter() {
        return new Account(
            Name = 'Proesis Dallas',
            RecordTypeId = Constants.CENTER_RECORD_TYPE_ID,
            BillingStreet = '1080 N Westmoreland Rd',
            BillingCity = 'Dallas',
            BillingState = 'TX',
            BillingPostalCode = '75311',
            BillingCountry = 'US',
            Geolocation__Latitude__s = 32.78411048612642,
            Geolocation__Longitude__s = -96.87149106359581,
            CenterId__c = 'center-333',
            Services__c = 'Donation;Medical: New Donor;Medical: Annual Physical;Medical: Consultation',
            Site = 'P-02',
            IsActive__c = true
        );
    }

    public static List<Business_Hours__c> createBusinessHours(Id centerId) {
        return new List<Business_Hours__c>{
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 1, // Sunday
                isclosed__c = true
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 2, // Monday
                Open__c = Time.newInstance(6, 0, 0, 0), // 6AM
                Close__c = Time.newInstance(21, 0, 0, 0) // 9PM
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 3, // Tuesday
                Open__c = Time.newInstance(6, 0, 0, 0), // 6AM
                Close__c = Time.newInstance(21, 0, 0, 0) // 9PM
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 4, // Wednesday
                Open__c = Time.newInstance(6, 0, 0, 0), // 6AM
                Close__c = Time.newInstance(21, 0, 0, 0) // 9PM
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 5, // Thursday
                Open__c = Time.newInstance(6, 0, 0, 0), // 6AM
                Close__c = Time.newInstance(21, 0, 0, 0) // 9PM
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 6, // Friday
                Open__c = Time.newInstance(6, 0, 0, 0), // 6AM
                Close__c = Time.newInstance(21, 0, 0, 0) // 9PM
            ),
            new Business_Hours__c(
                Center__c = centerId,
                Index__c = 7, // Saturday
                Open__c = Time.newInstance(8, 0, 0, 0), // 8AM
                Close__c = Time.newInstance(18, 0, 0, 0) // 6PM
            )
        };
    }

    public static Account createTestDonor(String donorId) {
        return new Account(
            RecordTypeId = Constants.DONOR_RECORD_TYPE_ID,
            FirstName = 'Test',
            LastName = 'Donor',
            DonorId__c = donorId
        );
    }

    public static Schedule__c createTestSchedule(Id centerId, Datetime testDateTime) {
        return new Schedule__c(
            Center__c = centerId,
            Begin_Date__c = Date.valueOf(testDateTime).addDays(-1),
            End_Date__c = Date.valueOf(testDateTime).addDays(1)
        );
    }

    public static Appointment__c createTestAppointment(Id scheduleId, Datetime testDateTime) {
        Integer testDateTimeHour = testDateTime.hourGmt();
        Time appointmentTime = Time.newInstance(testDateTimeHour, 0, 0, 0);
        Date appointmentDate = testDateTime.dateGmt();
        Datetime appointmentDateTime = Datetime.newInstanceGmt(appointmentDate, appointmentTime);
        return new Appointment__c(
            Schedule__c = scheduleId,
            Duration__c = 15,
            Capacity__c = 4,
            Datetime__c = appointmentDateTime
        );
    }

    public static Center_Donation_Type__c createCenterDonationType(Id centerId) {
        Donation_Type__c donationType = new Donation_Type__c(Name = 'Normal Source Plasma');
        insert donationType;
        return new Center_Donation_Type__c(
            isActive__c = true,
            Center__c = centerId,
            Donation_Type__c = donationType.Id
        );
    }

    public static Visit__c createVisit(Id donorId, Id centerDonationTypeId, Id appointmentId) {
        return new Visit__c(
            Donor__c = donorId,
            Center_Donation_Type__c = centerDonationTypeId,
            Appointment__c = appointmentId,
            Status__c = 'New'
        );
    }

    public static AccountContactRelation createDonorCenterRelation(Id donorId, Id centerId) {
        return new AccountContactRelation(
            AccountId = centerId,
            ContactId = donorId,
            Roles = 'Donor',
            IsActive = true
        );
    }

    public static VisitTestSetup createFullTestVisitSetup(String donorExternalId, Datetime testDateTime, Boolean createExperienceUser) {
        Id donorId;
        Id donorContactId;
        if (createExperienceUser) {
            User donorUser = createExperienceUser();
            donorContactId = donorUser.ContactId;
            donorId = donorUser.AccountId;
        } else {
            Account donor = createTestDonor(donorExternalId);
            insert donor;
            donorContactId = [SELECT PersonContactId FROM Account WHERE Id = :donor.Id][0].PersonContactId;
        }

        Account center = createMiramarCenter();
        insert center;
        AccountContactRelation donorCenterRelation = createDonorCenterRelation(donorContactId, center.Id);
        insert donorCenterRelation;
        Schedule__c schedule = createTestSchedule(center.Id, testDateTime);
        insert schedule;
        Appointment__c appointment = createTestAppointment(schedule.Id, testDateTime);
        insert appointment;
        Center_Donation_Type__c centerDonationType = createCenterDonationType(center.Id);
        insert centerDonationType;
        Visit__c visit = createVisit(donorContactId, centerDonationType.Id, appointment.Id);
        insert visit;

        VisitTestSetup testSetup = new VisitTestSetup();
        testSetup.DonorId = donorId;
        testSetup.DonorContactId = donorContactId;
        testSetup.CenterId = center.Id;
        testSetup.DonorCenterRelationId = donorCenterRelation.Id;
        testSetup.ScheduleId = schedule.Id;
        testSetup.AppointmentId = appointment.Id;
        testSetup.CenterDonationTypeId = centerDonationType.Id;
        testSetup.VisitId = visit.Id;

        return testSetup;
    }

    public static ContentVersion createContentVersion() {
        return new ContentVersion(
            Title = 'Test',
            PathOnClient = 'test.txt',
            VersionData = Blob.valueOf('data')
        );
    }

    public class VisitTestSetup {
        public Id DonorId;
        public Id DonorContactId;
        public Id CenterId;
        public Id DonorCenterRelationId;
        public Id ScheduleId;
        public Id AppointmentId;
        public Id CenterDonationTypeId;
        public Id VisitId;
    }

    public class TestException extends Exception {
    }

}