force-app/main/default/objects/Account/fields/CenterId__c.field-meta.xml
<CustomField>
    <fullName>CenterId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The unique external identifier for Centers</description>
    <externalId>true</externalId>
    <label>CenterId</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration in minutes, set by the Schedule Template used to generate the Schedule</description>
    <label>Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/Business_Hours__c.object-meta.xml
<CustomObject>
    <description>Hours of business available for scheduling Donors</description>
    <label>Business Hours</label>
    <nameField>
        <label>Business Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Hours__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Hours</relationshipLabel>
    <relationshipName>Business_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <description>Closing time</description>
    <label>Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>1-based index of Days of Week</description>
    <label>Index</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <description>Open time</description>
    <label>Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Default_Business_Hours__mdt/Default_Business_Hours__mdt.object-meta.xml
<CustomObject>
    <label>Default Business Hours</label>
    <pluralLabel>Default Business Hours</pluralLabel>
</CustomObject>

force-app/main/default/objects/Default_Business_Hours__mdt/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <description>See Open__c for format</description>
    <inlineHelpText>See Open field for instruction</inlineHelpText>
    <label>Close</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Default_Business_Hours__mdt/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>Index of Days of Week</description>
    <label>Index</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Default_Business_Hours__mdt/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Center is closed that day ignoring Open and Close fields.</description>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Default_Business_Hours__mdt/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <description>Date format &quot;h:mm a&quot; (see: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) e.g. &quot;8:30 am&quot;</description>
    <inlineHelpText>Enter in format &quot;h:mm a&quot; e.g. &quot;6:30 am&quot;</inlineHelpText>
    <label>Open</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>The beginning date for the Schedule inclusive.</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day for this Schedule inclusive.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of donation for this Visit</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CenterSchedulerControllerTests.cls
@IsTest
public with sharing class CenterSchedulerControllerTests {

    @TestSetup
    static void makeData(){
        Id centerRecordTypeID =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Center').getRecordTypeId();
        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Donor').getRecordTypeId();

        system.debug('centerRecordTypeID' + centerRecordTypeID);
        system.debug('personAccountRecordTypeId' + personAccountRecordTypeId);


        // Create Donors
        Account[] donors = new Account[]{
            new Account(
                FirstName = 'Danny',
                LastName = 'Donor',
                RecordTypeID = personAccountRecordTypeId,
                DonorId__c = 'donor-12345'
            ),
            new Account(
                FirstName = 'Betty',
                LastName = 'Bleeder',
                RecordTypeID = personAccountRecordTypeId,
                DonorId__c = 'donor-67890'
            )
        };

        upsert donors DonorId__c;

        //Create Donation Centers
        Account[] centers = new Account[]{
            TestUtil.createMiramarCenter(),
            TestUtil.createDallasCenter(),
            new Account(
                Name = 'Center 3',
                RecordTypeID = centerRecordTypeID,
                ShippingStreet = '333 3rd St',
                CenterId__c = 'center-3'
            )
        };

        upsert centers CenterId__c;


        Schedule__c[] schedules = new Schedule__c[]{
            new Schedule__c(
                Center__c = centers[0].Id, 
                Begin_Date__c =  Date.newInstance(2022, 1, 10).addDays(-10),
                End_Date__c =  Date.newInstance(2024, 1, 10).addDays(30)
            ),
            new Schedule__c(
                Center__c = centers[1].Id,
                Begin_Date__c =  Date.newInstance(2022, 1, 10).addDays(-10),
                End_Date__c =  Date.newInstance(2024, 1, 10).addDays(30)
            ),
            new Schedule__c(
                Center__c = centers[2].Id,
                Begin_Date__c =  Date.newInstance(2024, 1, 10).addDays(-10),
                End_Date__c =  Date.newInstance(2024, 1, 10).addDays(30)
            )
        };

        List<Business_Hours__c> businessHours = new List<Business_Hours__c>();
        for (Id centerId : new List<Id>{centers[0].Id, centers[1].Id}) {
            for (Default_Business_Hours__mdt defaultTime : [SELECT Label, Close__c, Index__c, IsClosed__c, Open__c FROM Default_Business_Hours__mdt]) {
                String todayString = String.valueOf(Datetime.now().date());
                Datetime closingTime = Datetime.valueOf(String.valueOf(todayString + ' ' + defaultTime.Close__c) + ':00');
                Datetime openTime = Datetime.valueOf(String.valueOf(todayString + ' ' + defaultTime.Open__c + ':00'));
        
                Business_Hours__c newBH = new Business_Hours__c();
                newBH.Name = defaultTime.Label;
                newBH.Center__c = centerId;
                newBH.Close__c = Time.newInstance(closingTime.hour(), closingTime.minute(), closingTime.second(), closingTime.millisecond());
                newBH.Index__c = defaultTime.Index__c;
                newBH.isClosed__c = defaultTime.IsClosed__c;
                newBH.Open__c = Time.newInstance(openTime.hour(), openTime.minute(), openTime.second(), openTime.millisecond());
        
                businessHours.add(newBH);
            }
        }
        
        insert businessHours;

        // insert schedules;

        Date startDate =  Date.newInstance(2023, 1, 10).addDays(-10);
        Date endDate =  Date.newInstance(2023, 1, 10).addDays(30);
        Id loyaltyTier = null;
        Integer intervalsPerHour = 6; //10 minutes apart
        Integer slotsPerInterval = 1;

        //create the schedule record
        Schedule__c schedule = ScheduleUtils.createScheduleRecord(centers[0].Id, startDate, endDate);
        insert schedule;

        Account center1 = [SELECT Id FROM Account WHERE Name = 'Proesis Miramar'];

        Appointment__c[] appointments = ScheduleUtils.scheduleRange(centers[0].Id,schedule.Id,startDate,endDate,loyaltyTier,intervalsPerHour,slotsPerInterval);

        insert appointments;
    }

    @IsTest
    public static void testGetCenters(){

        CenterScheduleController.Center[] centers = new CenterScheduleController.Center[]{};
        Test.startTest();
        System.runAs(TestUtil.createAdminUser()){
            centers = CenterScheduleController.getCenters();
        }
        Test.stopTest();
        system.assertEquals(3, centers.size());
    }

    @IsTest
    public static void testGetAppointments(){
        User contextuser = TestUtil.createAdminUser();
        System.runAs(contextuser){
            Account center = [Select ID FROM Account WHERE Name ='Proesis Miramar' ];

            Schedule__c schedule = new Schedule__c(
                Center__c = center.Id,
                Begin_Date__c = Date.newInstance(2023, 1, 10).addDays(-10),
                End_Date__c = Date.newInstance(2023, 1, 10).addDays(30)
            );
            insert schedule;
            Appointment__c[] appointments = new Appointment__c[]{
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 10, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                ),
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 11, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                )
            };
            
            insert appointments;


            Center_Donation_Type__c cdt = new Center_Donation_Type__c(Center__c = center.id);
            insert cdt;

            Contact donor = new Contact(FirstName='Danny', LastName ='Donor');
            insert donor;

            Visit__c visit = new Visit__c(
                Appointment__c = appointments[0].id,
                Center_Donation_Type__c = cdt.Id,
                Donor__c = donor.id
            );

            insert visit;
        
        
            CenterScheduleController.AppointmentSlot[] slots = new CenterScheduleController.AppointmentSlot[]{};
            Id centerId = [SELECT Id FROM Account WHERE NAME = 'Proesis Miramar'].Id;
            Test.startTest();
            
                slots = CenterScheduleController.getAppointments(centerId,Date.newInstance(2023, 1, 10),'','');
                CenterScheduleController.AppointmentSlot slot = CenterScheduleController.getAppointmentSlot(slots[0].Id);
            Test.stopTest();
            system.assertEquals(62, slots.size());
            //figure out why this only passes in scratch:
            // system.assertEquals(1,slot.visits.size());
        }
    }

    @IsTest
    public static void testChangeVisitAppointment(){
        user adminUser = TestUtil.createAdminUser();
        System.runAs(adminUser) {
            Account center = [Select ID FROM Account WHERE Name ='Proesis Miramar' ];

            Schedule__c schedule = new Schedule__c(
                Center__c = center.Id,
                Begin_Date__c = Date.newInstance(2023, 1, 10).addDays(-10),
                End_Date__c = Date.newInstance(2023, 1, 10).addDays(30)
            );
            insert schedule;
            Appointment__c[] appointments = new Appointment__c[]{
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 10, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                ),
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 11, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                )
            };
            
            insert appointments;


            Center_Donation_Type__c cdt = new Center_Donation_Type__c(Center__c = center.id);
            insert cdt;

            Contact donor = new Contact(FirstName='Danny', LastName ='Donor');
            insert donor;

            Visit__c visit = new Visit__c(
                Appointment__c = appointments[0].id,
                Center_Donation_Type__c = cdt.Id,
                Donor__c = donor.id
            );

            insert visit;

            Test.startTest();

                CenterScheduleController.changeVisitAppointment(visit.id, appointments[1].id);
            
            Test.stopTest();

            visit = [SELECT Id, Appointment__c FROM Visit__c limit 1];

            system.assertEquals(appointments[1].id, visit.Appointment__c);
        }

    }


    @IsTest
    public static void testCancelVisit(){
        user adminUser = TestUtil.createAdminUser();
        System.runAs(adminUser) {
            Account center = [Select ID FROM Account WHERE Name ='Proesis Miramar' ];

            Schedule__c schedule = new Schedule__c(
                Center__c = center.Id,
                Begin_Date__c = Date.newInstance(2023, 1, 10).addDays(-10),
                End_Date__c = Date.newInstance(2023, 1, 10).addDays(30)
            );
            insert schedule;
            Appointment__c[] appointments = new Appointment__c[]{
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 10, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                ),
                new Appointment__c(
                        Schedule__c = schedule.Id,
                    Datetime__c = DateTime.newInstance(2023, 1, 10, 11, 0, 0),
                    Duration__c = 10,
                    Capacity__c = 5
                )
            };
            
            insert appointments;


            Center_Donation_Type__c cdt = new Center_Donation_Type__c(Center__c = center.id);
            insert cdt;

            Contact donor = new Contact(FirstName='Danny', LastName ='Donor');
            insert donor;

            Visit__c visit = new Visit__c(
                Appointment__c = appointments[0].id,
                Center_Donation_Type__c = cdt.Id,
                Status__c = 'New',
                Donor__c = donor.id
            );

            insert visit;

            Test.startTest();

                CenterScheduleController.cancelVisit(visit.id);
            
            Test.stopTest();

            visit = [SELECT Id, Status__c, Outcome__c FROM Visit__c limit 1];

            system.assertEquals('Complete', visit.Status__c);
            system.assertEquals('Canceled', visit.Outcome__c);
        }

    }
    
    @IsTest
    public static void testCreateAppointmentSlots(){
        user adminUser = TestUtil.createAdminUser();
        Appointment__c[] appointments;
        Schedule__c schedule;
        Date startDate =  Date.newInstance(2022, 1, 10);
        Date endDate = startDate.addDays(-10);
        System.runAs(adminUser) {
            Account center = [Select ID FROM Account WHERE Name ='Proesis Miramar' ];
            Test.startTest();
            CenterScheduleController.createAppointmentSlots(center.Id,startDate,endDate,1,1,null);
            Test.stopTest();
        }

    }

    @IsTest
    static void testAddVisit() {
        String targetDonorRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Donor').getRecordTypeId();

        Appointment__c targetAppointmentSlot = [SELECT Id, Schedule__r.Center__c FROM Appointment__c LIMIT 1];
        Account targetCenter = [SELECT Id FROM Account WHERE Id = :targetAppointmentSlot.Schedule__r.Center__c LIMIT 1];
        Account targetDonor = [SELECT Id, PersonContactId FROM Account WHERE RecordTypeId = :targetDonorRecordTypeId LIMIT 1];

        // Create additional test data to allow visit insert
        Donation_Type__c donationTypeTest = new Donation_Type__c(
            Name = 'Test Donation Type'
        );
        insert donationTypeTest;

        Center_Donation_Type__c centerDonationTypeTest = new Center_Donation_Type__c(
            Center__c = targetCenter.Id,
            Donation_Type__c = donationTypeTest.Id,
            isActive__c = true
        );
        insert centerDonationTypeTest;

        Test.startTest();
        CenterScheduleController.addVisit(targetDonor.Id, targetAppointmentSlot.Id, targetCenter.Id);
        Test.stopTest();

        Visit__c createdVisit = [
            SELECT Id, Status__c 
            FROM Visit__c 
            WHERE Center_Donation_Type__r.Center__c = :targetCenter.Id AND
                Donor__c = :targetDonor.PersonContactId AND
                Appointment__c = :targetAppointmentSlot.Id
        ];

        Assert.isNotNull(createdVisit, 'Couldn\'t find the desired visit record. Either it wasn\'t created or the data wasn\'t set correctly.');
        Assert.areEqual('Scheduled', createdVisit.Status__c, 'The status of the visit should default to \'Scheduled\'');
    }
}