force-app/main/default/objects/Account/fields/Center_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Center_Timezone__c</fullName>
    <label>Center Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Chicago</fullName>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Date_Center__c.field-meta.xml
<CustomField>
    <fullName>Date_Center__c</fullName>
    <description>Date of this appointment in the center&apos;s time zone.</description>
    <label>Date (Center)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Time_Center__c.field-meta.xml
<CustomField>
    <fullName>Time_Center__c</fullName>
    <description>Time of this appointment in the center&apos;s time zone.</description>
    <label>Time (Center)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AppointmentTriggerHandler.cls
public without sharing class AppointmentTriggerHandler extends TriggerFactory.BaseHandler {

    public override void beforeInsert(List<SObject> newList) {
        setCenterDateAndTime((List<Appointment__c>) newList, new Map<Id, Appointment__c>());
    }

    public override void beforeUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        setCenterDateAndTime((List<Appointment__c>) newMap.values(), (Map<Id, Appointment__c>) oldMap);
    }

    private static void setCenterDateAndTime(List<Appointment__c> appointments, Map<Id, Appointment__c> oldAppointments) {
        List<Appointment__c> appointmentsToProcess = new List<Appointment__c>();
        Set<Id> scheduleIds = new Set<Id>();

        for (Appointment__c appointment : appointments) {
            if (!oldAppointments.containsKey(appointment.Id) || appointment.Datetime__c != oldAppointments.get(appointment.Id).Datetime__c) {
                appointmentsToProcess.add(appointment);
                scheduleIds.add(appointment.Schedule__c);
            }
        }

        if (appointmentsToProcess.size() > 0) {
            Map<Id, Schedule__c> schedules = new Map<Id, Schedule__c>([
                SELECT
                    Center__r.Center_Timezone__c
                FROM
                    Schedule__c
                WHERE
                    Id IN :scheduleIds
            ]);

            for (Appointment__c appointment : appointments) {
                Schedule__c schedule = schedules.get(appointment.Schedule__c);

                appointment.Date_Center__c = Util.getTimeZoneDate(appointment.Datetime__c, schedule.Center__r.Center_Timezone__c);
                appointment.Time_Center__c = Util.getTimeZoneTime(appointment.Datetime__c, schedule.Center__r.Center_Timezone__c);
            }
        }
    }

}