force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Used_Center__c.field-meta.xml
<CustomField>
    <fullName>Last_Used_Center__c</fullName>
    <description>Formula field to display the last used center from the person account.</description>
    <formula>Contact.Last_Used_Center__r.Name</formula>
    <label>Last Used Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Used_Center__c.field-meta.xml
<CustomField>
    <fullName>Last_Used_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field holds the last Donation Center that was scheduled by the Donor; for convenience.</description>
    <label>Last Used Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recent Donors</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>D-{0}</displayFormat>
        <label>Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Center where this device is located/associated</description>
    <inlineHelpText>Center where this device is located/associated</inlineHelpText>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BECS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donor_CheckIn__e/Donor_CheckIn__e.object-meta.xml
<CustomObject>
    <description>Donor is qualified to begin donation</description>
    <label>Donor CheckIn</label>
    <pluralLabel>Donor CheckIns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_CheckIn__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The datetime of this event</description>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems.</description>
    <externalId>true</externalId>
    <inlineHelpText>The external PK for donors in the BECS/NexLynk systems.</inlineHelpText>
    <label>Donor Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Used_Center__c.field-meta.xml
<CustomField>
    <fullName>Last_Used_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Used Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Datetime__c</fullName>
    <description>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</description>
    <inlineHelpText>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</inlineHelpText>
    <label>Appointment Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of donation for this Visit</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Previous_Donation__c.field-meta.xml
<CustomField>
    <fullName>Previous_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The previous Visit that was donation Complete</description>
    <inlineHelpText>The previous Visit that was a successful Donation</inlineHelpText>
    <label>Previous Donation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Visit__c.Status__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </filterItems>
        <filterItems>
            <field>Visit__c.Donation_Volume__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visits (Previous Donation)</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonorEventHelper.cls
public without sharing class DonorEventHelper {
    public static List<List<SObject>> validateDonorAndVisitReferences(List<List<SObject>> inputRecords) {
        Map<String, SObject> runningDonorNumberList = getDonorNumberToDonorEvent(inputRecords);
        Map<String, Object> getRelatedObjectMappingsResult = mapDonorNumberToDonorRelatedRecords(runningDonorNumberList);
        Map<String, SObject> validDonorNumbersToDonorEvent = (Map<String, SObject>)getRelatedObjectMappingsResult.get('validDonorNumbersToDonorEvent');
        Map<String, Contact> validDonorNumbersToDonor = (Map<String, Contact>)getRelatedObjectMappingsResult.get('validDonorNumbersToDonor');

        // Create Tasks for missing donors
        Group customerSupportQueue, proesisOperationsQueue;
        for(Group foundBaseQueue : [SELECT Id, DeveloperName FROM Group WHERE Type = 'Queue' AND DeveloperName IN ('Customer_Support', 'Proesis_Operations')]) {
            if (foundBaseQueue.DeveloperName == 'Customer_Support') {
                customerSupportQueue = foundBaseQueue;
            } else if (foundBaseQueue.DeveloperName == 'Proesis_Operations') {
                proesisOperationsQueue = foundBaseQueue;
            }
        }

        // Any Donors Left in the runningDonorNumberList are missing from the system
        // Valid numbers where removed when querying for the related records
        // Create a Task record for each donorNumber with a missing contact
        List<Task> tasksToInsert = new List<Task>();

        if (runningDonorNumberList.size() > 0) {
            for (String donorNumber : runningDonorNumberList.keySet()) {
                Task task = new Task();
                task.Subject = 'Missing Donor from BECS';
                task.Description = 'No matching donor for DonorId of ' + donorNumber;
                task.ActivityDate = Date.today();
                task.OwnerId = proesisOperationsQueue != null ? proesisOperationsQueue.Id : customerSupportQueue.Id;
                tasksToInsert.add(task);
            }
        }

        // Searching for valid visits on the varlid donors given the BECS Timestamp (Donor_Comp__e.Timestamp__c)
        Map<Datetime, List<Id>> targetAppointmentTimeToRescheduleVisitId = new Map<Datetime, List<Id>>();
        Map<Datetime, List<SObject>> targetAppointmentTimeToDonorEvent = new Map<Datetime, List<SObject>>();
        Set<String> becsDeviceNumbers = new Set<String>();
        Set<Id> lastUsedCenterIds = new Set<Id>();
        Set<Id> allRescheduleVisitIds = new Set<Id>();
        
        for (Contact validDonor : [
            SELECT Id, Account.DonorId__c, Last_Used_Center__c, (
                SELECT Id, Appointment_Datetime__c
                FROM Visits__r 
                WHERE Status__c IN ('New', 'Scheduled', 'Checked-In') 
                ORDER BY Appointment_Datetime__c ASC
            ) FROM Contact 
            WHERE Id IN :validDonorNumbersToDonor.values()
        ]) {
            SObject relatedEvent = validDonorNumbersToDonorEvent.get(validDonor.Account.DonorId__c);
            Datetime donorCompTimestamp = (Datetime)relatedEvent.get('Timestamp__c');

            // Check to see if there is a visit on the day of or next day of the Timestamp__c
            Boolean foundVisit = false;
            for (Visit__c visit : validDonor.Visits__r) {
                // If we find a visit on the day of then we exit happy!
                if (visit.Appointment_Datetime__c.date() == donorCompTimestamp.date()) {
                    System.debug('Found Visit ' + visit.Id + ' on the same day as the DonorComp Timestamp ' + donorCompTimestamp.date() + ' for Donor ' + validDonor.Id);

                    foundVisit = true;
                    continue;
                } else if (visit.Appointment_Datetime__c.date() == donorCompTimestamp.date().addDays(1)) {
                    System.debug('Found Visit ' + visit.Id + ' on the next day as the DonorComp Timestamp ' + donorCompTimestamp.date() + ' for Donor ' + validDonor.Id);

                    // If we find it the next day of, then we reschedule the visit to the target date using CenterScheduleController.changeVisit(visitId, newAppointmentId)
                    List<Id> visitIds = targetAppointmentTimeToRescheduleVisitId.get(donorCompTimestamp);
                    if (visitIds == null) {
                        visitIds = new List<Id>();
                    }
                    
                    visitIds.add(visit.Id);
                    targetAppointmentTimeToRescheduleVisitId.put(donorCompTimestamp, visitIds);
                    
                    allRescheduleVisitIds.add(visit.Id);
                    foundVisit = true;
                }
            }

            // If we don't find a visit on the day of or next day of, we need to find the next available appointment slot using Datetime__c and create a Visit for that slot
            // The Center for the visit (Visit__c.Center_Donation_Type__c.Center__c) can be queried using the BECS_Device_Id__c to find a related BECS_Device__c child record, the center would be the parent of that record
            System.debug('foundVisit: ' + foundVisit);

            if (!foundVisit) {
                List<SObject> donorComps = targetAppointmentTimeToDonorEvent.get(donorCompTimestamp);
                if (donorComps == null) {
                    donorComps = new List<SObject>();
                }

                // If there is a BECS_Device__c on the Event record, then we use that to find the center
                // Otherwise, use the Last_Used_Center__c as a backup
                String becsNumber = (relatedEvent instanceof Donor_Comp__e) ? (String)relatedEvent.get('BECS_Device__c') : '';
                if (!String.isEmpty(becsNumber)) {
                    becsDeviceNumbers.add(becsNumber);
                } else if (validDonor.Last_Used_Center__c != null) {
                    lastUsedCenterIds.add(validDonor.Last_Used_Center__c);
                }

                donorComps.add(relatedEvent);
                targetAppointmentTimeToDonorEvent.put(donorCompTimestamp, donorComps);
            }
        }

        // Reschedule visits that need to be rescheduled
        if (targetAppointmentTimeToRescheduleVisitId.size() > 0) {
            Set<Id> rescheduleVisitCenterIds = new Set<Id>();
            for(Visit__c targetVisit : [SELECT Center_Donation_Type__r.Center__c FROM Visit__c WHERE Id IN :allRescheduleVisitIds]) {
                rescheduleVisitCenterIds.add(targetVisit.Center_Donation_Type__r.Center__c);
            }

            // Sort the appointment times in ascending order so we know what time range to search for replacement appointments
            List<Datetime> rescheduleAppointmentTimes = new List<Datetime>(targetAppointmentTimeToRescheduleVisitId.keySet());
            rescheduleAppointmentTimes.sort();

            Datetime targetSearchStartTime = rescheduleAppointmentTimes[0].addHours(-12);
            Datetime targetSearchEndTime = rescheduleAppointmentTimes[rescheduleAppointmentTimes.size() - 1].addHours(12);

            Map<Datetime, Appointment__c> eligibleAppointmentSlots = new Map<Datetime, Appointment__c>();
            for(Appointment__c rescheduleAppointmentSlot : [
                SELECT Id, Datetime__c 
                FROM Appointment__c 
                WHERE Schedule__r.Center__c IN :rescheduleVisitCenterIds AND 
                    Datetime__c >= :targetSearchStartTime AND
                    Datetime__c <= :targetSearchEndTime
                ORDER BY Datetime__c ASC
            ]) {
                System.debug('rescheduleAppointmentSlot: ' + rescheduleAppointmentSlot);
                eligibleAppointmentSlots.put(rescheduleAppointmentSlot.Datetime__c, rescheduleAppointmentSlot);
            }

            List<CoreSchedulerHandler.RescheduleRequest> rescheduleRequests = new List<CoreSchedulerHandler.RescheduleRequest>();
            for(Datetime targetVisitRescheduleDatetime : targetAppointmentTimeToRescheduleVisitId.keySet()) {
                List<Id> visitIds = targetAppointmentTimeToRescheduleVisitId.get(targetVisitRescheduleDatetime);

                for(Id visitId : visitIds) {
                    Appointment__c targetAppointment;

                    for(Datetime appointmentSlotDatetime : eligibleAppointmentSlots.keySet()) {
                        Decimal diff1 = Math.abs(appointmentSlotDatetime.getTime() - targetVisitRescheduleDatetime.getTime());
                        Decimal diff2 = targetAppointment != null ? Math.abs(targetAppointment.Datetime__c.getTime() - targetVisitRescheduleDatetime.getTime()) : null;

                        if (targetAppointment == null || diff1 < diff2) {
                            targetAppointment = eligibleAppointmentSlots.get(appointmentSlotDatetime);
                        }
                    }

                    if (targetAppointment == null) {
                        System.debug('No eligible appointment slot found for visit ' + visitId);
                        continue;
                    }

                    rescheduleRequests.add(new CoreSchedulerHandler.RescheduleRequest(visitId, targetAppointment.Id));
                }
            }

            CoreSchedulerHandler.rescheduleVisits(new CoreSchedulerHandler.RescheduleBatchRequest(rescheduleRequests));
        }
        
        if (targetAppointmentTimeToDonorEvent.size() > 0) {
            // Get the Center_Donation_Type__c records for the BECS Devices
            Map<String, Device__c> becsCenterToDevice = new Map<String, Device__c>();
            Map<Id, String> centerIdToTargetQueueName = new Map<Id, String>();

            if (becsDeviceNumbers.size() > 0) {
                for(Device__c becsDevice : [SELECT Id, Center__c, Center__r.Name, Device_Id__c FROM Device__c WHERE Device_Id__c IN :becsDeviceNumbers AND Type__c = 'BECS']) {
                    becsCenterToDevice.put(becsDevice.Center__c, becsDevice);
                    centerIdToTargetQueueName.put(becsDevice.Center__c, 'Center_Manager_-_' + becsDevice.Center__r.Name.replaceAll(' ', '_'));
                }
            }

            Map<String, Center_Donation_Type__c> becsDeviceIdToCenterDonationType = new Map<String, Center_Donation_Type__c>();
            Map<Id, Center_Donation_Type__c> centerIdToCenterDonationType = new Map<Id, Center_Donation_Type__c>();

            for(Center_Donation_Type__c centerDonationType : [
                SELECT Id, Center__c 
                FROM Center_Donation_Type__c 
                WHERE (Center__c IN :becsCenterToDevice.keySet() OR Center__c IN :lastUsedCenterIds) AND 
                    Donation_Type__r.Name = 'Normal Source Plasma'
            ]) {
                if (becsCenterToDevice.get(centerDonationType.Center__c) != null) {
                    becsDeviceIdToCenterDonationType.put(becsCenterToDevice.get(centerDonationType.Center__c).Device_Id__c, centerDonationType);
                } else {
                    centerIdToCenterDonationType.put(centerDonationType.Center__c, centerDonationType);
                }
            }

            Map<String, Id> centerQueueNameToId = new Map<String, Id>();
            for(Group centerQueue : [SELECT Id, DeveloperName FROM Group WHERE Type = 'Queue' AND DeveloperName IN :centerIdToTargetQueueName.values()]) {
                centerQueueNameToId.put(centerQueue.DeveloperName, centerQueue.Id);
            }

            // Get the target Datetimes
            List<Datetime> targetAppointmentTimes = new List<Datetime>(targetAppointmentTimeToDonorEvent.keySet());
            targetAppointmentTimes.sort();

            Datetime targetSearchStartTime = targetAppointmentTimes[0].addHours(-12);
            Datetime targetSearchEndTime = targetSearchStartTime.addHours(12);

            // Create visits for donors that need to be scheduled
            List<Visit__c> visitsToInsert = new List<Visit__c>();
            List<ErrorLog__c> errorLogsToInsert = new List<ErrorLog__c>();
            Map<Id, List<Task>> donorIdToTasksToParent = new Map<Id, List<Task>>();
            Map<SObject, Appointment__c> donorEventToTargetAppointmentTime = new Map<SObject, Appointment__c>();

            for(Appointment__c newAppointmentSlot : [
                SELECT Id, Datetime__c 
                FROM Appointment__c 
                WHERE Datetime__c >= :targetSearchStartTime AND
                    Datetime__c <= :targetSearchEndTime AND 
                    (Schedule__r.Center__c IN :becsCenterToDevice.keySet() OR Schedule__r.Center__c IN :lastUsedCenterIds)
                ORDER BY Datetime__c ASC
            ]) {
                for(List<SObject> donorEventByAppointmentTime : targetAppointmentTimeToDonorEvent.values()) {
                    for(SObject donorEvent : donorEventByAppointmentTime) {
                        Datetime donorEventTimestamp = (Datetime)donorEvent.get('Timestamp__c');

                        Appointment__c currentTargetAppointment = donorEventToTargetAppointmentTime.get(donorEvent);
                        Datetime currentTargetAppointmentTime = currentTargetAppointment != null ? currentTargetAppointment.Datetime__c : null;

                        Decimal diff1 = Math.abs(newAppointmentSlot.Datetime__c.getTime() - donorEventTimestamp.getTime());
                        Decimal diff2 = currentTargetAppointmentTime != null ? Math.abs(currentTargetAppointmentTime.getTime() - donorEventTimestamp.getTime()) : null;

                        if ( currentTargetAppointmentTime == null || diff1 < diff2) {
                            donorEventToTargetAppointmentTime.put(donorEvent, newAppointmentSlot);
                        }
                    }
                }
            }

            for(List<SObject> donorEventByAppointmentTime : targetAppointmentTimeToDonorEvent.values()) {
                for(SObject donorEvent : donorEventByAppointmentTime) {
                    Contact relatedDonor = validDonorNumbersToDonor.get((String)donorEvent.get('Donor_Number__c'));
                    if (donorEvent instanceof Donor_CheckIn__e && relatedDonor.Last_Used_Center__c == null) {
                        System.debug('Couldn\'t create visit for donor ' + relatedDonor.Id + ' because they don\'t have a Last_Used_Center__c');
                        continue;
                    }

                    Appointment__c targetAppointment = donorEventToTargetAppointmentTime.get(donorEvent);
                    if (targetAppointment == null) {
                        String message = String.format(
                            'We received a {0} event without a corresponding scheduled visit. Attempting to create a visit failed because we couldn\'t find a target appointment time. \nTimeStamp: {1} \nDonor Number: {2} \nBECS Device (Comp Only): {3}', 
                            new List<object> { 
                                (donorEvent instanceof Donor_Comp__e) ? 'Donor Comp' : 'Donor Check In',
                                donorEvent.get('Timestamp__c'),
                                donorEvent.get('Donor_Number__c'),
                                (donorEvent instanceof Donor_Comp__e) ? donorEvent.get('BECS_Device__c') : 'N/A'
                            }
                        );

                        errorLogsToInsert.add(ErrorLogService.createErrorLog(
                            '', 'Donor Event Helper - Missing Visit Appointment', 'Error', message, message
                        ));

                        // Since the main scenario in which this happens is when a donor visit is manually marked as complete... we want to make sure this case doesn't result in that visit being processed
                        // That could lead to multiple payments (one from Donor Comp, other manual) 
                        validDonorNumbersToDonorEvent.remove((String)donorEvent.get('Donor_Number__c'));
                        continue;
                    }

                    Visit__c missingVisit = new Visit__c(
                        Appointment__c = donorEventToTargetAppointmentTime.get(donorEvent).Id,
                        Donor__c = relatedDonor.Id,
                        Status__c = 'Scheduled'
                    );

                    String becsNumber = (donorEvent instanceof Donor_Comp__e) ? (String)donorEvent.get('BECS_Device__c') : '';
                    if (becsDeviceIdToCenterDonationType.containsKey(becsNumber)) {
                        missingVisit.Center_Donation_Type__c = becsDeviceIdToCenterDonationType.get(becsNumber).Id;
                    } else {
                        missingVisit.Center_Donation_Type__c = centerIdToCenterDonationType.get(relatedDonor.Last_Used_Center__c).Id;
                    }

                    visitsToInsert.add(missingVisit);

                    // Create a task to notify the center manager
                    Id targetQueueId;
                    if (donorEvent instanceof Donor_Comp__e) {
                        targetQueueId = centerQueueNameToId.get(centerIdToTargetQueueName.get(becsCenterToDevice.get(becsDeviceIdToCenterDonationType.get(becsNumber).Center__c).Center__c));
                    } else {
                        targetQueueId = centerQueueNameToId.get(centerIdToTargetQueueName.get(relatedDonor.Last_Used_Center__c));
                    }

                    if (targetQueueId == null) {
                        targetQueueId = (proesisOperationsQueue != null) ? proesisOperationsQueue.Id : customerSupportQueue.Id;
                    }

                    String donorEventType = (donorEvent instanceof Donor_Comp__e) ? 'Donor Complete' : 'Donor Check In';

                    List<Task> tasksToParent = donorIdToTasksToParent.get(relatedDonor.Id);
                    if (tasksToParent == null) {
                        tasksToParent = new List<Task>();
                    }

                    tasksToParent.add(new Task(
                        Subject = 'Missing Visit Created upon ' + donorEventType + ' Event',
                        ActivityDate = Date.today(),
                        WhoId = relatedDonor.Id,
                        OwnerId = targetQueueId
                    ));

                    donorIdToTasksToParent.put(relatedDonor.Id, tasksToParent);
                }
            }

            if (errorLogsToInsert.size() > 0) {
                insert errorLogsToInsert;
            }

            if (visitsToInsert.size() > 0) {
                CoreSchedulerHandler.createVisits(visitsToInsert);
            }

            // Parent Tasks to Visit after inserting
            for(Visit__c createdVisit : visitsToInsert) {
                List<Task> tasksToParent = donorIdToTasksToParent.get(createdVisit.Donor__c);
                if (tasksToParent != null) {
                    for(Task taskToParent : tasksToParent) {
                        taskToParent.WhatId = createdVisit.Id;
                    }
                }

                tasksToInsert.addAll(tasksToParent);
            }
        }

        if (tasksToInsert.size() > 0) {
            insert tasksToInsert;
        }

        List<List<SObject>> validDonorEvents = new List<List<SObject>>();
        for(SObject validDonorEvent : validDonorNumbersToDonorEvent.values()) {
            validDonorEvents.add(new List<SObject>{validDonorEvent});
        }

        return validDonorEvents;
    }

    private static Map<String, SObject> getDonorNumberToDonorEvent(List<List<SObject>> donorEvents) {
        Map<String, SObject> donorNumberToDonorEvent = new Map<String, SObject>();

        for (List<SObject> donorEventList : donorEvents) {
            for (SObject donorEvent : donorEventList) {
                donorNumberToDonorEvent.put((String)donorEvent.get('Donor_Number__c'), donorEvent);
            }
        }

        return donorNumberToDonorEvent;
    }

    private static Map<String, Object> mapDonorNumberToDonorRelatedRecords(Map<String, SObject> runningDonorNumberList) {
        Map<String, SObject> validDonorNumbersToDonorEvent = new Map<String, SObject>();
        Map<String, Contact> validDonorNumbersToDonor = new Map<String, Contact>();

        for(Contact donor : [SELECT Id, Account.DonorId__c, Last_Used_Center__c FROM Contact WHERE Account.DonorId__c IN :runningDonorNumberList.keySet()]) {
            validDonorNumbersToDonorEvent.put(donor.Account.DonorId__c, runningDonorNumberList.get(donor.Account.DonorId__c));
            validDonorNumbersToDonor.put(donor.Account.DonorId__c, donor);

            runningDonorNumberList.remove(donor.Account.DonorId__c);
        }

        return new Map<String, Object> {
            'validDonorNumbersToDonorEvent' => validDonorNumbersToDonorEvent,
            'validDonorNumbersToDonor' => validDonorNumbersToDonor
        };
    }
}