force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Eligible_Donation_Count__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Donation_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date. This is set automatically by code, based on Status = Complete and Outcome = Donation visits for the Campaign Member Contact.</description>
    <inlineHelpText>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date.</inlineHelpText>
    <label>Eligible Donation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Last_Related_Visit__c.field-meta.xml
<CustomField>
    <fullName>Last_Related_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The last related visit to this Campaign Member, which last incremented the counter for this membership, if applicable.</description>
    <inlineHelpText>The last related visit to this Campaign Member, which last incremented the counter for this membership, if applicable.</inlineHelpText>
    <label>Last Related Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/Donor_Comp__e.object-meta.xml
<CustomObject>
    <description>The last donation step in the donation process typically indicating payment is owed.</description>
    <label>Donor Comp</label>
    <pluralLabel>Donor Comps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_Comp__e/fields/BECS_Device__c.field-meta.xml
<CustomField>
    <fullName>BECS_Device__c</fullName>
    <description>Serial number of BECS machine</description>
    <label>BECS Device</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Number__c.field-meta.xml
<CustomField>
    <fullName>Collection_Number__c</fullName>
    <description>Unique donation collection identifier.</description>
    <label>Collection Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Volume__c.field-meta.xml
<CustomField>
    <fullName>Collection_Volume__c</fullName>
    <description>The volume in milliliters (ml or cc) of the donation collected.</description>
    <label>Collection Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Donor_Number__c.field-meta.xml
<CustomField>
    <fullName>Donor_Number__c</fullName>
    <label>Donor Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Appointment_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Datetime__c</fullName>
    <description>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</description>
    <inlineHelpText>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</inlineHelpText>
    <label>Appointment Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Collection_Device_ID__c.field-meta.xml
<CustomField>
    <fullName>Collection_Device_ID__c</fullName>
    <description>Unique BECS device identifier (serial number)</description>
    <inlineHelpText>Unique BECS device identifier (serial number)</inlineHelpText>
    <label>Collection Device ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Collection_Number__c.field-meta.xml
<CustomField>
    <fullName>Collection_Number__c</fullName>
    <description>Upon a donation complete event, the collection number received from BECs.</description>
    <inlineHelpText>Upon a donation complete event, the collection number received from BECs.</inlineHelpText>
    <label>Collection Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Donation_Complete__c</fullName>
    <description>Datetime that BECS concludes the donation; when payment can be made.</description>
    <label>Donation Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Volume__c.field-meta.xml
<CustomField>
    <fullName>Donation_Volume__c</fullName>
    <description>Donation in cc</description>
    <label>Donation Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Previous_Donation__c.field-meta.xml
<CustomField>
    <fullName>Previous_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The previous Visit that was donation Complete</description>
    <inlineHelpText>The previous Visit that was a successful Donation</inlineHelpText>
    <label>Previous Donation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Visit__c.Status__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </filterItems>
        <filterItems>
            <field>Visit__c.Donation_Volume__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visits (Previous Donation)</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonorCompInvocable.cls
/**
 * Created by joshlequire1 on 3/10/23.
 */

public without sharing class DonorCompInvocable {
    @InvocableMethod(Label='Handle Donor Comp Event' Description='Handles the Donor Comp Event by updating the Visit Status to Complete and creating a Donation Transaction' Category='Donor')
    public static void handleDonorCompEvent(List<List<Donor_Comp__e>> inputRecords) {
        // Donor Comp Events returned by this function have both a valid donor and visit reference
        List<List<Donor_Comp__e>> validDonorEvents = (List<List<Donor_Comp__e>>) DonorEventHelper.validateDonorAndVisitReferences(inputRecords);

        if (!validDonorEvents.isEmpty()) {
            updateVisitStatusComplete(validDonorEvents);
            handleCreateDonationTransactions(validDonorEvents);
        }
    }

    // NOTE (similar to Donor Checkin), this assumes we'll receive a call for each unique comp event at the Donor_Comp__e endpoint, but is bulkfied in case there is a need for processing these in larger batches. However, this method assumes only 1 check in per Donor Number - if multiple checkinis for the same donor are needed with this call, we'll need to refactor the method to handle this.
    public static void updateVisitStatusComplete(List<List<Donor_Comp__e>> inputRecords) {
        List<Donor_Comp__e> recordsToProcess = new List<Donor_Comp__e>();
        Map<String, Donor_Comp__e> donorNumberToPEs = new Map<String, Donor_Comp__e>();
        List<Datetime> dateTimesToProcess = new List<Datetime>();
        Set<String> donorNumbersToQuery = new Set<String>();
        Map<String, Contact> donorNumberToContact = new Map<String, Contact>();
        Map<String, Visit__c> donorNumberToVisit = new Map<String, Visit__c>();
        List<Visit__c> visitsToUpdate = new List<Visit__c>();

        for (List<Donor_Comp__e> recordList : inputRecords) {
            for (Donor_Comp__e donorComp : recordList) {
                recordsToProcess.add(donorComp);
                donorNumberToPEs.put(donorComp.Donor_Number__c, donorComp);
                dateTimesToProcess.add(donorComp.Timestamp__c);
                donorNumbersToQuery.add(donorComp.Donor_Number__c);
            }
        }

        // find visits in this list
        for (Visit__c visit : VisitSelector.getVisitsInRangeForDonorNumbers(dateTimesToProcess, donorNumbersToQuery)) {
            Donor_Comp__e comp = donorNumberToPEs.get(visit.Donor__r.Account.DonorId__c);
            // Assuming FDA 48 Hour rule mandates (at least) 24 hours between visits, check if this event is within 12 hours of the Visit (Appointment) Date Time
            if (comp.Timestamp__c <= visit.Appointment__r.Datetime__c.addHours(12) && comp.Timestamp__c >= visit.Appointment__r.Datetime__c.addHours(-12)) {
                Visit__c visitUpdate = new Visit__c(Id = visit.Id,
                    Donor__c = visit.Donor__c);
                updateVisitToCompleteDonationStatus(visitUpdate, comp);

                visitsToUpdate.add(visitUpdate);
                donorNumberToVisit.put(comp.Donor_Number__c, visitUpdate);
            }
        }

        // find Contacts iin this list
        for (Contact ct : [SELECT Id, AccountId, Account.DonorId__c FROM Contact WHERE Account.DonorId__c IN :donorNumbersToQuery]) {
            donorNumberToContact.put(ct.Account.DonorId__c, ct);
        }

        if (!visitsToUpdate.isEmpty()) {
            update visitsToUpdate;
            updateCampaignVisitCounter(visitsToUpdate);
        }
    }

    private static Visit__c updateVisitToCompleteDonationStatus(Visit__c visit, Donor_Comp__e comp) {
        visit.Status__c = Constants.VISIT_STATUS_COMPLETE;
        visit.Donation_Complete__c = comp.Timestamp__c;
        visit.Outcome__c = Constants.VISIT_OUTCOME_DONATION;
        visit.Collection_Number__c = comp.Collection_Number__c;
        visit.Donation_Volume__c = comp.Collection_Volume__c;
        visit.Collection_Device_ID__c = comp.BECS_Device__c;

        return visit;
    }

    public static void handleCreateDonationTransactions(List<List<Donor_Comp__e>> inputRecords) {
        Set<String> donorNumbers = new Set<String>();
        for (List<Donor_Comp__e> recordList : inputRecords) {
            for (Donor_Comp__e donorComp : recordList) {
                donorNumbers.add(donorComp.Donor_Number__c);
            }
        }

        List<DonorPaymentService.DonationPaymentRequest> paymentRequests = new List<DonorPaymentService.DonationPaymentRequest>();
        for(Contact foundContact : [
            SELECT Id, (SELECT Id FROM Visits__r WHERE Status__c = 'Complete' AND Outcome__c = 'Donation' ORDER BY Appointment_Datetime__c DESC LIMIT 1) 
            FROM Contact 
            WHERE Account.DonorId__c IN :donorNumbers
        ]) {
            if (foundContact.Visits__r.isEmpty()) {
                continue;
            }

            paymentRequests.add(new DonorPaymentService.DonationPaymentRequest(foundContact.Id, foundContact.Visits__r[0].Id));
        }

        DonorPaymentService.createDonationPayment(paymentRequests);
    }

    public static void updateCampaignVisitCounter(List<Visit__c> visitsToProcess) {
        Map<Id, List<CampaignMember>> donorToCampaignMembers = new Map<Id, List<CampaignMember>>();
        List<Date> datesInRange = new List<Date>();
        Map<Id, List<Visit__c>> donorToVisitsInRange = new Map<Id, List<Visit__c>>();
        List<CampaignMember> finalCampaignMemberUpdates = new List<CampaignMember>();

        for (Visit__c visit : visitsToProcess) {
            donorToCampaignMembers.put(visit.Donor__c, new List<CampaignMember>());
            donorToVisitsInRange.put(visit.Donor__c, new List<Visit__c>());
        }

        // The Campaign Member Trigger assumes the visit counter assumes this query (below) is looking only at active Incentive Type Campaigns. If this changes, verify the login in the Campaign Member Trigger Handler class is correct.
        for (CampaignMember cm : [
            SELECT Id,
                ContactId,
                CampaignId,
                Eligible_Donation_Count__c,
                CreatedDate
            FROM CampaignMember
            WHERE Campaign.IsActive = TRUE
            AND Campaign.Type = :Constants.CAMPAIGN_TYPE_INCENTIVE
            AND ContactId IN :donorToCampaignMembers.keySet()
        ]) {
            List<CampaignMember> donorCMs = donorToCampaignMembers.get(cm.ContactId);
            cm.Eligible_Donation_Count__c = 0; // set to zero; we want to recount these in case something changes
            donorCMs.add(cm);
            donorToCampaignMembers.put(cm.ContactId, donorCMs);
            datesInRange.add(cm.CreatedDate.date());
        }

        if (datesInRange.size() == 0) {
            return;
        }

        datesInRange.sort();
        Date minDate = datesInRange[0];
        Time minTime = Time.newInstance(0, 0, 0, 0);
        Datetime minDateTime = Datetime.newInstance(minDate, minTime);

        for (Visit__c visit : [
            SELECT Id,
                Appointment_Datetime__c,
                Donor__c
            FROM Visit__c
            WHERE Donor__c IN :donorToVisitsInRange.keySet()
            AND Status__c = :Constants.VISIT_STATUS_COMPLETE
            AND Outcome__c = :Constants.VISIT_OUTCOME_DONATION
            AND Appointment_Datetime__c >= :minDateTime
        ]) {
            List<Visit__c> donorVisits = donorToVisitsInRange.get(visit.Donor__c);
            donorVisits.add(visit);
            donorToVisitsInRange.put(visit.Donor__c, donorVisits);
        }

        for (Id donorId : donorToCampaignMembers.keySet()) {
            if (donorToCampaignMembers.get(donorId).size() >= 1) {
                for (CampaignMember cm : donorToCampaignMembers.get(donorId)) {
                    Integer campaignMemberVisitCounter = 0;
                    String latestVisitId = null;
                    Datetime maxDateTime = Datetime.newInstance(1900, 01, 01, 00, 00, 00);
                    Date checkDate = cm.CreatedDate.date();
                    if (donorToVisitsInRange.get(cm.ContactId).size() >= 1) {
                        for (Visit__c visit : donorToVisitsInRange.get(cm.ContactId)) {
                            if (Date.valueOf(visit.Appointment_Datetime__c) >= checkDate) {
                                campaignMemberVisitCounter++;
                                if (visit.Appointment_Datetime__c > maxDateTime) {
                                    maxDateTime = visit.Appointment_Datetime__c;
                                    latestVisitId = visit.Id;
                                }
                            }
                        }
                    }
                    CampaignMember cmUpdate = new CampaignMember(
                        Id = cm.Id,
                        Eligible_Donation_Count__c = campaignMemberVisitCounter,
                        Last_Related_Visit__c = latestVisitId
                    );
                    finalCampaignMemberUpdates.add(cmUpdate);
                }
            }
        }
        if (!finalCampaignMemberUpdates.isEmpty()) {
            update finalCampaignMemberUpdates;
        }
    }
}