force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>The item description for this line in the transaction; user will most likely see this exact content</description>
    <inlineHelpText>The item description for this line in the transaction; user will most likely see this exact content</inlineHelpText>
    <label>Item</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>An amount of a specific item</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <description>The price paid for a unit of measure</description>
    <inlineHelpText>The price paid for a unit of measure</inlineHelpText>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TransactionSelectorTest.cls
@IsTest 
public class TransactionSelectorTest {
    static Integer AMOUNT_OF_TEST_TRANSACTIONS = 5;
    static String TEST_DONOR_ID = '123456';
    static Decimal TEST_AMOUNT_CURRENCY = 10;
    static Decimal TEST_AMOUNT_POINTS = 100;

    @TestSetup
    static void createTestData() {
        System.runAs(TestUtil.createAdminUser()) {
            Account centerAccount = TestUtil.createMiramarCenter();
            insert centerAccount;

            Center_Donation_Type__c testCenterDonationType = TestUtil.createCenterDonationType(centerAccount.Id);
            insert testCenterDonationType;

            Account donorAccount = TestUtil.createDonor(TEST_DONOR_ID);
            insert donorAccount;

            Id donorContactId = [SELECT PersonContactId FROM Account WHERE Id = :donorAccount.Id LIMIT 1].PersonContactId;

            Schedule__c testSchedule = TestUtil.createTestSchedule(centerAccount.Id, Datetime.now());
            insert testSchedule;

            List<Appointment__c> testAppointments = new List<Appointment__c>();
            for (Integer i = 0; i < AMOUNT_OF_TEST_TRANSACTIONS; i++) {
                testAppointments.add(TestUtil.createTestAppointment(testSchedule.Id, Datetime.now()));
            }
            insert testAppointments;

            List<Visit__c> testVisits = new List<Visit__c>();
            for (Appointment__c appointmentRecord : testAppointments) {
                testVisits.add(new Visit__c(
                    Appointment__c = appointmentRecord.Id,
                    Center_Donation_Type__c = testCenterDonationType.Id,
                    Donor__c = donorContactId,
                    Status__c = 'Complete',
                    Outcome__c = 'Donation'
                ));
            }
            insert testVisits;

            List<Transaction__c> testTransactions = new List<Transaction__c>();
            for (Integer i = 0; i < AMOUNT_OF_TEST_TRANSACTIONS; i++) {
                testTransactions.add(new Transaction__c(
                    Donor__c = donorContactId,
                    Visit__c = testVisits[i].Id,
                    Type__c = 'Credit',
                    Status__c = 'Complete'
                ));

                testTransactions.add(new Transaction__c(
                    Donor__c = donorContactId,
                    Visit__c = testVisits[i].Id,
                    Type__c = 'Debit',
                    Status__c = 'Complete'
                ));
            }
            insert testTransactions;

            List<Txn_Line_Item__c> testLineItems = new List<Txn_Line_Item__c>();
            for(Transaction__c transactionRecord : testTransactions) {
                if (transactionRecord.Type__c == 'Credit') {
                    testLineItems.add(new Txn_Line_Item__c(
                        Item__c	= 'Donation Points',
                        Quantity__c = 1,
                        Type__c = 'Points',
                        Unit_Cost__c = TEST_AMOUNT_POINTS,
                        Transaction__c = transactionRecord.Id
                    ));
                }

                testLineItems.add(new Txn_Line_Item__c(
                    Item__c	= 'Donation Payment',
                    Quantity__c = 1,
                    Type__c = 'Currency',
                    Unit_Cost__c = TEST_AMOUNT_CURRENCY,
                    Transaction__c = transactionRecord.Id
                ));
            }
            insert testLineItems;
        }
    }

    @IsTest
    static void testGetUserTransactions() {
        List<TransactionSelector.DonorTransaction> testTransactions;

        Test.startTest();
        System.runAs(TestUtil.createExperienceUserFromContactId([SELECT PersonContactId FROM Account WHERE RecordType.DeveloperName = 'Donor' LIMIT 1]?.PersonContactId)) { 
            testTransactions = TransactionSelector.getUserTransactions();
        }
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_TEST_TRANSACTIONS, testTransactions.size(), 'The amount of transactions returned does not match the amount of transactions created.');
        for(TransactionSelector.DonorTransaction transactionRecord : testTransactions) {
            Assert.areEqual(TEST_AMOUNT_CURRENCY, transactionRecord.currencyTotal, 'The currency total of the transaction does not match the expected value (10).');
            Assert.areEqual(TEST_AMOUNT_POINTS, transactionRecord.pointTotal, 'The points total of the transaction does not match the expected value (100).');
            Assert.areEqual(2, transactionRecord.transactionLineItems.size(), 'The amount of line items in the transaction does not match the expected value (2).');
        }
    }

    @IsTest 
    static void testGetUserTransactionsWithPointRedemption() {
        Contact testDonorContact = [SELECT Id FROM Contact WHERE Account.DonorId__c = :TEST_DONOR_ID LIMIT 1];
        Decimal redeemedPoints = 1000;
        Decimal redeemedCurrency = 10;

        List<Transaction__c> pointRedemptionTransactions = new List<Transaction__c> {
            new Transaction__c(
                Donor__c = testDonorContact.Id,
                Type__c = 'Debit',
                SubType__c = 'Point Redemption',
                Status__c = 'Complete'
            ),
            new Transaction__c(
                Donor__c = testDonorContact.Id,
                Type__c = 'Credit',
                SubType__c = 'Point Redemption',
                Status__c = 'Complete'
            )
        };
        insert pointRedemptionTransactions;

        List<Txn_Line_Item__c> pointRedemptionLineItems = new List<Txn_Line_Item__c> {
            new Txn_Line_Item__c(
                Item__c = 'Redeemed Points',
                Quantity__c = 1,
                Type__c = 'Points',
                Unit_Cost__c = redeemedPoints,
                Transaction__c = pointRedemptionTransactions[0].Id
            ),
            new Txn_Line_Item__c(
                Item__c = 'Redeemed Currency',
                Quantity__c = 1,
                Type__c = 'Currency',
                Unit_Cost__c = redeemedCurrency,
                Transaction__c = pointRedemptionTransactions[0].Id
            ),
            new Txn_Line_Item__c(
                Item__c = 'Redeemed Points',
                Quantity__c = 1,
                Type__c = 'Points',
                Unit_Cost__c = redeemedPoints,
                Transaction__c = pointRedemptionTransactions[1].Id
            ),
            new Txn_Line_Item__c(
                Item__c = 'Redeemed Currency',
                Quantity__c = 1,
                Type__c = 'Currency',
                Unit_Cost__c = redeemedCurrency,
                Transaction__c = pointRedemptionTransactions[1].Id
            )
        };
        insert pointRedemptionLineItems;

        List<TransactionSelector.DonorTransaction> testTransactions;
        Set<Id> testPointRedemptionIds = new Set<Id> {
            pointRedemptionTransactions[0].Id,
            pointRedemptionTransactions[1].Id
        };
        Boolean wasPointRedemptionTransactionFound = false;

        Test.startTest();
        System.runAs(TestUtil.createExperienceUserFromContactId([SELECT PersonContactId FROM Account WHERE RecordType.DeveloperName = 'Donor' LIMIT 1]?.PersonContactId)) { 
            testTransactions = TransactionSelector.getUserTransactions();
        }
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_TEST_TRANSACTIONS + 1, testTransactions.size(), 'The amount of transactions returned does not match the amount of transactions created.');
        for(TransactionSelector.DonorTransaction transactionRecord : testTransactions) {
            if (testPointRedemptionIds.contains(transactionRecord.transactionId)) {
                Assert.areEqual(redeemedCurrency, transactionRecord.currencyTotal, 'The currency total of the transaction does not match the expected value.');
                Assert.areEqual(redeemedPoints, transactionRecord.pointTotal, 'The points total of the transaction does not match the expected value.');
                Assert.areEqual(2, transactionRecord.transactionLineItems.size(), 'The amount of line items in the transaction does not match the expected value.');

                wasPointRedemptionTransactionFound = true;
                continue;
            }

            Assert.areEqual(TEST_AMOUNT_CURRENCY, transactionRecord.currencyTotal, 'The currency total of the transaction does not match the expected value.');
            Assert.areEqual(TEST_AMOUNT_POINTS, transactionRecord.pointTotal, 'The points total of the transaction does not match the expected value.');
            Assert.areEqual(2, transactionRecord.transactionLineItems.size(), 'The amount of line items in the transaction does not match the expected value.');
        }

        Assert.isTrue(wasPointRedemptionTransactionFound, 'The point redemption transaction was not found in the list of transactions.');
    }
}