force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donor_Comp__e/Donor_Comp__e.object-meta.xml
<CustomObject>
    <description>The last donation step in the donation process typically indicating payment is owed.</description>
    <label>Donor Comp</label>
    <pluralLabel>Donor Comps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Number__c.field-meta.xml
<CustomField>
    <fullName>Collection_Number__c</fullName>
    <description>Unique donation collection identifier.</description>
    <label>Collection Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Volume__c.field-meta.xml
<CustomField>
    <fullName>Collection_Volume__c</fullName>
    <description>The volume in milliliters (ml or cc) of the donation collected.</description>
    <label>Collection Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Donor_Number__c.field-meta.xml
<CustomField>
    <fullName>Donor_Number__c</fullName>
    <label>Donor Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/hasException__c.field-meta.xml
<CustomField>
    <fullName>hasException__c</fullName>
    <description>Indicates with 1 or 0 (from Haemonetics NL integration) true or false, respectively.</description>
    <label>Has Exception</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>ErrorLog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Action or Code Area that led to the error</description>
    <inlineHelpText>Action or Code Area that led to the error</inlineHelpText>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ShortMessage__c.field-meta.xml
<CustomField>
    <fullName>ShortMessage__c</fullName>
    <description>Short Title of the Error</description>
    <inlineHelpText>Short Title of the Error</inlineHelpText>
    <label>Short Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Message</description>
    <inlineHelpText>Type of Error Message</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Collection_Number__c.field-meta.xml
<CustomField>
    <fullName>Collection_Number__c</fullName>
    <description>Upon a donation complete event, the collection number received from BECs.</description>
    <inlineHelpText>Upon a donation complete event, the collection number received from BECs.</inlineHelpText>
    <label>Collection Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Complete__c.field-meta.xml
<CustomField>
    <fullName>Donation_Complete__c</fullName>
    <description>Datetime that BECS concludes the donation; when payment can be made.</description>
    <label>Donation Complete</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Volume__c.field-meta.xml
<CustomField>
    <fullName>Donation_Volume__c</fullName>
    <description>Donation in cc</description>
    <label>Donation Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonorCompInvocableTest.cls
/**
 * Created by joshlequire1 on 3/7/23.
 */

@IsTest
public with sharing class DonorCompInvocableTest {

    @IsTest
    static void testBehavior() {
        Account centerAccount = TestUtil.createMiramarCenter();
        insert centerAccount;

        Datetime testDateTime = Datetime.now();
        Schedule__c testSchedule = TestUtil.createTestSchedule(centerAccount.Id, testDateTime);
        insert testSchedule;

        Appointment__c testAppointment = TestUtil.createTestAppointment(testSchedule.Id, testDateTime);
        insert testAppointment;

        Center_Donation_Type__c testCenterDonationType = TestUtil.createCenterDonationType(centerAccount.Id);
        insert testCenterDonationType;

        Account donorAccount1 = TestUtil.createTestDonor('123456');
        insert donorAccount1;

        Account donorAccount2 = TestUtil.createTestDonor('654321');
        insert donorAccount2;

        Id donor1ContactId = [SELECT PersonContactId FROM Account WHERE Id = :donorAccount1.Id][0].PersonContactId;

        Visit__c testVisit = TestUtil.createVisit(donor1ContactId, testCenterDonationType.Id, testAppointment.Id);
        insert testVisit;

        List<Donor_Comp__e> donorCompEvents = new List<Donor_Comp__e>{
                new Donor_Comp__e(Donor_Number__c = donorAccount1.DonorId__c, Timestamp__c = testDateTime.addHours(1), Collection_Volume__c = 555, Collection_Number__c ='collection number', hasException__c = 0),
                new Donor_Comp__e(Donor_Number__c = donorAccount2.DonorId__c, Timestamp__c = testDateTime.addDays(-2), hasException__c = 0),
                new Donor_Comp__e(Donor_Number__c = 'random', Timestamp__c = testDateTime, hasException__c = 0)
        };

        // Remove this and use the Eventbus.publish() call when the flow is deployed and active. This is here only for the PROD check only test to pass.
        List<List<Donor_Comp__e>> invocableInputList = new List<List<Donor_Comp__e>>();
        invocableInputList.add(donorCompEvents);


        Test.startTest();
        /* IF the 'Donor Checkin Handler' Flow is active, this EventBus call will work and should be used. This is on purpose - we want this test to fail if that flow is changed or deactivated, as this is a business critical process that needs to run.
        EventBus.publish(donorCheckInEvents); */
        // For PROD check only deploys to work until the flow is pushed and active.
        DonorCompInvocable.updateVisitStatusComplete(invocableInputList);
        Test.stopTest();

        List<Visit__c> compVisits = [SELECT Id, Status__c, Donation_Complete__c, Outcome__c, Collection_Number__c, Donation_Volume__c FROM Visit__c WHERE Id = :testVisit.Id];
        Integer noMatchingDonorCount = 0;
        Integer noMatchingVisitCount = 0;
        for (ErrorLog__c er : [SELECT Id, Type__c, ShortMessage__c, Origin__c FROM ErrorLog__c WHERE Origin__c = 'DonorCompInvocable.updateVisitStatusComplete']) {
            if (er.ShortMessage__c == 'Donor Comp Event Exception: No matching donor') {
                noMatchingDonorCount++;
            } else if (er.ShortMessage__c == 'Donor Comp Event Exception: No matching visit') {
                noMatchingVisitCount++;
            }
        }

        Assert.areEqual(Constants.VISIT_STATUS_COMPLETE, compVisits[0].Status__c);
        Assert.areEqual(donorCompEvents[0].Timestamp__c, compVisits[0].Donation_Complete__c);
        Assert.areEqual(Constants.VISIT_OUTCOME_DONATION, compVisits[0].Outcome__c);
        Assert.areEqual(donorCompEvents[0].Collection_Number__c, compVisits[0].Collection_Number__c);
        Assert.areEqual(donorCompEvents[0].Collection_Volume__c, compVisits[0].Donation_Volume__c);
        Assert.areEqual(1, noMatchingVisitCount);
        Assert.areEqual(1, noMatchingDonorCount);

    }

}