force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <displayFormat>D-{0}</displayFormat>
        <label>Device Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Center where this device is located/associated</description>
    <inlineHelpText>Center where this device is located/associated</inlineHelpText>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Devices</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_Id__c.field-meta.xml
<CustomField>
    <fullName>Device_Id__c</fullName>
    <description>Unique device id for device type</description>
    <inlineHelpText>Unique device id for device type</inlineHelpText>
    <label>Device Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BECS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donor_CheckIn__e/Donor_CheckIn__e.object-meta.xml
<CustomObject>
    <description>Donor is qualified to begin donation</description>
    <label>Donor CheckIn</label>
    <pluralLabel>Donor CheckIns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_CheckIn__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The datetime of this event</description>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/Donor_Comp__e.object-meta.xml
<CustomObject>
    <description>The last donation step in the donation process typically indicating payment is owed.</description>
    <label>Donor Comp</label>
    <pluralLabel>Donor Comps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_Comp__e/fields/BECS_Device__c.field-meta.xml
<CustomField>
    <fullName>BECS_Device__c</fullName>
    <description>Serial number of BECS machine</description>
    <label>BECS Device</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Donor_Number__c.field-meta.xml
<CustomField>
    <fullName>Donor_Number__c</fullName>
    <label>Donor Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonorEventHelperTest.cls
@IsTest
public class DonorEventHelperTest {
    // 99 is the max amount of donors that can be checked in to an appointment
    final static Integer AMOUNT_OF_DONORS = 99;
    final static String TEST_BECS_DEVICE_ID = 'becs12345';

    @TestSetup
    static void createTestData() {
        Account centerAccount = TestUtil.createMiramarCenter();
        insert centerAccount;

        Device__c becsDevice = new Device__c(
            Device_Id__c = TEST_BECS_DEVICE_ID,
            Center__c = centerAccount.Id,
            Type__c = 'BECS'
        );
        insert becsDevice;

        Datetime testDateTime = Datetime.now();
        Schedule__c testSchedule = TestUtil.createTestSchedule(centerAccount.Id, testDateTime);
        insert testSchedule;

        List<Appointment__c> testAppointments = new List<Appointment__c> {
            TestUtil.createTestAppointment(testSchedule.Id, testDateTime),
            TestUtil.createTestAppointment(testSchedule.Id, testDateTime.addDays(1))
        };
        
        for(Appointment__c testAppointment : testAppointments) {
            testAppointment.Capacity__c = AMOUNT_OF_DONORS;
        }

        insert testAppointments;

        Center_Donation_Type__c testCenterDonationType = TestUtil.createCenterDonationType(centerAccount.Id);
        insert testCenterDonationType;

        List<Account> donors = new List<Account>();
        for (Integer i = 0; i < AMOUNT_OF_DONORS; i++) {
            Account donorAccount = TestUtil.createDonor(String.valueOf(i));
            donorAccount.Last_Used_Center__pc = centerAccount.Id;

            donors.add(donorAccount);
        }
        insert donors;
    }

    @IsTest
    static void testDonorCheckInNoDonor() {
        // Create Donor_CheckIn__e records for donorIds that don't have a donor
        // Make sure the tasks get created

        List<List<Donor_CheckIn__e>> donorCheckInEvents = new List<List<Donor_CheckIn__e>>();
        for (Integer i = 0; i < AMOUNT_OF_DONORS; i++) {
            Donor_CheckIn__e donorCheckInEvent = new Donor_CheckIn__e();
            donorCheckInEvent.Donor_Number__c = '00Q0' + String.valueOf(i); // Made up Donor Numbers that shouldn\'t exist
            donorCheckInEvent.Timestamp__c = Datetime.now();

            donorCheckInEvents.add(new List<Donor_CheckIn__e> { donorCheckInEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCheckInEvents);
        Test.stopTest();

        // The only time an event is marked as invalid is when the donorId is not found
        Assert.areEqual(0, validatedEvents.size(), 'There should be no valid events');
        Assert.areEqual(AMOUNT_OF_DONORS, [SELECT count() FROM Task], 'A task should have been created for each missing donor');
    }

    @IsTest 
    static void testDonorCheckInValidEvents() {
        // Create Donor_CheckIn__e records for donors(Account) that have a donorId
        // Make sure the event records are returned as validated

        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        List<Visit__c> visits = new List<Visit__c>();

        Appointment__c testAppointment = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];
        Center_Donation_Type__c testCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        for(Contact validDonor : validDonors) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = validDonor.Id;
            visit.Appointment__c = testAppointment.Id;
            visit.Center_Donation_Type__c = testCenterDonationType.Id;
            visits.add(visit);
        }
        insert visits;

        List<List<Donor_CheckIn__e>> donorCheckInEvents = new List<List<Donor_CheckIn__e>>();
        for(Contact donor : validDonors) {
            Donor_CheckIn__e donorCheckInEvent = new Donor_CheckIn__e();
            donorCheckInEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCheckInEvent.Timestamp__c = testAppointment.Datetime__c;

            donorCheckInEvents.add(new List<Donor_CheckIn__e> { donorCheckInEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCheckInEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');
    }

    @IsTest
    static void testDonorCheckInRescheduleVisitEvents() {
        // Create Donor_CheckIn__e records for donors(Account) that have a donorId
        // Make sure the event records are returned as validated

        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        List<Visit__c> visits = new List<Visit__c>();

        List<Appointment__c> testAppointments = [SELECT Id, Datetime__c FROM Appointment__c ORDER BY Datetime__c ASC LIMIT 2];
        Center_Donation_Type__c testCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        for(Contact validDonor : validDonors) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = validDonor.Id;
            visit.Appointment__c = testAppointments[1].Id;
            visit.Center_Donation_Type__c = testCenterDonationType.Id;
            visits.add(visit);
        }
        insert visits;

        List<List<Donor_CheckIn__e>> donorCheckInEvents = new List<List<Donor_CheckIn__e>>();
        for(Contact donor : validDonors) {
            Donor_CheckIn__e donorCheckInEvent = new Donor_CheckIn__e();
            donorCheckInEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCheckInEvent.Timestamp__c = testAppointments[0].Datetime__c;

            donorCheckInEvents.add(new List<Donor_CheckIn__e> { donorCheckInEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCheckInEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');

        for(Visit__c rescheduledVisit : [SELECT Id, Appointment__c, Status__c, Outcome__c FROM Visit__c WHERE Appointment__c IN :testAppointments]) {
            if (rescheduledVisit.Appointment__c == testAppointments[0].Id) {
                Assert.areEqual('Scheduled', rescheduledVisit.Status__c, 'The new visit should have been status=scheduled');
                Assert.areEqual(null, rescheduledVisit.Outcome__c, 'The new visit should have been outcome=null');
            } else {
                Assert.areEqual('Complete', rescheduledVisit.Status__c, 'The original visit should have been status=completed');
                Assert.areEqual('Rescheduled', rescheduledVisit.Outcome__c, 'The original visit should have been outcome=rescheduled');
            }
        }
    }

    @IsTest
    static void testDonorCheckInMissingVisitEvents() {
        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        Appointment__c targetAppointment = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];

        List<List<Donor_CheckIn__e>> donorCheckInEvents = new List<List<Donor_CheckIn__e>>();
        for(Contact donor : validDonors) {
            Donor_CheckIn__e donorCheckInEvent = new Donor_CheckIn__e();
            donorCheckInEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCheckInEvent.Timestamp__c = targetAppointment.Datetime__c;

            donorCheckInEvents.add(new List<Donor_CheckIn__e> { donorCheckInEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCheckInEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');

        List<Visit__c> missingVisits = [SELECT Id FROM Visit__c WHERE Appointment__c = :targetAppointment.Id];
        Assert.areEqual(AMOUNT_OF_DONORS, missingVisits.size(), 'There should be ' + AMOUNT_OF_DONORS + ' missing visits');
        Assert.areEqual(AMOUNT_OF_DONORS, [SELECT count() FROM Task WHERE WhatId IN :missingVisits AND Subject LIKE 'Missing Visit%'], 'There should be ' + AMOUNT_OF_DONORS + ' missing visit tasks');
    }

    @IsTest
    static void testDonorCompNoDonor() {
        List<List<Donor_Comp__e>> donorCompEvents = new List<List<Donor_Comp__e>>();
        for (Integer i = 0; i < AMOUNT_OF_DONORS; i++) {
            Donor_Comp__e donorCompEvent = new Donor_Comp__e();
            donorCompEvent.Donor_Number__c = '00Q0' + String.valueOf(i); // Made up Donor Numbers that shouldn\'t exist
            donorCompEvent.Timestamp__c = Datetime.now();
            donorCompEvent.BECS_Device__c = TEST_BECS_DEVICE_ID;

            donorCompEvents.add(new List<Donor_Comp__e> { donorCompEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCompEvents);
        Test.stopTest();

        // The only time an event is marked as invalid is when the donorId is not found
        Assert.areEqual(0, validatedEvents.size(), 'There should be no valid events');
        Assert.areEqual(AMOUNT_OF_DONORS, [SELECT count() FROM Task], 'A task should have been created for each missing donor');
    }

    @IsTest 
    static void testDonorCompValidEvents() {
        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        List<Visit__c> visits = new List<Visit__c>();

        Appointment__c testAppointment = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];
        Center_Donation_Type__c testCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        for(Contact validDonor : validDonors) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = validDonor.Id;
            visit.Appointment__c = testAppointment.Id;
            visit.Center_Donation_Type__c = testCenterDonationType.Id;
            visits.add(visit);
        }
        insert visits;

        List<List<Donor_Comp__e>> donorCompEvents = new List<List<Donor_Comp__e>>();
        for(Contact donor : validDonors) {
            Donor_Comp__e donorCompEvent = new Donor_Comp__e();
            donorCompEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCompEvent.Timestamp__c = testAppointment.Datetime__c;
            donorCompEvent.BECS_Device__c = TEST_BECS_DEVICE_ID;

            donorCompEvents.add(new List<Donor_Comp__e> { donorCompEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCompEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');
    }

    @IsTest
    static void testDonorCompRescheduleVisitEvents() {
        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        List<Visit__c> visits = new List<Visit__c>();

        List<Appointment__c> testAppointments = [SELECT Id, Datetime__c FROM Appointment__c ORDER BY Datetime__c ASC LIMIT 2];
        Center_Donation_Type__c testCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        for(Contact validDonor : validDonors) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = validDonor.Id;
            visit.Appointment__c = testAppointments[1].Id;
            visit.Center_Donation_Type__c = testCenterDonationType.Id;
            visits.add(visit);
        }
        insert visits;

        List<List<Donor_Comp__e>> donorCompEvents = new List<List<Donor_Comp__e>>();
        for(Contact donor : validDonors) {
            Donor_Comp__e donorCompEvent = new Donor_Comp__e();
            donorCompEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCompEvent.Timestamp__c = testAppointments[0].Datetime__c;
            donorCompEvent.BECS_Device__c = TEST_BECS_DEVICE_ID;

            donorCompEvents.add(new List<Donor_Comp__e> { donorCompEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCompEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');

        for(Visit__c rescheduledVisit : [SELECT Id, Appointment__c, Status__c, Outcome__c FROM Visit__c WHERE Appointment__c IN :testAppointments]) {
            if (rescheduledVisit.Appointment__c == testAppointments[0].Id) {
                Assert.areEqual('Scheduled', rescheduledVisit.Status__c, 'The new visit should have been status=scheduled');
                Assert.areEqual(null, rescheduledVisit.Outcome__c, 'The new visit should have been outcome=null');
            } else {
                Assert.areEqual('Complete', rescheduledVisit.Status__c, 'The original visit should have been status=completed');
                Assert.areEqual('Rescheduled', rescheduledVisit.Outcome__c, 'The original visit should have been outcome=rescheduled');
            }
        }
    }

    @IsTest
    static void testDonorCompMissingVisitEvents() {
        List<Contact> validDonors = [SELECT Id, Account.DonorId__c FROM Contact WHERE Account.DonorId__c != null];
        Appointment__c targetAppointment = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];

        List<List<Donor_Comp__e>> donorCompEvents = new List<List<Donor_Comp__e>>();
        for(Contact donor : validDonors) {
            Donor_Comp__e donorCompEvent = new Donor_Comp__e();
            donorCompEvent.Donor_Number__c = donor.Account.DonorId__c;
            donorCompEvent.Timestamp__c = targetAppointment.Datetime__c;
            donorCompEvent.BECS_Device__c = TEST_BECS_DEVICE_ID;

            donorCompEvents.add(new List<Donor_Comp__e> { donorCompEvent });
        }

        Test.startTest();
        List<List<SObject>> validatedEvents = DonorEventHelper.validateDonorAndVisitReferences(donorCompEvents);
        Test.stopTest();

        Assert.areEqual(AMOUNT_OF_DONORS, validatedEvents.size(), 'There should be ' + AMOUNT_OF_DONORS + ' valid events');

        List<Visit__c> missingVisits = [SELECT Id FROM Visit__c WHERE Appointment__c = :targetAppointment.Id];
        Assert.areEqual(AMOUNT_OF_DONORS, missingVisits.size(), 'There should be ' + AMOUNT_OF_DONORS + ' missing visits');
        Assert.areEqual(AMOUNT_OF_DONORS, [SELECT count() FROM Task WHERE WhatId IN :missingVisits AND Subject LIKE 'Missing Visit%'], 'There should be ' + AMOUNT_OF_DONORS + ' missing visit tasks');
    }
}