force-app/main/default/objects/Account/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/DonorId__c.field-meta.xml
<CustomField>
    <fullName>DonorId__c</fullName>
    <description>The external PK for donors in the BECS/NexLynk systems for person accounts</description>
    <externalId>true</externalId>
    <label>DonorId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>The payment vehicle associated with a Donor</description>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Account_Token__c.field-meta.xml
<CustomField>
    <fullName>Account_Token__c</fullName>
    <label>Account Token</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Card_Number__c</fullName>
    <description>Storing the last 4 digits of the card to be displayed on the mobile app</description>
    <label>Card Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <description>The donor owner of this payment method</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is_Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CancelCardControllerTest.cls
@IsTest
public without sharing class CancelCardControllerTest {
    @TestSetup
    static void createTestData() {
        Account donorAccountRecord = TestUtil.createDonor('123-456');
        insert donorAccountRecord;

        Contact donorContactRecord = [SELECT Id FROM Contact WHERE AccountId = :donorAccountRecord.Id LIMIT 1];

        Payment_Method__c testPaymentMethod = new Payment_Method__c();
        testPaymentMethod.Name = 'Test Payment Method';
        testPaymentMethod.Donor__c = donorContactRecord.Id;
        testPaymentMethod.Account_Token__c = '1050';
        testPaymentMethod.Account_Number__c = '4968712468235235';
        testPaymentMethod.Card_Number__c = '7890';
        testPaymentMethod.Is_Active__c = true;
        testPaymentMethod.isDefault__c = true;
        insert testPaymentMethod;
    }
    
    @IsTest
    static void testGetDonorDefaultPaymentMethod() {
        Contact testDonor = [SELECT Id, AccountId, (SELECT Id, Name, Card_Number__c FROM Payment_Methods__r ORDER BY CreatedDate DESC LIMIT 1) FROM Contact WHERE Account.DonorId__c != null LIMIT 1];
        CancelCardController.PaymentMethod foundPaymentMethod;

        Test.startTest();
        foundPaymentMethod = CancelCardController.getDonorDefaultPaymentMethod(testDonor.AccountId);
        Test.stopTest();

        Assert.areEqual(foundPaymentMethod.id, testDonor.Payment_Methods__r[0].Id);
        Assert.areEqual(foundPaymentMethod.name, testDonor.Payment_Methods__r[0].Name);
        Assert.areEqual(foundPaymentMethod.cardNumber4Digits, testDonor.Payment_Methods__r[0].Card_Number__c.left(4));
    }

    @IsTest
    static void testCancelDonorActivePayment() {
        User experienceUser = TestUtil.createExperienceUser();

        System.runAs(TestUtil.createAdminUser()) {
            Payment_Method__c testPaymentMethod = new Payment_Method__c();
            testPaymentMethod.Name = 'Test Payment Method';
            testPaymentMethod.Donor__c = experienceUser.ContactId;
            testPaymentMethod.Account_Token__c = '1050';
            testPaymentMethod.Account_Number__c = '4968712468235235';
            testPaymentMethod.Card_Number__c = '7890';
            testPaymentMethod.Is_Active__c = true;
            testPaymentMethod.isDefault__c = true;
            insert testPaymentMethod;
        }

        Test.setMock(HttpCalloutMock.class, new OnbeWsManageCardHttpCalloutMock());

        Test.startTest();
        System.runAs(experienceUser) {
            CancelCardController.cancelDonorActivePayment();
        }
        Test.stopTest();

        Payment_Method__c updatedPaymentMethod = [SELECT Id, Is_Active__c, isDefault__c FROM Payment_Method__c WHERE Donor__c = :experienceUser.ContactId ORDER BY CreatedDate DESC LIMIT 1];

        Assert.isFalse(updatedPaymentMethod.Is_Active__c);
        Assert.isFalse(updatedPaymentMethod.isDefault__c);
    }

    @IsTest 
    static void testCancelPaymentMethod() {
        Contact testDonor = [SELECT Id, (SELECT Id FROM Payment_Methods__r WHERE Is_Active__c = true AND isDefault__c = true ORDER BY CreatedDate DESC LIMIT 1) FROM Contact WHERE Account.DonorId__c != null LIMIT 1];

        Test.setMock(HttpCalloutMock.class, new OnbeWsManageCardHttpCalloutMock());

        Test.startTest();
        CancelCardController.cancelPaymentMethod(testDonor.Payment_Methods__r[0].Id, Constants.ONBE_REISSUE_CARD_REVOKED_CODE);
        Test.stopTest();

        Payment_Method__c updatedPaymentMethod = [SELECT Id, Is_Active__c, isDefault__c FROM Payment_Method__c WHERE Id = :testDonor.Payment_Methods__r[0].Id LIMIT 1];

        Assert.isFalse(updatedPaymentMethod.Is_Active__c);
        Assert.isFalse(updatedPaymentMethod.isDefault__c);
    }
}