force-app/main/default/objects/Account/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <description>The coordinates of a Center&apos;s location.</description>
    <label>Geolocation</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Business_Hours__c/Business_Hours__c.object-meta.xml
<CustomObject>
    <description>Hours of business available for scheduling Donors</description>
    <label>Business Hours</label>
    <nameField>
        <label>Business Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Hours__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Business Hours</relationshipLabel>
    <relationshipName>Business_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Close__c.field-meta.xml
<CustomField>
    <fullName>Close__c</fullName>
    <description>Closing time</description>
    <label>Close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <description>1-based index of Days of Week</description>
    <label>Index</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/isClosed__c.field-meta.xml
<CustomField>
    <fullName>isClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Hours__c/fields/Open__c.field-meta.xml
<CustomField>
    <fullName>Open__c</fullName>
    <description>Open time</description>
    <label>Open</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Postal_Code__c/Postal_Code__c.object-meta.xml
<CustomObject>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Postal_Code__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/classes/CenterController.cls
public without sharing class CenterController {

    public static final Map<Decimal, String> BUSINESS_HOURS_INDEX_DAYS = new Map<Decimal, String>{
        1 => Label.Sunday,
        2 => Label.Monday,
        3 => Label.Tuesday,
        4 => Label.Wednesday,
        5 => Label.Thursday,
        6 => Label.Friday,
        7 => Label.Saturday
    };

    @AuraEnabled
    public static List<Center> getCenters(Double latitude, Double longitude) {
        try {
            Util.testExceptionHandling();

            List<Account> accounts = [
                SELECT
                    Name, BillingStreet, Geolocation__c
                FROM
                    Account
                WHERE
                    RecordTypeId = :Constants.CENTER_RECORD_TYPE_ID
                AND
                    IsActive__c = true
                ORDER BY
                    DISTANCE(Geolocation__c, GEOLOCATION(:latitude, :longitude), 'mi')
                LIMIT
                    5
            ];

            List<Center> centers = new List<Center>();

            for (Account account : accounts) {
                Center center = new Center();
                center.id = account.Id;
                center.name = account.Name;
                center.address = account.BillingStreet;
                center.distance = Decimal.valueOf(Location.getDistance(account.Geolocation__c, Location.newInstance(latitude, longitude), 'mi')).setScale(1);
                center.distanceUnit = 'mi';
                centers.add(center);
            }

            return centers;
        } catch (Exception e) {
            throw Util.createAuraHandledException(e);
        }
    }

    @AuraEnabled
    public static Center getCenter(Id centerId) {
        try {
            Util.testExceptionHandling();

            Account account = [
                SELECT
                    Name, BillingStreet, Geolocation__c,
                    (SELECT Index__c, Open__c, Close__c, isClosed__c FROM Business_Hours__r ORDER BY Index__c ASC)
                FROM
                    Account
                WHERE
                    Id = :centerId
            ];

            Center center = new Center();
            center.id = account.Id;
            center.name = account.Name;
            center.address = account.BillingStreet;

            for (Business_Hours__c bizHours : account.Business_Hours__r) {
                BusinessHours businessHours = new BusinessHours();
                businessHours.day = BUSINESS_HOURS_INDEX_DAYS.get(bizHours.Index__c);
                if (bizHours.Open__c != null) {
                    businessHours.open = DateTime.newInstance(Date.today(), bizHours.Open__c).format('h:mm a');
                }
                if (bizHours.Close__c != null) {
                    businessHours.close = DateTime.newInstance(Date.today(), bizHours.Close__c).format('h:mm a');
                }
                businessHours.isClosed = bizHours.isClosed__c;
                center.businessHoursList.add(businessHours);
            }

            return center;
        } catch (Exception e) {
            throw Util.createAuraHandledException(e);
        }
    }

    @AuraEnabled
    public static LatLong getLatLong(String postalCode) {
        try {
            Util.testExceptionHandling();

            List<Postal_Code__c> postalCodeRecords = [
                SELECT
                    Location__c
                FROM
                    Postal_Code__c
                WHERE
                    Name = :postalCode
                LIMIT
                    1
            ];

            if (postalCodeRecords.size() > 0) {
                Location location = postalCodeRecords[0].Location__c;

                LatLong latLong = new LatLong();
                latLong.latitude = location.latitude;
                latLong.longitude = location.longitude;

                return latLong;
            } else {
                return null;
            }
        } catch (Exception e) {
            throw Util.createAuraHandledException(e);
        }
    }

    public class Center {

        @AuraEnabled
        public Id id {get; set;}

        @AuraEnabled
        public String name {get; set;}

        @AuraEnabled
        public String address {get; set;}

        @AuraEnabled
        public Decimal distance {get; set;}

        @AuraEnabled
        public String distanceUnit {get; set;}

        @AuraEnabled
        public List<BusinessHours> businessHoursList {get; set;}

        public Center() {
            businessHoursList = new List<BusinessHours>();
        }

    }

    public class BusinessHours {

        @AuraEnabled
        public String day {get; set;}

        @AuraEnabled
        public String open {get; set;}

        @AuraEnabled
        public String close {get; set;}

        @AuraEnabled
        public Boolean isClosed {get; set;}
    }

    public class LatLong {

        @AuraEnabled
        public Double latitude {get; set;}

        @AuraEnabled
        public Double longitude {get; set;}

    }

}