force-app/main/default/objects/Account/fields/Individual_Exception_Limit__c.field-meta.xml
<CustomField>
    <fullName>Individual_Exception_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The maximum amount that can be issued for each individual exception payment.</description>
    <label>Individual Exception Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Max_Dollar_Per_Day__c.field-meta.xml
<CustomField>
    <fullName>Max_Dollar_Per_Day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The maximum amount of exception payments that can be issued on a per center basis. Measured in dollars.</description>
    <label>Max $ Per Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>The payment vehicle associated with a Donor</description>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <description>The donor owner of this payment method</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is_Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Payment rates for a Center&apos;s Donation Types</description>
    <label>Rate</label>
    <nameField>
        <displayFormat>R-{0}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Base_Payment__c.field-meta.xml
<CustomField>
    <fullName>Base_Payment__c</fullName>
    <description>The base amount per unit donation collected</description>
    <inlineHelpText>The base amount per unit donation collected</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Amount_Currency__c</fullName>
    <description>The amount of the transaction currency</description>
    <inlineHelpText>The amount of the transaction currency</inlineHelpText>
    <label>Amount Currency</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This indicates more detail about the transaction.</description>
    <inlineHelpText>This indicates more detail about the transaction.</inlineHelpText>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>The item description for this line in the transaction; user will most likely see this exact content</description>
    <inlineHelpText>The item description for this line in the transaction; user will most likely see this exact content</inlineHelpText>
    <label>Item</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>An amount of a specific item</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <description>The price paid for a unit of measure</description>
    <inlineHelpText>The price paid for a unit of measure</inlineHelpText>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DonorPaymentService.cls
public with sharing class DonorPaymentService {
    public static List<DonationPaymentResponse> createDonationPayment(List<DonationPaymentRequest> paymentRequests) {
        Set<Id> donorIds = new Set<Id>();

        for (DonationPaymentRequest donationPaymentRequest : paymentRequests) {
            donorIds.add(donationPaymentRequest.donorId);
        }

        Map<Id, String> donorIdToPaymentMethodAccountNumber = new Map<Id, String>();
        for(Payment_Method__c paymentMethod : [
            SELECT Id, Account_Number__c, Donor__c
            FROM Payment_Method__c
            WHERE Donor__c IN :donorIds AND
                Is_Active__c = true AND 
                isDefault__c = true
        ]) {
            donorIdToPaymentMethodAccountNumber.put(paymentMethod.Donor__c, paymentMethod.Account_Number__c);
        }

        Map<DonationPaymentRequest, Transaction__c> donationPaymentRequestToTransaction = new Map<DonationPaymentRequest, Transaction__c>();
        Map<DonationPaymentRequest, List<Txn_Line_Item__c>> donationPaymentRequestToTxnLineItems = new Map<DonationPaymentRequest, List<Txn_Line_Item__c>>();

        for(DonationPaymentRequest paymentRequest : paymentRequests) {
            donationPaymentRequestToTransaction.put(paymentRequest, new Transaction__c(
                Donor__c = paymentRequest.donorId,
                Visit__c = paymentRequest.visitId,
                Type__c = 'Credit',
                SubType__c = 'Donation Payment'
            ));

            List<Txn_Line_Item__c> donationPaymentLineItems = new List<Txn_Line_Item__c>();
            for(DonationPaymentLineItem lineItem : paymentRequest.donationLineItems) {
                donationPaymentLineItems.add(new Txn_Line_Item__c(
                    Item__c = lineItem.description,
                    Quantity__c = 1,
                    Unit_Cost__c = lineItem.unitCost,
                    Type__c = lineItem.type
                ));
            }

            donationPaymentRequestToTxnLineItems.put(paymentRequest, donationPaymentLineItems);
        }

        insert donationPaymentRequestToTransaction.values();

        List<DonationPaymentResponse> donationPaymentResponses = new List<DonationPaymentResponse>();
        List<Txn_Line_Item__c> allLineItems = new List<Txn_Line_Item__c>();

        for(DonationPaymentRequest paymentRequest : paymentRequests) {
            Transaction__c transactionRecord = donationPaymentRequestToTransaction.get(paymentRequest);
            List<Txn_Line_Item__c> donationPaymentLineItems = donationPaymentRequestToTxnLineItems.get(paymentRequest);

            for(Txn_Line_Item__c lineItem : donationPaymentLineItems) {
                lineItem.Transaction__c = transactionRecord.Id;
            }

            allLineItems.addAll(donationPaymentLineItems);

            Decimal totalCurrencyPaid = 0;
            Decimal totalPointsPaid = 0;

            for(Txn_Line_Item__c lineItem : donationPaymentLineItems) {
                if (lineItem.Type__c == 'Currency') {
                    totalCurrencyPaid += lineItem.Unit_Cost__c * lineItem.Quantity__c;
                } else if (lineItem.Type__c == 'Points') {
                    totalPointsPaid += lineItem.Unit_Cost__c * lineItem.Quantity__c;
                }
            }

            donationPaymentResponses.add(new DonationPaymentResponse(
                paymentRequest.donorId,
                paymentRequest.visitId,
                transactionRecord.Id,
                totalCurrencyPaid,
                totalPointsPaid
            ));
        }

        insert allLineItems;
        return donationPaymentResponses;
    }

    public class DonationPaymentRequest {
        public Id donorId;
        public Id visitId;

        public List<DonationPaymentLineItem> donationLineItems = new List<DonationPaymentLineItem>();

        public DonationPaymentRequest(Id donorId, Id visitId) {
            this.donorId = donorId;
            this.visitId = visitId;

            donationLineItems = new List<DonationPaymentLineItem>();
        }

        public void addDonationLineItem(String description, String type, Decimal unitCost) {
            donationLineItems.add(new DonationPaymentLineItem(description, type, unitCost));
        }
    }

    public class DonationPaymentLineItem {
        public String description;
        public String type;
        public Decimal unitCost;

        public DonationPaymentLineItem(String description, String type, Decimal unitCost) {
            this.description = description;
            this.type = type;
            this.unitCost = unitCost;
        }
    }

    public class DonationPaymentResponse {
        public Id donorId;
        public Id visitId;
        public Id transactionId;

        public Decimal totalCurrencyPaid;
        public Decimal totalPointsPaid;

        public DonationPaymentResponse(Id donorId, Id visitId, Id transactionId, Decimal totalCurrencyPaid, Decimal totalPointsPaid) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.transactionId = transactionId;
            this.totalCurrencyPaid = totalCurrencyPaid;
            this.totalPointsPaid = totalPointsPaid;
        }
    }

    public static List<ExceptionPaymentResponse> createExceptionPayment(List<ExceptionPaymentRequest> exceptionRequests) {
        List<DonorCompInvocable.AddFundsRequest> addFundsRequests = new List<DonorCompInvocable.AddFundsRequest>();
        
        Set<Id> exceptionRateIds = new Set<Id>();
        Set<Id> visitIds = new Set<Id>();

        for (ExceptionPaymentRequest exceptionRequest : exceptionRequests) {
            if (exceptionRequest.exceptionRateId != null && (exceptionRequest.exceptionAmount == null || String.isEmpty(exceptionRequest.exceptionReason))) {
                exceptionRateIds.add(exceptionRequest.exceptionRateId);
            }
            
            visitIds.add(exceptionRequest.visitId);
        }

        Map<Id, String> donorIdToPaymentMethodAccountNumber = new Map<Id, String>();
        for(Payment_Method__c paymentMethod : [
            SELECT Id, Account_Number__c, Donor__c
            FROM Payment_Method__c
            WHERE Donor__c IN (SELECT Donor__c FROM Visit__c WHERE Id IN :visitIds) AND
                Is_Active__c = true AND 
                isDefault__c = true
        ]) {
            donorIdToPaymentMethodAccountNumber.put(paymentMethod.Donor__c, paymentMethod.Account_Number__c);
        }

        // Verify Exception Limits haven't been exceeded before creating transactions
        Map<Id, Rate__c> exceptionRates;
        if (exceptionRateIds.size() > 0) {
            exceptionRates = new Map<Id, Rate__c>([
                SELECT Id, Base_Payment__c, Description__c, Center__c
                FROM Rate__c
                WHERE Id IN :exceptionRateIds
            ]);
        }

        Map<Id, Account> centerIdToCenter = new Map<Id, Account>();
        for(Visit__c targetVisit : [
            SELECT Id, Center_Donation_Type__r.Center__r.Name, Center_Donation_Type__r.Center__r.Max_Dollar_Per_Day__c, Center_Donation_Type__r.Center__r.Individual_Exception_Limit__c 
            FROM Visit__c 
            WHERE Id IN :visitIds
        ]) {
            centerIdToCenter.put(targetVisit.Id, targetVisit.Center_Donation_Type__r.Center__r);
        }

        Map<Id, Decimal> centerIdToTotalExceptionAmount = new Map<Id, Decimal>();
        for (AggregateResult result : [
            SELECT Visit__r.Center_Donation_Type__r.Center__c centerId, SUM(Amount_Currency__c) totalExceptionAmount
            FROM Transaction__c
            WHERE Visit__c IN :visitIds AND
                Type__c = 'Credit' AND
                SubType__c = 'Exception' AND 
                CreatedDate = TODAY
            GROUP BY Visit__r.Center_Donation_Type__r.Center__c
        ]) {
            centerIdToTotalExceptionAmount.put((Id)result.get('centerId'), (Decimal)result.get('totalExceptionAmount'));
        }

        for (ExceptionPaymentRequest exceptionRequest : exceptionRequests) {
            Decimal exceptionAmount;
            String exceptionReason;
            
            if (!String.isEmpty(exceptionRequest.exceptionRateId)) {
                Rate__c exceptionRate = exceptionRates.get(exceptionRequest.exceptionRateId);
                exceptionAmount = exceptionRate.Base_Payment__c;
                exceptionReason = exceptionRate.Description__c;
            } else {
                exceptionAmount = exceptionRequest.exceptionAmount;
                exceptionReason = exceptionRequest.exceptionReason;
            }

            Account center = centerIdToCenter.get(exceptionRequest.visitId);

            Decimal totalExceptionAmount = centerIdToTotalExceptionAmount.get(center.Id);
            if (totalExceptionAmount == null) {
                totalExceptionAmount = 0;
            }

            totalExceptionAmount += exceptionAmount;
            centerIdToTotalExceptionAmount.put(center.Id, totalExceptionAmount);

            if ((center.Max_Dollar_Per_Day__c != null && center.Max_Dollar_Per_Day__c > 0) && totalExceptionAmount > center.Max_Dollar_Per_Day__c) {
                throw new DonorPaymentException(String.format(Constants.CENTER_DAY_EXCEPTION_LIMIT_ERROR, new List<object> { center.Name }));
            }

            if ((center.Individual_Exception_Limit__c != null && center.Individual_Exception_Limit__c > 0) && exceptionAmount > center.Individual_Exception_Limit__c) {
                throw new DonorPaymentException(String.format(Constants.CENTER_INDIVIDUAL_EXCEPTION_LIMIT_ERROR, new List<object> { center.Name }));
            }

            DonorCompInvocable.AddFundsRequest addFundsRequest = new DonorCompInvocable.AddFundsRequest(
                exceptionRequest.donorId, exceptionRequest.visitId, donorIdToPaymentMethodAccountNumber.get(exceptionRequest.donorId), 'Exception'
            );

            addFundsRequest.addLineItem(exceptionReason, 'Currency', exceptionAmount);
            addFundsRequest.comments.add('Exception Payment - ' + exceptionReason);
            addFundsRequest.isExceptionPayment = true;

            addFundsRequests.add(addFundsRequest);
        }
        
        // Assuming no exceptions, create the actual transactions
        Map<Id, Transaction__c> visitIdToTransaction = new Map<Id, Transaction__c>();
        Map<Id, Task> visitIdToExceptionPaymentTask = new Map<Id, Task>();

        List<Group> targetExceptionPaymentTaskQueue = [SELECT Id FROM Group WHERE DeveloperName = 'Proesis_Operations' LIMIT 1];
        for(ExceptionPaymentRequest exceptionRequest : exceptionRequests) {
            String exceptionReason;
            
            if (!String.isEmpty(exceptionRequest.exceptionRateId)) {
                Rate__c exceptionRate = exceptionRates.get(exceptionRequest.exceptionRateId);
                exceptionReason = exceptionRate.Description__c;
            } else {
                exceptionReason = exceptionRequest.exceptionReason;
            }
            
            Transaction__c exceptionTransaction = new Transaction__c(
                Donor__c = exceptionRequest.donorId,
                Visit__c = exceptionRequest.visitId,
                Status__c = 'Complete',
                Type__c = 'Credit',
                SubType__c = 'Exception'
            );

            Task exceptionPaymentTask = new Task(
                WhoId = exceptionRequest.donorId,
                WhatId = exceptionRequest.visitId,
                Subject = 'Exception Payment - ' + exceptionReason,
                ActivityDate = Date.today(),
                OwnerId = targetExceptionPaymentTaskQueue[0].Id
            );

            visitIdToExceptionPaymentTask.put(exceptionRequest.visitId, exceptionPaymentTask);
            visitIdToTransaction.put(exceptionRequest.visitId, exceptionTransaction);
        }

        insert visitIdToTransaction.values();
        insert visitIdToExceptionPaymentTask.values();

        List<Txn_Line_Item__c> lineItems = new List<Txn_Line_Item__c>();
        List<ExceptionPaymentResponse> exceptionResponses = new List<ExceptionPaymentResponse>();

        for (ExceptionPaymentRequest exceptionRequest : exceptionRequests) {
            Transaction__c exceptionTransaction = visitIdToTransaction.get(exceptionRequest.visitId);
            Decimal exceptionAmount;
            String exceptionReason;
            
            if (!String.isEmpty(exceptionRequest.exceptionRateId)) {
                Rate__c exceptionRate = exceptionRates.get(exceptionRequest.exceptionRateId);
                exceptionAmount = exceptionRate.Base_Payment__c;
                exceptionReason = exceptionRate.Description__c;
            } else {
                exceptionAmount = exceptionRequest.exceptionAmount;
                exceptionReason = exceptionRequest.exceptionReason;
            }
            
            exceptionResponses.add(new ExceptionPaymentResponse(exceptionRequest.donorId, exceptionRequest.visitId, exceptionAmount, exceptionReason, exceptionTransaction.Id));
            lineItems.add(new Txn_Line_Item__c(
                Transaction__c = exceptionTransaction.Id,
                Item__c = exceptionReason,
                Unit_Cost__c = exceptionAmount,
                Quantity__c = 1,
                Type__c = 'Currency'
            ));
        }
        insert lineItems;

        Database.executeBatch(new AddFundsBatchable(addFundsRequests), 100);
        return exceptionResponses;
    }

    public class ExceptionPaymentRequest {
        public Id donorId;
        public Id visitId;
        public Id exceptionRateId;

        public Decimal exceptionAmount;
        public String exceptionReason;

        public ExceptionPaymentRequest(Id donorId, Id visitId, Id exceptionRateId) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.exceptionRateId = exceptionRateId;
        }

        public ExceptionPaymentRequest(Id donorId, Id visitId, Decimal amount, String reason) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.exceptionAmount = amount;
            this.exceptionReason = reason;
        }
    }

    public class ExceptionPaymentResponse {
        public Id donorId;
        public Id visitId;
        public Decimal amount;
        public String reason;
        public Id exceptionTransactionId;

        public ExceptionPaymentResponse(Id donorId, Id visitId, Decimal amount, String reason, Id exceptionTransactionId) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.amount = amount;
            this.reason = reason;
            this.exceptionTransactionId = exceptionTransactionId;
        }
    }

    public static List<PromotionPaymentResponse> createPromotionPayment(List<PromotionPaymentRequest> promotionRequests) {
        Map<Id, String> donorIdToAccountNumber = new Map<Id, String>();
        for (PromotionPaymentRequest request : promotionRequests) {
            donorIdToAccountNumber.put(request.donorId, null);
        }

        for(Payment_Method__c activePaymentMethod : [SELECT Id, Account_Number__c, Donor__c FROM Payment_Method__c WHERE Donor__c IN :donorIdToAccountNumber.keySet() AND Is_Active__c = true]) {
            donorIdToAccountNumber.put(activePaymentMethod.Donor__c, activePaymentMethod.Account_Number__c);
        }
        
        Map<PromotionPaymentRequest, Transaction__c> promotionPaymentRequestToTransaction = new Map<PromotionPaymentRequest, Transaction__c>();
        Map<PromotionPaymentRequest, List<Txn_Line_Item__c>> promotionPaymentRequestToTxnLineItems = new Map<PromotionPaymentRequest, List<Txn_Line_Item__c>>();

        for (PromotionPaymentRequest request : promotionRequests) {
            promotionPaymentRequestToTransaction.put(request, new Transaction__c(
                Donor__c = request.donorId,
                Visit__c = request.visitId,
                Type__c = 'Credit',
                SubType__c = 'Promotion Payment',
                Status__c = 'Complete'
            ));

            promotionPaymentRequestToTxnLineItems.put(request, new List<Txn_Line_Item__c> {
                new Txn_Line_Item__c(
                    Type__c = 'Currency',
                    Unit_Cost__c = request.amount,
                    Item__c = request.reason,
                    Quantity__c = 1
                )
            });
        }

        insert promotionPaymentRequestToTransaction.values();
        
        List<Txn_Line_Item__c> allTxnLineItems = new List<Txn_Line_Item__c>();
        for(PromotionPaymentRequest promotionPaymentRequestWithLineItems : promotionPaymentRequestToTxnLineItems.keySet()) {
            Transaction__c txnRecord = promotionPaymentRequestToTransaction.get(promotionPaymentRequestWithLineItems);
            List<Txn_Line_Item__c> lineItems = promotionPaymentRequestToTxnLineItems.get(promotionPaymentRequestWithLineItems);

            for(Txn_Line_Item__c lineItem : lineItems) {
                lineItem.Transaction__c = txnRecord.Id;
            }

            allTxnLineItems.addAll(lineItems);
        }
        insert allTxnLineItems;

        // Process the payments through Onbe
        List<DonorCompInvocable.AddFundsRequest> addFundsRequest = new List<DonorCompInvocable.AddFundsRequest>();
        List<PromotionPaymentResponse> promotionPaymentResponses = new List<PromotionPaymentResponse>();

        for(Transaction__c updatedTransaction : [
            SELECT Id, Donor__c, Visit__c, Amount_Currency__c, (
                SELECT Id, Unit_Cost__c, Type__c, Item__c 
                FROM Txn_Line_Items__r
            ) 
            FROM Transaction__c 
            WHERE Id IN :promotionPaymentRequestToTransaction.values()
        ]) {
            DonorCompInvocable.AddFundsRequest newRequest = new DonorCompInvocable.AddFundsRequest(
                updatedTransaction.Donor__c, updatedTransaction.Visit__c, donorIdToAccountNumber.get(updatedTransaction.Donor__c), 'Promotion Payment'
            );

            for(Txn_Line_Item__c lineItem : updatedTransaction.Txn_Line_Items__r) {
                newRequest.comments.add(lineItem.Item__c);
                newRequest.addLineItem(lineItem.Item__c, lineItem.Type__c, lineItem.Unit_Cost__c);
            }
            
            addFundsRequest.add(newRequest);
            promotionPaymentResponses.add(new PromotionPaymentResponse(
                updatedTransaction.Donor__c, updatedTransaction.Visit__c, updatedTransaction.Amount_Currency__c, String.join(newRequest.comments, ', '), updatedTransaction.Id
            ));
        }

        Database.executeBatch(new AddFundsBatchable(addFundsRequest), 100);
        return promotionPaymentResponses;
    }

    public class PromotionPaymentRequest {
        public Id donorId;
        public Id visitId;
        public Decimal amount;
        public String reason;

        public PromotionPaymentRequest(Id donorId, Id visitId, Decimal amount, String reason) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.amount = amount;
            this.reason = reason;
        }
    }

    public class PromotionPaymentResponse {
        public Id donorId;
        public Id visitId;
        public Decimal amount;
        public String reason;
        public Id promotionTransactionId;

        public PromotionPaymentResponse(Id donorId, Id visitId, Decimal amount, String reason, Id promotionTransactionId) {
            this.donorId = donorId;
            this.visitId = visitId;
            this.amount = amount;
            this.reason = reason;
            this.promotionTransactionId = promotionTransactionId;
        }
    }

    public class DonorPaymentException extends Exception { }
}