force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Enable_Payment_Requests__c.field-meta.xml
<CustomField>
    <fullName>Enable_Payment_Requests__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Incentive Type Campaigns, indicates if Payment Requests should be created automatically when new Campaign Levels are achieved for Campaign Members.</description>
    <inlineHelpText>For Incentive Type Campaigns, indicates if Payment Requests should be created automatically when new Campaign Levels are achieved for Campaign Members.</inlineHelpText>
    <label>Enable Payment Requests</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Member_Incentive_Life_Days__c.field-meta.xml
<CustomField>
    <fullName>Member_Incentive_Life_Days__c</fullName>
    <description>Indicates the numbers of days since joining the Campaign that the member is eligible for the incentive.</description>
    <inlineHelpText>Indicates the numbers of days since joining the Campaign that the member is eligible for the incentive.</inlineHelpText>
    <label>Member Incentive Life (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/Campaign_Level__c.object-meta.xml
<CustomObject>
    <description>Indicates levels of achievement and payment for incentive type Campaigns.</description>
    <label>Campaign Level</label>
    <nameField>
        <label>Campaign Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Level__c/fields/Award_Dollar_Amount__c.field-meta.xml
<CustomField>
    <fullName>Award_Dollar_Amount__c</fullName>
    <description>Indicates the dollar amount award for the incentive level.</description>
    <inlineHelpText>Indicates the dollar amount award for the incentive level.</inlineHelpText>
    <label>Award (Dollar Amount)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Campaign to which this Level belongs. Campaign MUST be an `Incentive` Type to link correctly.</description>
    <inlineHelpText>The Campaign to which this Level belongs. Campaign MUST be an `Incentive` Type to link correctly.</inlineHelpText>
    <label>Campaign</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an Incentive Type Campaign to link this Level.</errorMessage>
        <filterItems>
            <field>Campaign.Type</field>
            <operation>equals</operation>
            <value>Incentive</value>
        </filterItems>
        <infoMessage>Please select an Incentive Type Campaign to link this Level.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Levels</relationshipLabel>
    <relationshipName>Campaign_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the incentive level is active or not. Allows for editing incentives, activating, and deactivating.</description>
    <inlineHelpText>Indicates if the incentive level is active or not. Allows for editing incentives, activating, and deactivating.</inlineHelpText>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Message_Body_Default__c.field-meta.xml
<CustomField>
    <fullName>Message_Body_Default__c</fullName>
    <description>The default content of the Message body, for mobile notification, limited to 255 characters</description>
    <inlineHelpText>The default content of the Message body, for mobile notification, limited to 255 characters</inlineHelpText>
    <label>Message Body Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Message_Subject_Default__c.field-meta.xml
<CustomField>
    <fullName>Message_Subject_Default__c</fullName>
    <description>The default content of the Message subject, for mobile notification, limited to 80 characters.</description>
    <inlineHelpText>The default content of the Message subject, for mobile notification, limited to 80 characters.</inlineHelpText>
    <label>Message Subject Default</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Level__c/fields/Minimum_Donation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Donation_Amount__c</fullName>
    <description>Indicates the number of eligible donations for a member of the Campaign to reach to get this incentive.</description>
    <inlineHelpText>Indicates the number of eligible donations for a member of the Campaign to reach to get this incentive.</inlineHelpText>
    <label>Minimum Donation Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Campaign_Level__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current Campaign Level for this Member, if applicable (for incentive Campaigns only).</description>
    <inlineHelpText>Current Campaign Level for this Member, if applicable (for incentive Campaigns only).</inlineHelpText>
    <label>Campaign Level</label>
    <referenceTo>Campaign_Level__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Eligible_Donation_Count__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Donation_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date. This is set automatically by code, based on Status = Complete and Outcome = Donation visits for the Campaign Member Contact.</description>
    <inlineHelpText>The total count of successful (completed donations) visits for a Donor since he / she joined the Campaign, until the Campaign End Date.</inlineHelpText>
    <label>Eligible Donation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Incentive_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Eligible__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this Campaign Member is eligible for incentives in this Campaign. For Incentive Type Campaigns only. Defaults to checked (true).</description>
    <inlineHelpText>Indicates whether this Campaign Member is eligible for incentives in this Campaign.</inlineHelpText>
    <label>Incentive Eligible?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Starting_Donation_Count__c.field-meta.xml
<CustomField>
    <fullName>Starting_Donation_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Enter this only for use to allow a Campaign Member to start at a higher level. This will affect how the Member is placed into Campaign Levels.</description>
    <inlineHelpText>Enter this only for use to allow a Campaign Member to start at a higher level. This will affect how the Member is placed into Campaign Levels.</inlineHelpText>
    <label>Starting Donation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Total_Eligible_Donation_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Eligible_Donation_Count__c</fullName>
    <description>This is set automatically as a calculation of the starting eligible amount plus the counts automatically computed for a donor from Starting Donation Count plus Eligible Donation Count.</description>
    <inlineHelpText>This is set automatically as a calculation of the starting eligible amount plus the counts automatically computed for a donor from Starting Donation Count plus Eligible Donation Count.</inlineHelpText>
    <label>Total Eligible Donation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <description>Used to manage payment requests for approval, typically for promotional and/or exceptional payments.</description>
    <label>Payment Request</label>
    <nameField>
        <label>Payment Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Dollars__c.field-meta.xml
<CustomField>
    <fullName>Amount_Dollars__c</fullName>
    <description>The dollar amount for the payment request.</description>
    <inlineHelpText>The dollar amount for the payment request.</inlineHelpText>
    <label>Amount (Dollars)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Points__c.field-meta.xml
<CustomField>
    <fullName>Amount_Points__c</fullName>
    <description>The point amount for the payment request.</description>
    <inlineHelpText>The point amount for the payment request.</inlineHelpText>
    <label>Amount (Points)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Campaign_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Id__c</fullName>
    <description>The Campaign Member to which the Payment Request relates. NOTE: Campaign Members do not allow lookup relationships currently in Salesforce, so this is a text field.</description>
    <inlineHelpText>The Campaign Member to which the Payment Request relates.</inlineHelpText>
    <label>Campaign Member Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor to whom this request relates.</description>
    <inlineHelpText>The Donor to whom this request relates.</inlineHelpText>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Reason_Description__c.field-meta.xml
<CustomField>
    <fullName>Reason_Description__c</fullName>
    <description>A short reason / description to print on the Transaction Line Item.</description>
    <inlineHelpText>A short reason / description to print on the Transaction Line Item.</inlineHelpText>
    <label>Reason / Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Advances the state of the request, controlled by approval processes and automation.</description>
    <inlineHelpText>Advances the state of the request, controlled by approval processes and automation.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If applicable, the visit to which this request relates.</description>
    <inlineHelpText>If applicable, the visit to which this request relates.</inlineHelpText>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerHandlerTest.cls
/**
 * Created by joshlequire1 on 5/31/23.
 */
@IsTest
public without sharing class CampaignMemberTriggerHandlerTest {

    @IsTest
    static void testTotalEligibleCountUpdate() {
        Account testPerson = TestUtil.createDonor('234567');
        insert testPerson;

        Id personContactId = [SELECT PersonContactId FROM Account WHERE Id = :testPerson.Id][0].PersonContactId;

        Campaign testCampaign = new Campaign(
            Name = 'Test Campaign',
            IsActive = true
        );

        insert testCampaign;

        CampaignMember testCampaignMember = new CampaignMember(
            CampaignId = testCampaign.Id,
            ContactId = personContactId
        );

        insert testCampaignMember;

        update new CampaignMember(
            Id = testCampaignMember.Id,
            Starting_Donation_Count__c = 1
        );

        CampaignMember cmCheck1 = [
            SELECT Id,
                Starting_Donation_Count__c,
                Eligible_Donation_Count__c,
                Total_Eligible_Donation_Count__c
            FROM CampaignMember
        ]
            [0];

        Assert.areEqual(0, cmCheck1.Eligible_Donation_Count__c);
        Assert.areEqual(1, cmCheck1.Total_Eligible_Donation_Count__c);
    }

    @IsTest
    static void testIncentivePromotion() {
        Account testPerson = TestUtil.createDonor('123456');
        insert testPerson;

        Id personContactId = [SELECT PersonContactId FROM Account WHERE Id = :testPerson.Id][0].PersonContactId;

        Campaign incentiveCampaign = new Campaign(
            Name = 'Test Campaign',
            Type = Constants.CAMPAIGN_TYPE_INCENTIVE,
            IsActive = true,
            Enable_Payment_Requests__c = true,
            Member_Incentive_Life_Days__c = 10
        );

        insert incentiveCampaign;

        List<Campaign_Level__c> incentiveCampaignLevels = new List<Campaign_Level__c>{
            new Campaign_Level__c(
                Name = 'Level 1',
                Award_Dollar_Amount__c = 100,
                Campaign__c = incentiveCampaign.Id,
                isActive__c = true,
                Minimum_Donation_Amount__c = 1,
                Message_Subject_Default__c = 'You achieved level 1!',
                Message_Body_Default__c = 'Here\'s some sweet moolah'
            ),
            new Campaign_Level__c(
                Name = 'Level 2',
                Award_Dollar_Amount__c = 50,
                Campaign__c = incentiveCampaign.Id,
                isActive__c = true,
                Minimum_Donation_Amount__c = 2,
                Message_Subject_Default__c = 'You achieved level 2!',
                Message_Body_Default__c = 'Here\'s some more sweet moolah'
            )
        };

        insert incentiveCampaignLevels;

        Map<Integer, Campaign_Level__c> incentiveCampaignLevelMap = new Map<Integer, Campaign_Level__c>();

        for (Campaign_Level__c cl : incentiveCampaignLevels) {
            incentiveCampaignLevelMap.put(Integer.valueOf(cl.Minimum_Donation_Amount__c), cl);
        }

        // Expects Incentive_Eligible__c to default to TRUE; test will fail (as expected) if that changes.
        CampaignMember testCampaignMember = new CampaignMember(
            ContactId = personContactId,
            CampaignId = incentiveCampaign.Id
        );

        insert testCampaignMember;

        Test.startTest();
        CampaignMember cmUpdate1 = new CampaignMember(
            Id = testCampaignMember.Id,
            Eligible_Donation_Count__c = 1
        );

        update cmUpdate1;

        CampaignMember cmUpdate1Check = [SELECT Id, Eligible_Donation_Count__c, Campaign_Level__c FROM CampaignMember WHERE Id = :testCampaignMember.Id][0];

        // Verify change from null value to 1
        Assert.areEqual(incentiveCampaignLevelMap.get(1).Id, cmUpdate1Check.Campaign_Level__c);

        CampaignMember cmUpdate2 = new CampaignMember(
            Id = testCampaignMember.Id,
            Eligible_Donation_Count__c = 2
        );

        update cmUpdate2;

        CampaignMember cmUpdate2Check = [SELECT Id, Eligible_Donation_Count__c, Campaign_Level__c FROM CampaignMember WHERE Id = :testCampaignMember.Id][0];

        // Verify change from 1 to 2
        Assert.areEqual(incentiveCampaignLevelMap.get(2).Id, cmUpdate2Check.Campaign_Level__c);

        CampaignMember cmUdpate3 = new CampaignMember(
            Id = testCampaignMember.Id,
            Eligible_Donation_Count__c = 3
        );

        update cmUdpate3;

        // Verify no change from 2 to 3, because no level exists for this
        CampaignMember cmUpdate3Check = [SELECT Id, Eligible_Donation_Count__c, Campaign_Level__c FROM CampaignMember WHERE Id = :testCampaignMember.Id][0];

        Assert.areEqual(incentiveCampaignLevelMap.get(2).Id, cmUpdate3Check.Campaign_Level__c);

        // Change Incentive Life, test result
        Campaign incentiveCampaignUpdate = new Campaign(
            Id = incentiveCampaign.Id,
            Member_Incentive_Life_Days__c = -1
        );

        update incentiveCampaignUpdate;

        CampaignMember cmUpdate4 = new CampaignMember(
            Id = testCampaignMember.Id,
            Eligible_Donation_Count__c = 1
        );

        CampaignMember cmUpdate4Check = [SELECT Id, Eligible_Donation_Count__c, Campaign_Level__c FROM CampaignMember WHERE Id = :testCampaignMember.Id][0];

        // Should be no change
        Assert.areEqual(incentiveCampaignLevelMap.get(2).Id, cmUpdate3Check.Campaign_Level__c);

        Test.stopTest();

        for (Payment_Request__c pr : [
            SELECT Id,
                Name,
                Reason_Description__c,
                Amount_Dollars__c,
                Amount_Points__c,
                Status__c,
                Donor__c,
                Visit__c,
                Campaign_Member_Id__c,
                Message_Subject__c,
                Message_Body__c
            FROM Payment_Request__c
        ]) {
            Assert.areEqual(pr.Donor__c, personContactId);
            Assert.areEqual(testCampaignMember.Id, pr.Campaign_Member_Id__c);
            Assert.areEqual(Constants.PAYMENTREQUEST_STATUS_NEW, pr.Status__c);
            if (pr.Name.contains('Level 1')) {
                Assert.areEqual(100, pr.Amount_Dollars__c);
                Assert.areEqual('You achieved level 1!', pr.Message_Subject__c);
                Assert.areEqual('Here\'s some sweet moolah', pr.Message_Body__c);
            } else {
                Assert.areEqual(50, pr.Amount_Dollars__c);
                Assert.areEqual('You achieved level 2!', pr.Message_Subject__c);
                Assert.areEqual('Here\'s some more sweet moolah', pr.Message_Body__c);
            }
        }
    }
}