force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the setup of a new Donation Type for a Center without affecting processing until active=True</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of donation for this Visit</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VisitSelectorTest.cls
@IsTest
public class VisitSelectorTest {
    final static Integer NUMBER_OF_TEST_VISITS = 5;

    @TestSetup
    static void createTestData() {
        // Account of type center
        Account center = new Account();
        center.Name = 'Test Center';
        center.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Center' LIMIT 1].Id;
        insert center;

        // Donation Type
        Donation_Type__c donationType = new Donation_Type__c();
        donationType.Name = 'Test Donation Type';
        insert donationType;

        // Center Donation Type
        Center_Donation_Type__c centerDonationType = new Center_Donation_Type__c();
        centerDonationType.Center__c = center.Id;
        centerDonationType.Donation_Type__c = donationType.Id;
        centerDonationType.isActive__c = true;
        insert centerDonationType;

        Account testDonor = TestUtil.createTestDonor(ScheduleUtils.createFirstVisitCode());
        insert testDonor;

        List<Visit__c> visits = new List<Visit__c>();
        Contact testDonorContact = [SELECT Id FROM Contact WHERE AccountId = :testDonor.Id LIMIT 1];

        for(Integer i = 0; i < NUMBER_OF_TEST_VISITS; i++) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = testDonorContact.Id;
            visit.Center_Donation_Type__c = centerDonationType.Id;
            visit.Status__c = 'Scheduled';
            visits.add(visit);
        }
        insert visits;
    }

    @IsTest
    static void testVisitSelector() {
        Integer numberOfVisits;
        
        Test.startTest();
        System.runAs(TestUtil.createExperienceUserFromContactId([SELECT Id FROM Contact LIMIT 1].Id)) {
            numberOfVisits = VisitSelector.getCurrentDonorVisitCount();
        }
        Test.stopTest();

        Assert.areEqual(NUMBER_OF_TEST_VISITS, numberOfVisits, 'Number of visits should be ' + NUMBER_OF_TEST_VISITS);
    }
}