force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <description>The services offered at a given donation Center</description>
    <label>Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Center_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the setup of a new Donation Type for a Center without affecting processing until active=True</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Center_Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Donation</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: New Donor</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: Annual Physical</fullName>
    </customValue>
    <customValue>
        <fullName>Medical: Consultation</fullName>
    </customValue>
    <description>The types of services offered by a Donation Center</description>
    <masterLabel>Center Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DonorSelectorTest.cls
@IsTest
public with sharing class DonorSelectorTest {
    static final String SEARCH_TERM = 'FoundDonor';
    static final Integer EXPECTED_SEARCH_RESULT_COUNT = 3;
    static final Integer EXPECTED_MISSING_SEARCH_RESULT_COUNT = 3;
    
    @TestSetup
    static void createTestData() {
        String targetDonorRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Donor').getRecordTypeId();
        String targetCenterRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Center').getRecordTypeId();

        List<Account> donorsAndCenter = new List<Account> {
            new Account(
                Name = 'Test Donor Center',
                RecordTypeId = targetCenterRecordTypeId,
                Services__c = 'Donation',
                IsActive__c = true
            )
        };

        for(Integer i = 0; i < EXPECTED_SEARCH_RESULT_COUNT; i++) {
            donorsAndCenter.add(
                new Account(
                    FirstName = SEARCH_TERM + 'Test' + (i + 1),
                    LastName = 'Tester',
                    RecordTypeId = targetDonorRecordTypeId
                )
            );
        }
        for(Integer j = 0; j < EXPECTED_MISSING_SEARCH_RESULT_COUNT; j++) {
            donorsAndCenter.add(
                new Account(
                    FirstName = 'MissingDonor' + 'Test' + (j + 1),
                    LastName = 'Tester',
                    RecordTypeId = targetDonorRecordTypeId
                )
            );
        }

        insert donorsAndCenter;

        Donation_Type__c testDonationType = new Donation_Type__c(
            Name = 'Donation Type 1'
        );
        insert testDonationType;

        Center_Donation_Type__c centerDonationType1 = new Center_Donation_Type__c(
            Center__c = donorsAndCenter[0].Id,
            Donation_Type__c = testDonationType.Id,
            isActive__c = true
        );
        insert centerDonationType1;
    }

    @IsTest
    static void searchVisitElgibleDonorByNameSuccessTest() {
        List<Account> foundDonors;

        Test.startTest();
        foundDonors = DonorSelector.searchVisitElgibleDonorByName(SEARCH_TERM, DateTime.now());
        Test.stopTest();

        Assert.areEqual(EXPECTED_SEARCH_RESULT_COUNT, foundDonors.size(), 'Expected to find ' + EXPECTED_SEARCH_RESULT_COUNT + ' donors.');
    }

    @IsTest
    static void searchVisitElgibleDonorByNameNoResultsTest() {
        List<Account> foundDonors;

        Test.startTest();
        foundDonors = DonorSelector.searchVisitElgibleDonorByName('RandomTermThatHasNoResultsHere', DateTime.now());
        Test.stopTest();

        Assert.areEqual(0, foundDonors.size(), 'Expected No Results when a nonsense string is provided');
    }

    @IsTest
    static void searchVisitElgibleDonorByNameNoSearchTermTest() {
        List<Account> foundDonors;

        Test.startTest();
        foundDonors = DonorSelector.searchVisitElgibleDonorByName(null, DateTime.now());
        Test.stopTest();

        Assert.areEqual(null, foundDonors, 'If nothing is passed, nothing is returned');
        Assert.areEqual(0, Limits.getQueries(), 'If nothing is passed, no queries should be executed');
    }
}