force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Serves to hide a Center during development before it is open for business from the mobile app, etc.</description>
    <inlineHelpText>Serves to hide a Center during development before it is open for business from the mobile app, etc.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Center.recordType-meta.xml
<RecordType>
    <fullName>Center</fullName>
    <active>true</active>
    <description>Center for plasma collection services.</description>
    <label>Center</label>
   
    
</RecordType>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center_Donation_Type__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Center for this Donation Type</description>
    <label>Center</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Center account does not exist.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donation Type supported by this Center</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Center Donation Types</relationshipLabel>
    <relationshipName>Center_Donation_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows the setup of a new Donation Type for a Center without affecting processing until active=True</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donation_Type__c/Donation_Type__c.object-meta.xml
<CustomObject>
    <label>Donation Type</label>
    <nameField>
        <label>Donation Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Amount_Currency__c</fullName>
    <description>The amount of the transaction currency</description>
    <inlineHelpText>The amount of the transaction currency</inlineHelpText>
    <label>Amount Currency</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount_Points__c.field-meta.xml
<CustomField>
    <fullName>Amount_Points__c</fullName>
    <description>The amount in points for this transaction</description>
    <inlineHelpText>The amount in points for this transaction</inlineHelpText>
    <label>Amount Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>An amount of a specific item</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <description>The price paid for a unit of measure</description>
    <inlineHelpText>The price paid for a unit of measure</inlineHelpText>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <formula>Appointment__r.Schedule__r.Center__r.Name</formula>
    <label>Center</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Donation_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of donation for this Visit</description>
    <label>Donation Type</label>
    <referenceTo>Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TxnLineItemTriggerHandlerTest.cls
@IsTest
public class TxnLineItemTriggerHandlerTest {
    static Integer NUMBER_OF_TRANSACTIONS = 201;

    @TestSetup
    static void makeData() {
        // Account of type center
        Account center = new Account();
        center.Name = 'Test Center';
        center.RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Center' LIMIT 1].Id;
        insert center;

        // Donation Type
        Donation_Type__c donationType = new Donation_Type__c();
        donationType.Name = 'Test Donation Type';
        insert donationType;

        // Center Donation Type
        Center_Donation_Type__c centerDonationType = new Center_Donation_Type__c();
        centerDonationType.Center__c = center.Id;
        centerDonationType.Donation_Type__c = donationType.Id;
        centerDonationType.isActive__c = true;
        insert centerDonationType;

        // Create a transaction
        List<Contact> donors = new List<Contact>();
        // Id donorRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Donor' LIMIT 1].Id;

        for(Integer i = 0; i < NUMBER_OF_TRANSACTIONS; i++) {
            Contact donor = new Contact();
            donor.FirstName = 'Test Donor' + i;
            donor.LastName = 'DonorLast' + i;
            donors.add(donor);
        }
        insert donors;

        List<Visit__c> visits = new List<Visit__c>();
        for(Integer i = 0; i < NUMBER_OF_TRANSACTIONS; i++) {
            Visit__c visit = new Visit__c();
            visit.Donor__c = donors[i].Id;
            visit.Center_Donation_Type__c = centerDonationType.Id;
            visit.Status__c = 'Complete';
            visit.Outcome__c = 'Donation';
            visits.add(visit);
        }
        insert visits;

        List<Transaction__c> txnRecords = new List<Transaction__c>();
        for(Integer i = 0; i < NUMBER_OF_TRANSACTIONS; i++) {
            Transaction__c txn = new Transaction__c();
            txn.Donor__c = donors[i].Id;
            txn.Visit__c = visits[i].Id;
            txnRecords.add(txn);
        }
        insert txnRecords;
    }

    @isTest
    private static void testBulkTxnLineItemInsert() {
        // Create a transaction
        List<Transaction__c> txnRecords = [SELECT Id FROM Transaction__c];
        List<Txn_Line_Item__c> lineItems = new List<Txn_Line_Item__c>();

        for(Transaction__c txn : txnRecords) {
            lineItems.add(new Txn_Line_Item__c(
                Transaction__c = txn.Id,
                Type__c = 'Currency',
                Quantity__c = 1,
                Unit_Cost__c = 10
            ));
            lineItems.add(new Txn_Line_Item__c(
                Transaction__c = txn.Id,
                Type__c = 'Points',
                Quantity__c = 1,
                Unit_Cost__c = 1000
            ));
        }

        Test.startTest();
        insert lineItems;
        Test.stopTest();

        // Verify that the transaction has the correct values
        txnRecords = [SELECT Id, Amount_Currency__c, Amount_Points__c FROM Transaction__c];
        
        Assert.areEqual(NUMBER_OF_TRANSACTIONS, txnRecords.size(), 'There should be ' + NUMBER_OF_TRANSACTIONS + ' transactions');
        for(Transaction__c txnRecord : txnRecords) {
            Assert.areEqual(10, txnRecord.Amount_Currency__c, 'Amount_Currency__c should be 10');
            Assert.areEqual(1000, txnRecord.Amount_Points__c, 'Amount_Points__c should be 1000');
        }
    }

    @isTest
    private static void testBulkTxnLineItemUpdate() {
        // Create a transaction
        List<Transaction__c> txnRecords = [SELECT Id FROM Transaction__c];
        List<Txn_Line_Item__c> lineItems = new List<Txn_Line_Item__c>();

        for(Transaction__c txn : txnRecords) {
            lineItems.add(new Txn_Line_Item__c(
                Transaction__c = txn.Id,
                Type__c = 'Currency',
                Quantity__c = 0,
                Unit_Cost__c = 10
            ));
            lineItems.add(new Txn_Line_Item__c(
                Transaction__c = txn.Id,
                Type__c = 'Points',
                Quantity__c = 0,
                Unit_Cost__c = 1000
            ));
        }
        insert lineItems;

        // Update the quantities to 1
        for(Txn_Line_Item__c lineItem : lineItems) {
            lineItem.Quantity__c = 1;
        }

        Test.startTest();
        update lineItems;
        Test.stopTest();

        // Verify that the transaction has the correct values
        txnRecords = [SELECT Id, Amount_Currency__c, Amount_Points__c FROM Transaction__c];
        
        Assert.areEqual(NUMBER_OF_TRANSACTIONS, txnRecords.size(), 'There should be ' + NUMBER_OF_TRANSACTIONS + ' transactions');
        for(Transaction__c txnRecord : txnRecords) {
            Assert.areEqual(10, txnRecord.Amount_Currency__c, 'Amount_Currency__c should be 10');
            Assert.areEqual(1000, txnRecord.Amount_Points__c, 'Amount_Points__c should be 1000');
        }
    }
}