force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <description>All messages for users of the mobile Donor app</description>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Indicates the date the message will expire.</description>
    <inlineHelpText>Indicates the date the message will expire.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Scheduled_Send_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Send_Time__c</fullName>
    <description>Used when a message is set to be scheduled to be sent at a certain point in time.</description>
    <inlineHelpText>Used when a message is set to be scheduled to be sent at a certain point in time.</inlineHelpText>
    <label>Scheduled Send Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Any optionally associated Visit related to the message</description>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BroadcastActionInvocable.cls
/**
 * Created by joshlequire1 on 3/13/23.
 */

public class BroadcastActionInvocable {

    @InvocableMethod(Label='Execute Broadcast Action' Category='Donor' Description='Takes the message configuration from the flow and produces outputs for interaction and messaging.')
    public static List<BroadcastActionResponse> executeBroadcastAction(List<List<BroadcastActionInvocableVariable>> messageConfiguration) {
        BroadcastActionInvocableVariable sendConfiguration = new BroadcastActionInvocableVariable();
        List<BroadcastActionInvocableVariable> messageConfigurationList = messageConfiguration[0];
        sendConfiguration = messageConfigurationList[0];
        Set<String> userIds = new Set<String>();
        List<Message__c> messagesToSend = new List<Message__c>();
        BroadcastActionResponse barOutputToFlow = new BroadcastActionResponse();
        List<BroadcastActionResponse> sendBarsToFlow = new List<BroadcastActionResponse>();
        String messageContent;

        if (sendConfiguration.MessageType == 'Center Closure') {
            messageContent = 'This center will be closed during the following times: ' +
                'Closure Start: ' + String.valueOf(sendConfiguration.ClosureStartDatetime.month()) + '-' + String.valueOf(sendConfiguration.ClosureStartDatetime.day()) + '-' + String.valueOf(sendConfiguration.ClosureStartDatetime.year()) + ' ' + String.valueOf(sendConfiguration.ClosureStartDatetime.hour()) + ':' + minuteHelper(sendConfiguration.ClosureStartDatetime) + ', Closure End: ' + String.valueOf(sendConfiguration.ReopenDatetime.month()) + '-' + String.valueOf(sendConfiguration.ReopenDatetime.day()) + ' ' + String.valueOf(sendConfiguration.ReopenDatetime.hour()) + ':' + minuteHelper(sendConfiguration.ReopenDatetime);
            messageContent = messageContent + '. ' + String.valueOf(sendConfiguration.MessageContent);
        } else {
            messageContent = String.valueOf(sendConfiguration.MessageContent);
        }

        if (sendConfiguration.Audience == 'All Donors for Center') {
            for (User usr : [SELECT Id, ContactId FROM User WHERE ContactId IN (SELECT ContactId FROM AccountContactRelation WHERE AccountId = :sendConfiguration.CenterAccountId AND Roles = 'Donor' AND IsActive = TRUE) AND IsActive = TRUE]) {
                userIds.add(usr.Id);
                Message__c message = new Message__c();
                message.Name = String.valueOf(sendConfiguration.MessageType);
                message.Body__c = messageContent;
                message.Donor__c = usr.ContactId;
                message.Expiration_Date__c = sendConfiguration.MessageExpirationDate;
                message.Scheduled_Send_Time__c = sendConfiguration.ScheduledSendDateTime;
                messagesToSend.add(message);
            }
        } else {
            Map<Id, List<Visit__c>> contactToVisitsMap = new Map<Id, List<Visit__c>>();
            for (Visit__c visit : VisitSelector.getVisitsInDateRange(sendConfiguration.DonorScheduleStart, sendConfiguration.DonorScheduleEnd)) {
                List<Visit__c> contactVisitsForPeriod = new List<Visit__c>();
                if (contactToVisitsMap.get(visit.Donor__c) != null) {
                    contactVisitsForPeriod.addAll(contactToVisitsMap.get(visit.Donor__c));
                }
                contactVisitsForPeriod.add(visit);
                contactToVisitsMap.put(visit.Donor__c, contactVisitsForPeriod);
            }

            for (User usr : [SELECT Id, ContactId FROM User WHERE ContactId IN :contactToVisitsMap.keySet() AND IsActive = TRUE]) {
                userIds.add(usr.Id);
                for (Visit__c visit : contactToVisitsMap.get(usr.ContactId)) {
                    Message__c message = new Message__c();
                    message.Name = String.valueOf(sendConfiguration.MessageType);
                    message.Body__c = messageContent;
                    message.Donor__c = usr.ContactId;
                    message.Expiration_Date__c = sendConfiguration.MessageExpirationDate;
                    message.Scheduled_Send_Time__c = sendConfiguration.ScheduledSendDateTime;
                    message.Visit__c = visit.Id;
                    messagesToSend.add(message);
                }
            }
        }

        barOutputToFlow.donorUserIds = new List<String>(userIds);
        barOutputToFlow.donorCount = userIds.size();
        barOutputToFlow.messageRecords = messagesToSend;
        barOutputToFlow.finalMessageText = messageContent;
        sendBarsToFlow.add(barOutputToFlow);

        return sendBarsToFlow;
    }

    public class BroadcastActionResponse {
        @AuraEnabled @InvocableVariable
        public List<String> donorUserIds;

        @AuraEnabled @InvocableVariable
        public Integer donorCount;

        @AuraEnabled @InvocableVariable
        public List<Message__c> messageRecords;

        @AuraEnabled @InvocableVariable
        public String finalMessageText;
    }

    public static String minuteHelper(Datetime dt){
        String returnValue;
        if(dt.minute() == 0) {
            returnValue = '00';
        } else {
            returnValue = String.valueOf(dt);
        }
        return returnValue;
    }

}