force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <description>All messages for users of the mobile Donor app</description>
    <label>Message</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates the Center, specifically for Center related broadcast (or other) messages, to show what messages where emitted from a Center.</description>
    <inlineHelpText>Indicates the Center, specifically for Center related broadcast (or other) messages, to show what messages where emitted from a Center.</inlineHelpText>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Center Messages</relationshipLabel>
    <relationshipName>CenterMessages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>Indicates the date the message will expire.</description>
    <inlineHelpText>Indicates the date the message will expire.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/isViewed__c.field-meta.xml
<CustomField>
    <fullName>isViewed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the recipient viewed this message?</description>
    <label>is Viewed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Viewed_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Datetime__c</fullName>
    <description>The datetime this message was viewed</description>
    <label>Viewed Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/NotificationsController.cls
public without sharing class NotificationsController {

    @AuraEnabled
    public static Boolean hasUnreadNotifications() {
        Integer unreadNotificationCount = 0;

        try {
            unreadNotificationCount = [
                SELECT COUNT()
                FROM Message__c
                WHERE Donor__c IN (SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()) AND
                    isViewed__c = false AND
                    Viewed_Datetime__c = null
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return (unreadNotificationCount > 0);
    }

    @AuraEnabled
    public static List<Notification> getNotifications(Id centerId) {
        try {
            Util.testExceptionHandling();

            List<Message__c> messages;

            // If center is not specified, get donor messages.
            if (centerId == null) {
                User user = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId()];

                messages = [
                    SELECT
                        Name, Body__c
                    FROM
                        Message__c
                    WHERE
                        Donor__c = :user.ContactId
                    AND
                        (Expiration_Date__c = null OR Expiration_Date__c > :Date.today())
                    ORDER BY
                        CreatedDate DESC
                ];
            }

            // Else get center messages.
            else {
                messages = [
                    SELECT
                        Name, Body__c
                    FROM
                        Message__c
                    WHERE
                        Center__c = :centerId
                    AND
                        (Expiration_Date__c = null OR Expiration_Date__c > :Date.today())
                    ORDER BY
                        CreatedDate DESC
                ];
            }

            List<Notification> notifications = new List<Notification>();

            for (Message__c message : messages) {
                Notification notification = new Notification();
                notification.id = message.Id;
                notification.subject = message.Name;
                notification.body = message.Body__c;
                notifications.add(notification);
            }

            return notifications;
        } catch (Exception e) {
            throw Util.createAuraHandledException(e);
        }
    }

    @AuraEnabled
    public static Notification viewNotification(Id notificationId) {
        try {
            Util.testExceptionHandling();

            Message__c message = [
                SELECT
                    Name, Body__c, Viewed_Datetime__c
                FROM
                    Message__c
                WHERE
                    Id = :notificationId
            ];

            if (message.Viewed_Datetime__c == null) {
                message.isViewed__c = true;
                message.Viewed_Datetime__c = DateTime.now();
                update message;
            }

            Notification notification = new Notification();
            notification.id = message.Id;
            notification.subject = message.Name;
            notification.body = message.Body__c;

            return notification;
        } catch (Exception e) {
            throw Util.createAuraHandledException(e);
        }
    }


    public class Notification {

        @AuraEnabled
        public Id id {get; set;}

        @AuraEnabled
        public String subject {get; set;}

        @AuraEnabled
        public String body {get; set;}

    }

}