force-app/main/default/objects/Consent_Transaction__c/Consent_Transaction__c.object-meta.xml
<CustomObject>
    <description>Tracks the instances where a Constituent (Lead or Contact / Person Account) opts in or out of marketing communications, for regulatory compliance and honoring privacy preferences.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consent_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact to which this Consent Transaction relates.</description>
    <inlineHelpText>The Contact to which this Consent Transaction relates.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>Consent_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent_Transaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Lead to which this Consent Transaction relates.</description>
    <inlineHelpText>The Lead to which this Consent Transaction relates.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>Consent_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent_Transaction__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the general source where this Consent Transaction originated.</description>
    <inlineHelpText>Indicates the general source where this Consent Transaction originated.</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Web Form</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Mobile Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Consent_Transaction__c/fields/Type_of_Consent__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Consent__c</fullName>
    <description>Indicates the nature of the consent - if someone opted in or out.</description>
    <inlineHelpText>Indicates the nature of the consent - if someone opted in or out.</inlineHelpText>
    <label>Type of Consent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-in</fullName>
            </value>
            <value>
                <fullName>Opt-out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
/**
 * Created by joshlequire1 on 2/28/23.
 */
@IsTest
public with sharing class LeadTriggerHandlerTest {
    @IsTest
    static void testConsentTransactionBehavior() {
        Test.startTest();
        Lead testLead = new Lead(FirstName = 'Test', LastName = 'Lead');
        insert testLead;

        List<Consent_Transaction__c> testConsents = new List<Consent_Transaction__c>{
                new Consent_Transaction__c(
                        Lead__c = testLead.Id,
                        Source__c = 'Agent',
                        Type_of_Consent__c = 'Opt-in'
                ),
                new Consent_Transaction__c(
                        Lead__c = testLead.Id,
                        Source__c = 'Web Form',
                        Type_of_Consent__c = 'Opt-out'
                )
        };

        insert testConsents;

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(testLead.Id);
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = TRUE LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);

        Test.stopTest();

        Lead convertedLead = [SELECT Id, ConvertedContactId FROM Lead WHERE IsConverted = TRUE][0];

        for (Consent_Transaction__c ct : [SELECT Id, Lead__c, Contact__c FROM Consent_Transaction__c WHERE Contact__c != NULL]) {
            Assert.areEqual(convertedLead.ConvertedContactId, ct.Contact__c);
        }

    }

}