force-app/main/default/objects/Consent_Transaction__c/Consent_Transaction__c.object-meta.xml
<CustomObject>
    <description>Tracks the instances where a Constituent (Lead or Contact / Person Account) opts in or out of marketing communications, for regulatory compliance and honoring privacy preferences.</description>
    <label>Consent Transaction</label>
    <nameField>
        <displayFormat>CT-{00000000}</displayFormat>
        <label>Consent Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consent Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consent_Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact to which this Consent Transaction relates.</description>
    <inlineHelpText>The Contact to which this Consent Transaction relates.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>Consent_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consent_Transaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Lead to which this Consent Transaction relates.</description>
    <inlineHelpText>The Lead to which this Consent Transaction relates.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Consent Transactions</relationshipLabel>
    <relationshipName>Consent_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
/**
 * Created by joshlequire1 on 2/28/23.
 */

public with sharing class LeadTriggerHandler extends TriggerFactory.BaseHandler {
    public static Boolean bypassTrigger = false;

    public override void afterUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        if (bypassTrigger) {
            return;
        }

        Set<Id> convertedLeadIds = getConvertedLeadIds((Map<Id, Lead>) oldMap, (Map<Id, Lead>) newMap);

        if (!convertedLeadIds.isEmpty()) {
            updateConsentTransactionLinksOnConversion((Map<Id, Lead>) newMap, convertedLeadIds);
        }
    }

    private static Set<Id> getConvertedLeadIds(Map<Id, Lead> oldLeadMap, Map<Id, Lead> newLeadMap) {
        Set<Id> convertedLeadIds = new Set<Id>();

        for (Lead ld : newLeadMap.values()) {
            if (ld.IsConverted && ld.IsConverted != oldLeadMap.get(ld.Id).IsConverted) {
                convertedLeadIds.add(ld.Id);
            }
        }
        return convertedLeadIds;
    }

    public static void updateConsentTransactionLinksOnConversion(Map<Id, Lead> newLeadMap, Set<Id> convertedLeadIds) {
        List<Consent_Transaction__c> consentTransactionsToUpdate = [SELECT Id, Lead__c, Contact__c FROM Consent_Transaction__c WHERE Lead__c IN :convertedLeadIds];

        if (!consentTransactionsToUpdate.isEmpty()) {
            List<Consent_Transaction__c> consentTransactionsUpdates = new List<Consent_Transaction__c>();
            for (Consent_Transaction__c ct : consentTransactionsToUpdate) {
                Consent_Transaction__c ctUpdate = new Consent_Transaction__c(Id = ct.Id);
                ctUpdate.Contact__c = newLeadMap.get(ct.Lead__c).ConvertedContactId;
                consentTransactionsUpdates.add(ctUpdate);
            }

            update consentTransactionsUpdates;
        }
    }
}