force-app/main/default/objects/ErrorEvent__e/ErrorEvent__e.object-meta.xml
<CustomObject>
    <description>Used to logged errors within a different transaction</description>
    <label>Error Event</label>
    <pluralLabel>Error Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ErrorEvent__e/fields/AdditionalInfo__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInfo__c</fullName>
    <description>Additional info about the error, record details, or JSON payload</description>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/LongMessage__c.field-meta.xml
<CustomField>
    <fullName>LongMessage__c</fullName>
    <description>Error Message with all the details</description>
    <label>Long Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Action or Code Area that led to the error</description>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Identifying Info of the Record (if any) that threw this error.</description>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/ShortMessage__c.field-meta.xml
<CustomField>
    <fullName>ShortMessage__c</fullName>
    <description>Short Title of the Error</description>
    <label>Short Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Message</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>ErrorLog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/AdditionalInfo__c.field-meta.xml
<CustomField>
    <fullName>AdditionalInfo__c</fullName>
    <description>Additional info about the error, record details, or JSON payload</description>
    <inlineHelpText>Additional info about the error, record details, or JSON payload</inlineHelpText>
    <label>Additional Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ErrorDate__c.field-meta.xml
<CustomField>
    <fullName>ErrorDate__c</fullName>
    <description>Date/Time where the error occurred</description>
    <inlineHelpText>Date/Time where the error occurred</inlineHelpText>
    <label>Error Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/LongMessage__c.field-meta.xml
<CustomField>
    <fullName>LongMessage__c</fullName>
    <description>Error Message with all the details</description>
    <inlineHelpText>Error Message with all the details</inlineHelpText>
    <label>Long Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Action or Code Area that led to the error</description>
    <inlineHelpText>Action or Code Area that led to the error</inlineHelpText>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Identifying Info of the Record (if any) that threw this error. May not be an id if it&apos;s an insert call</description>
    <inlineHelpText>Identifying Info of the Record (if any) that threw this error. May not be an id if it&apos;s an insert call</inlineHelpText>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ShortMessage__c.field-meta.xml
<CustomField>
    <fullName>ShortMessage__c</fullName>
    <description>Short Title of the Error</description>
    <inlineHelpText>Short Title of the Error</inlineHelpText>
    <label>Short Message</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Error Message</description>
    <inlineHelpText>Type of Error Message</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorLogService.cls
public without sharing class ErrorLogService {

    public static ErrorLog__c createErrorLog(String recordId, String origin, String type, String shortMessage, String longMessage) {
        ErrorLog__c errorLog = new ErrorLog__c();

        errorLog.RecordId__c = recordId;
        errorLog.ErrorDate__c = Datetime.now();
        errorLog.Origin__c = origin;
        errorLog.ShortMessage__c = (shortMessage.length() > 3000) ? shortMessage.substring(0, 3000) : shortMessage;
        errorLog.LongMessage__c = (longMessage.length() > 32700) ? longMessage.substring(0, 32700) : longMessage;
        errorLog.Type__c = type;

        return errorLog;
    }

    public static ErrorLog__c createErrorLogFromException(String recordId, String origin, String type, Exception e) {
        ErrorLog__c errorLog = new ErrorLog__c();

        errorLog.RecordId__c = recordId;
        errorLog.ErrorDate__c = Datetime.now();
        errorLog.Origin__c = origin;
        errorLog.ShortMessage__c = (e.getMessage().length() > 3000) ? e.getMessage().substring(0, 3000) : e.getMessage();
        errorLog.LongMessage__c = (e.getStackTraceString().length() > 32700) ? e.getStackTraceString().substring(0, 32700) : e.getStackTraceString();
        errorLog.Type__c = type;

        return errorLog;
    }


    public static void logError(String recordId, String origin, String shortMessage, String longMessage, String additionalInfo) {
        ErrorEvent__e errorEvent = new ErrorEvent__e();
        errorEvent.RecordId__c = recordId;
        errorEvent.Origin__c = origin;
        errorEvent.ShortMessage__c = (shortMessage.length() > 3000) ? shortMessage.substring(0, 3000) : shortMessage;
        errorEvent.LongMessage__c = (longMessage.length() > 32700) ? longMessage.substring(0, 32700) : longMessage;
        errorEvent.Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR;
        errorEvent.AdditionalInfo__c = additionalInfo;
        publishError(errorEvent);
    }

    public static void logErrorFromException(String recordId, String origin, Exception e, String additionalInfo) {
        ErrorEvent__e errorEvent = new ErrorEvent__e();
        errorEvent.RecordId__c = recordId;
        errorEvent.Origin__c = origin;
        errorEvent.ShortMessage__c = (e.getMessage().length() > 3000) ? e.getMessage().substring(0, 3000) : e.getMessage();
        errorEvent.LongMessage__c = (e.getStackTraceString().length() > 32700) ? e.getStackTraceString().substring(0, 32700) : e.getStackTraceString();
        errorEvent.Type__c = CONSTANTS.ERRORLOG_TYPE_ERROR;
        errorEvent.AdditionalInfo__c = additionalInfo;
        publishError(errorEvent);
    }

    private static void publishError(ErrorEvent__e ee) {
        EventBus.publish(ee);
    }

    private static ErrorLog__c createErrorLogFromErrorEvent(ErrorEvent__e ee) {
        ErrorLog__c errorLog = new ErrorLog__c();

        errorLog.RecordId__c = ee.RecordId__c;
        errorLog.ErrorDate__c = Datetime.now();
        errorLog.Origin__c = ee.Origin__c;
        errorLog.ShortMessage__c = ee.ShortMessage__c;
        errorLog.LongMessage__c = ee.LongMessage__c;
        errorLog.Type__c = ee.Type__c;
        errorLog.AdditionalInfo__c = ee.AdditionalInfo__c;
        return errorLog;
    }

    public static void writeErrorEvent(List<ErrorEvent__e> errorEvents) {
        List<ErrorLog__c> errorLogs = new List<ErrorLog__c>();
        for (ErrorEvent__e ee : errorEvents) {
            errorLogs.add(createErrorLogFromErrorEvent(ee));
        }
        insert errorLogs;
    }
}