force-app/main/default/objects/Level__c/Level__c.object-meta.xml
<CustomObject>
    <description>Loyalty tier levels</description>
    <label>Level</label>
    <nameField>
        <label>Level Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Level__c/fields/Donation_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Donation_Threshold__c</fullName>
    <description>Number of donations where Level is valid e.g. 31 means the Level applies at 31st donation.</description>
    <inlineHelpText>The donation number where this Level applies</inlineHelpText>
    <label>Donation Threshold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoyaltyLevelService.cls
public with sharing class LoyaltyLevelService {
    private static Map<Id, Integer> loyaltyLevelIdToIndex;

    public static Integer getLoyaltyLevel(Id loyaltyLevelId) {
        if (loyaltyLevelIdToIndex == null) {
            loyaltyLevelIdToIndex = new Map<Id, Integer>();

            Integer loyaltyLevelIndex = 0;
            for(Level__c loyaltyLevelRecord : [
                SELECT Id
                FROM Level__c
                ORDER BY Donation_Threshold__c ASC
            ]) {
                loyaltyLevelIdToIndex.put(loyaltyLevelRecord.Id, loyaltyLevelIndex);
                loyaltyLevelIndex += 1;
            }
        }

        return loyaltyLevelIdToIndex.get(loyaltyLevelId);
    } 
}