force-app/main/default/objects/Contact/fields/Last_Onbe_Balance_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Onbe_Balance_Update__c</fullName>
    <label>Last Onbe Balance Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Redeemed_Points__c.field-meta.xml
<CustomField>
    <fullName>Redeemed_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Redeemed Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>The payment vehicle associated with a Donor</description>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>40</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <description>The donor owner of this payment method</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>true</defaultValue>
    <label>is_Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Proesis_Wallet__c/Proesis_Wallet__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Proesis Wallet</label>
</CustomObject>

force-app/main/default/objects/Proesis_Wallet__c/fields/Points_to_Dollar__c.field-meta.xml
<CustomField>
    <fullName>Points_to_Dollar__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Represents how many points are needed for $1 USD</description>
    <label>Points to Dollar</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>The item description for this line in the transaction; user will most likely see this exact content</description>
    <inlineHelpText>The item description for this line in the transaction; user will most likely see this exact content</inlineHelpText>
    <label>Item</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>An amount of a specific item</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <description>The price paid for a unit of measure</description>
    <inlineHelpText>The price paid for a unit of measure</inlineHelpText>
    <label>Unit Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RedeemPointsController.cls
public without sharing class RedeemPointsController {
    @AuraEnabled
    public static void redeemPoints(String donorId, Decimal pointsToRedeem) {
        List<Payment_Method__c> donorPaymentMethod = [SELECT Id, Account_Number__c FROM Payment_Method__c WHERE Donor__c = :donorId AND Is_Active__c = true AND isDefault__c = true LIMIT 1];
        String accountNumber = (donorPaymentMethod != null && donorPaymentMethod.size() > 0) ? donorPaymentMethod[0].Account_Number__c : null;

        Proesis_Wallet__c proesisWallet = Proesis_Wallet__c.getOrgDefaults();
        Decimal pointsToDollars = (proesisWallet.Points_to_Dollar__c != null) ? proesisWallet.Points_to_Dollar__c : 100;
        Decimal dollorsToCredit = Math.round(pointsToRedeem / pointsToDollars);
        Decimal roundedPointsToRedeem = dollorsToCredit * pointsToDollars;
        
        // Create the initial credit transactions
        Transaction__c creditTransaction = new Transaction__c(Donor__c = donorId, Type__c = 'Credit', SubType__c = 'Point Redemption', Status__c = 'Complete');
        insert creditTransaction;

        List<Txn_Line_Item__c> transactionLineItems = new List<Txn_Line_Item__c>();
        transactionLineItems.add(new Txn_Line_Item__c(
            Transaction__c = creditTransaction.Id, 
            Type__c = 'Currency', 
            Unit_Cost__c = dollorsToCredit,
            Quantity__c = 1,
            Item__c = 'PlasmaPoints Redeemed'
        ));
        insert transactionLineItems;

        // Update points redeemed on the donor contact's record
        Contact targetContact;
        try {
            targetContact = [SELECT Id, Redeemed_Points__c, Last_Onbe_Balance_Update__c FROM Contact WHERE Id = :donorId LIMIT 1];
        } catch(Exception e) {
            System.debug(e);
            throw new AuraHandledException('Unable to find donor contact');
        }

        targetContact.Redeemed_Points__c = (targetContact.Redeemed_Points__c != null) ? targetContact.Redeemed_Points__c + roundedPointsToRedeem : roundedPointsToRedeem;
        targetContact.Last_Onbe_Balance_Update__c = null;
        update targetContact;

        // Queue up the addFunds callout to Onbe
        List<DonorCompInvocable.AddFundsRequest> addFundsRequests = new List<DonorCompInvocable.AddFundsRequest>();

        DonorCompInvocable.AddFundsRequest redeemPointsRequest = new DonorCompInvocable.AddFundsRequest(donorId, null, accountNumber, 'Point Redemption');
        redeemPointsRequest.comments.add('PlasmaPoints Redeemed');
        redeemPointsRequest.addLineItem('PlasmaPoints Redeemed', 'Currency', dollorsToCredit);
        redeemPointsRequest.addLineItem('PlasmaPoints Redeemed', 'Points', roundedPointsToRedeem);

        addFundsRequests.add(redeemPointsRequest);

        Database.executeBatch(new AddFundsBatchable(addFundsRequests));
    }
}