force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Amount_Currency__c</fullName>
    <description>The amount of the transaction currency</description>
    <inlineHelpText>The amount of the transaction currency</inlineHelpText>
    <label>Amount Currency</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount_Points__c.field-meta.xml
<CustomField>
    <fullName>Amount_Points__c</fullName>
    <description>The amount in points for this transaction</description>
    <inlineHelpText>The amount in points for this transaction</inlineHelpText>
    <label>Amount Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/SubType__c.field-meta.xml
<CustomField>
    <fullName>SubType__c</fullName>
    <label>SubType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Visit__c.field-meta.xml
<CustomField>
    <fullName>Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <description>The item description for this line in the transaction; user will most likely see this exact content</description>
    <inlineHelpText>The item description for this line in the transaction; user will most likely see this exact content</inlineHelpText>
    <label>Item</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Quantity__c *  Unit_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First Donation</fullName>
            </value>
            <value>
                <fullName>Repeat Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionSelector.cls
public without sharing class TransactionSelector {
    @AuraEnabled
    public static List<DonorTransaction> getUserTransactions(){
        List<Transaction__c> transactionRecords;
        try {
            Id targetDonorId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1]?.ContactId;

            transactionRecords = [
                SELECT Id, Name, Amount_Currency__c, Amount_Points__c, CreatedDate, (SELECT Id, Item__c, Total__c, Type__c FROM Txn_Line_Items__r), Visit__c, Type__c, SubType__c 
                FROM Transaction__c 
                WHERE Donor__c = :targetDonorId AND
                    Status__c = 'Complete'
                ORDER BY CreatedDate DESC
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        List<DonorTransaction> transactionWrappers = new List<DonorTransaction>();
        Map<Id, DonorTransaction> visitIdToTransactionWrapper = new Map<Id, DonorTransaction>();

        for (Transaction__c transactionRecord : transactionRecords) {
            DonorTransaction transactionWrapper;

            if (transactionRecord.SubType__c == 'Point Redemption') {
                if (transactionRecord.Type__c == 'Credit') {
                    continue;
                }

                transactionWrapper = new DonorTransaction(transactionRecord);
                transactionWrappers.add(transactionWrapper);

                for(Txn_Line_Item__c transactionLineItemRecord : transactionRecord.Txn_Line_Items__r) {
                    if (transactionLineItemRecord.Type__c == 'Currency') {
                        transactionWrapper.addCurrency(transactionLineItemRecord);
                    } else if (transactionLineItemRecord.Type__c == 'Points') {
                        transactionWrapper.addPoints(transactionLineItemRecord);
                    }
                }
            } else {
                transactionWrapper = visitIdToTransactionWrapper.get(transactionRecord.Visit__c);

                if (transactionWrapper == null) {
                    transactionWrapper = new DonorTransaction(transactionRecord);

                    visitIdToTransactionWrapper.put(transactionRecord.Visit__c, transactionWrapper);
                    transactionWrappers.add(transactionWrapper);
                }

                for(Txn_Line_Item__c transactionLineItemRecord : transactionRecord.Txn_Line_Items__r) {
                    if (transactionLineItemRecord.Type__c == 'Currency' && transactionRecord.Type__c == 'Debit') {
                        transactionWrapper.addCurrency(transactionLineItemRecord);
                    } else if (transactionLineItemRecord.Type__c == 'Points' && transactionRecord.Type__c == 'Credit') {
                        transactionWrapper.addPoints(transactionLineItemRecord);
                    }
                }
            }
        }

        return transactionWrappers;
    }

    public class DonorTransaction {
        @AuraEnabled
        public Id transactionId;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public Decimal currencyTotal;
        @AuraEnabled
        public Decimal pointTotal;
        @AuraEnabled
        public DateTime transactionDate;
        @AuraEnabled
        public List<TransactionLineItem> transactionLineItems;

        public DonorTransaction(Transaction__c transactionRecord) {
            this.transactionId = transactionRecord.Id;
            this.name = transactionRecord.Name;
            this.transactionDate = transactionRecord.CreatedDate;

            this.currencyTotal = 0;
            this.pointTotal = 0;

            transactionLineItems = new List<TransactionLineItem>();
        }

        public void addPoints(Txn_Line_Item__c pointLineItem) {
            this.pointTotal += pointLineItem.Total__c;
            transactionLineItems.add(new TransactionLineItem(pointLineItem));
        }

        public void addCurrency(Txn_Line_Item__c currencyLineItem) {
            this.currencyTotal += currencyLineItem.Total__c;
            transactionLineItems.add(new TransactionLineItem(currencyLineItem));
        }
    }

    public class TransactionLineItem {
        @AuraEnabled
        public String itemName;
        @AuraEnabled
        public Decimal currencyTotal;
        @AuraEnabled
        public Decimal pointTotal;

        public TransactionLineItem(Txn_Line_Item__c transactionLineItemRecord) {
            this.itemName = transactionLineItemRecord.Item__c;

            if (transactionLineItemRecord.Type__c == 'Currency') {
                this.currencyTotal = transactionLineItemRecord.Total__c;
                this.pointTotal = 0;
            } else if (transactionLineItemRecord.Type__c == 'Points') {
                this.pointTotal = transactionLineItemRecord.Total__c;
                this.currencyTotal = 0;
            }
        }
    }
}