force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddFundsBatchable.cls
public without sharing class AddFundsBatchable implements Database.Batchable<DonorCompInvocable.AddFundsRequest>, Database.AllowsCallouts {
    List<DonorCompInvocable.AddFundsRequest> addFundRequests;

    public AddFundsBatchable(List<DonorCompInvocable.AddFundsRequest> addFundRequests) {
        this.addFundRequests = addFundRequests;
    }

    public Iterable<DonorCompInvocable.AddFundsRequest> start(Database.BatchableContext bc) {
        return this.addFundRequests;
    }

    public void execute(Database.BatchableContext info, List<DonorCompInvocable.AddFundsRequest> scope) {
        Map<DonorCompInvocable.AddFundsRequest, Transaction__c> debitTransactions = AddFundsBatchableHelper.createDebitTransactions(scope);
        Map<DonorCompInvocable.AddFundsRequest, Txn_Line_Item__c> transactionLineItems = AddFundsBatchableHelper.createDebitTransactionLineItems(
            new List<DonorCompInvocable.AddFundsRequest>(debitTransactions.keySet())
        );

        AddFundsBatchableHelper.processAddFundsCallouts(new List<DonorCompInvocable.AddFundsRequest>(debitTransactions.keySet()));
        AddFundsBatchableHelper.handleAddFundsResponses(debitTransactions, transactionLineItems);
    }

    public void finish(Database.BatchableContext bc) { }
}