force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <description>The number of retries attempted to process this transaction</description>
    <inlineHelpText>The number of retries attempted to process this transaction</inlineHelpText>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Retry_Next__c.field-meta.xml
<CustomField>
    <fullName>Retry_Next__c</fullName>
    <description>Datetime of next retry time</description>
    <inlineHelpText>Datetime of next retry time</inlineHelpText>
    <label>Retry Next</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Was_Manually_Processed__c.field-meta.xml
<CustomField>
    <fullName>Was_Manually_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the payment was processed outside of Salesforce and should not be processed.</description>
    <label>Was Manually Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TransactionActionController.cls
public without sharing class TransactionActionController {
    @AuraEnabled
    public static Transaction__c markTransactionForRetry(Id transactionId) {
        Transaction__c transactionToRetry = new Transaction__c(
            Id = transactionId,
            Retry_Count__c = 0,
            Retry_Next__c = null
        );

        try {
            update transactionToRetry;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        if (AddFundsBatchable.getScheduledRetryJobInstanceCount() == 0) {
            AddFundsBatchable.scheduledRetryRun();
        }

        return transactionToRetry;
    }

    @AuraEnabled
    public static Transaction__c markTransactionAsManualPayment(Id transactionId) {
        Transaction__c manualTransaction = new Transaction__c(
            Id = transactionId,
            Was_Manually_Processed__c = true,
            Status__c = 'Complete'
        );
        
        try {
            update manualTransaction;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

        return manualTransaction;
    }
}