force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <description>The number of retries attempted to process this transaction</description>
    <inlineHelpText>The number of retries attempted to process this transaction</inlineHelpText>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Retry_Next__c.field-meta.xml
<CustomField>
    <fullName>Retry_Next__c</fullName>
    <description>Datetime of next retry time</description>
    <inlineHelpText>Datetime of next retry time</inlineHelpText>
    <label>Retry Next</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Was_Manually_Processed__c.field-meta.xml
<CustomField>
    <fullName>Was_Manually_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the payment was processed outside of Salesforce and should not be processed.</description>
    <label>Was Manually Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TransactionActionControllerTest.cls
@IsTest
public without sharing class TransactionActionControllerTest {
    @TestSetup
    static void createTestData() {
        Account testDonorAccount = TestUtil.createDonor('123-456');
        insert testDonorAccount;

        Id testDonorContactId = [SELECT PersonContactId FROM Account WHERE Id = :testDonorAccount.Id].PersonContactId;
        Transaction__c testTransaction = new Transaction__c(
            Donor__c = testDonorContactId,
            Status__c = 'Error',
            Retry_Count__c = 5, 
            Retry_Next__c = System.now().addMinutes(5),
            Was_Manually_Processed__c = false
        );
        insert testTransaction;
    }

    @IsTest
    public static void testMarkTransactionForRetry() {
        Transaction__c testTransaction = [SELECT Id, Status__c, Retry_Count__c, Retry_Next__c FROM Transaction__c LIMIT 1];
        Transaction__c updatedTransaction;

        Test.startTest();
        updatedTransaction = TransactionActionController.markTransactionForRetry(testTransaction.Id);
        Test.stopTest();

        Assert.areEqual(testTransaction.Id, updatedTransaction.Id, 'The correct transaction was returned from the quick action');
        Assert.areEqual(0, updatedTransaction.Retry_Count__c, 'The retry count was reset to 0');
        Assert.isNull(updatedTransaction.Retry_Next__c, 'The retry next date was reset to null');
    }

    @IsTest 
    public static void testMarkTransactionAsManualPayment() {
        Transaction__c testTransaction = [SELECT Id, Status__c, Was_Manually_Processed__c FROM Transaction__c LIMIT 1];
        Transaction__c updatedTransaction;

        Test.startTest();
        updatedTransaction = TransactionActionController.markTransactionAsManualPayment(testTransaction.Id);
        Test.stopTest();

        Assert.areEqual(testTransaction.Id, updatedTransaction.Id, 'The correct transaction was returned from the quick action');
        Assert.isTrue(updatedTransaction.Was_Manually_Processed__c, 'The transaction was marked as manually processed');
        Assert.areEqual('Complete', updatedTransaction.Status__c, 'The transaction Status was updated to Complete');
    }
}