force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <description>All related credits and debits for a Donor</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000}</displayFormat>
        <label>Transaction #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Amount_Currency__c</fullName>
    <description>The amount of the transaction currency</description>
    <inlineHelpText>The amount of the transaction currency</inlineHelpText>
    <label>Amount Currency</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Amount_Points__c.field-meta.xml
<CustomField>
    <fullName>Amount_Points__c</fullName>
    <description>The amount in points for this transaction</description>
    <inlineHelpText>The amount in points for this transaction</inlineHelpText>
    <label>Amount Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/Txn_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Line Items that make up a total for a parent Transaction</description>
    <label>Txn Line Item</label>
    <nameField>
        <displayFormat>TLI-{0}</displayFormat>
        <label>Txn Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Txn Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Txn_Line_Item__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Quantity__c *  Unit_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Parent transaction</description>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Txn Line Items</relationshipLabel>
    <relationshipName>Txn_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Txn_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Points</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TxnLineItemTriggerHandler.cls
public without sharing class TxnLineItemTriggerHandler extends TriggerFactory.BaseHandler {
    public override void beforeInsert(List<SObject> newList) {
        rollupTxnLineItemFields((List<Txn_Line_Item__c>) newList);
    }
    
    public override void beforeUpdate(Map<Id, SObject> oldMap, Map<Id, SObject> newMap) {
        rollupTxnLineItemFields((List<Txn_Line_Item__c>) newMap.values());
    }

    public void rollupTxnLineItemFields(List<Txn_Line_Item__c> lineItems) {
        // If Txn_Line_Item__c.Type__c = 'Currency' then add Txn_Line_Item__c.Total__c to Txn_Line_Item__c.Transaction__r.Amount_Currency__c field
        // If Txn_Line_Item__c.Type__c = 'Points' then add Txn_Line_Item__c.Total__c to Txn_Line_Item__c.Transaction__r.Amount_Points__c field

        Map<Id, Decimal> currencyMap = new Map<Id, Decimal>();
        Map<Id, Decimal> pointsMap = new Map<Id, Decimal>();

        for (Txn_Line_Item__c lineItem : lineItems) {
            if (lineItem.Type__c == 'Currency') {
                if (currencyMap.containsKey(lineItem.Transaction__c)) {
                    currencyMap.put(lineItem.Transaction__c, currencyMap.get(lineItem.Transaction__c) + lineItem.Total__c);
                } else {
                    currencyMap.put(lineItem.Transaction__c, lineItem.Total__c);
                }
            } else if (lineItem.Type__c == 'Points') {
                if (pointsMap.containsKey(lineItem.Transaction__c)) {
                    pointsMap.put(lineItem.Transaction__c, pointsMap.get(lineItem.Transaction__c) + lineItem.Total__c);
                } else {
                    pointsMap.put(lineItem.Transaction__c, lineItem.Total__c);
                }
            }
        }

        Map<Id, Transaction__c> transactions = new Map<Id, Transaction__c>();
        for (Id transactionId : currencyMap.keySet()) {
            Transaction__c txnRecord = transactions.get(transactionId);
            if (txnRecord == null) {
                txnRecord = new Transaction__c(Id = transactionId);
            }

            txnRecord.Amount_Currency__c = currencyMap.get(transactionId);
            transactions.put(transactionId, txnRecord);
        }

        for (Id transactionId : pointsMap.keySet()) {
            Transaction__c txnRecord = transactions.get(transactionId);
            if (txnRecord == null) {
                txnRecord = new Transaction__c(Id = transactionId);
            }

            txnRecord.Amount_Points__c = pointsMap.get(transactionId);
            transactions.put(transactionId, txnRecord);
        }

        update transactions.values();
    }
}