force-app/main/default/objects/Donor_CheckIn__e/Donor_CheckIn__e.object-meta.xml
<CustomObject>
    <description>Donor is qualified to begin donation</description>
    <label>Donor CheckIn</label>
    <pluralLabel>Donor CheckIns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_CheckIn__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The datetime of this event</description>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/Donor_Comp__e.object-meta.xml
<CustomObject>
    <description>The last donation step in the donation process typically indicating payment is owed.</description>
    <label>Donor Comp</label>
    <pluralLabel>Donor Comps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Donor_Comp__e/fields/BECS_Device__c.field-meta.xml
<CustomField>
    <fullName>BECS_Device__c</fullName>
    <description>Serial number of BECS machine</description>
    <label>BECS Device</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Number__c.field-meta.xml
<CustomField>
    <fullName>Collection_Number__c</fullName>
    <description>Unique donation collection identifier.</description>
    <label>Collection Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Collection_Volume__c.field-meta.xml
<CustomField>
    <fullName>Collection_Volume__c</fullName>
    <description>The volume in milliliters (ml or cc) of the donation collected.</description>
    <label>Collection Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/Donor_Number__c.field-meta.xml
<CustomField>
    <fullName>Donor_Number__c</fullName>
    <label>Donor Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donor_Comp__e/fields/hasException__c.field-meta.xml
<CustomField>
    <fullName>hasException__c</fullName>
    <description>Indicates with 1 or 0 (from Haemonetics NL integration) true or false, respectively.</description>
    <label>Has Exception</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

dx-scripts/apex/checkin_complete_visit.cls
String targetDonor = 'UZD-3HH';
Datetime targetDatetime = Datetime.newInstance(2023, 6, 3, 17, 0, 0);

DonorCheckinInvocable.updateVisitStatus(new List<List<Donor_CheckIn__e>> {
    new List<Donor_CheckIn__e> {
        new Donor_CheckIn__e(
        	Donor_Number__c = targetDonor,
    		Timestamp__c = targetDatetime
        )
    }
});

DonorCompInvocable.handleDonorCompEvent(new List<List<Donor_Comp__e>> {
    new List<Donor_Comp__e> {
        new Donor_Comp__e(
        	Donor_Number__c = targetDonor,
    		hasException__c = 0,
    		Collection_Number__c = 'c1234567890',
    		Collection_Volume__c = 1233,
    		BECS_Device__c = '123456789',
    		Timestamp__c = targetDatetime
        )
    }
});