force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <description>Capacity - Booked</description>
    <formula>Capacity__c - Booked__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The available Appointment slots</inlineHelpText>
    <label>Availability</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Booked__c.field-meta.xml
<CustomField>
    <fullName>Booked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of Visits booked into this Appointment slot. Will be updated by the API for scheduling a Visit.</description>
    <label>Booked</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The number of Appointments available at a given time slot.</description>
    <label>Capacity</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Soonest_Next_Visit__c.field-meta.xml
<CustomField>
    <fullName>Soonest_Next_Visit__c</fullName>
    <description>The earliest another Visit can be scheduled after the last Donation.</description>
    <formula>FROMUNIXTIME( 
MAX ( 
    UNIXTIMESTAMP(  Eligibility_Date__c   ),
    UNIXTIMESTAMP(  BLANKVALUE( Next_Visit_Option_48hr__c, Eligibility_Date__c ) ),
    UNIXTIMESTAMP(  BLANKVALUE( Next_Visit_Option_7d__c, Eligibility_Date__c ) )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The earliest another Visit can be scheduled after the last Donation. The greater of Eligibility Date, 48h and 7d rules.</inlineHelpText>
    <label>Soonest Next Visit</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Rescheduled_Visit__c.field-meta.xml
<CustomField>
    <fullName>Rescheduled_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This refers to the new Visit created when an existing Visit is rescheduled.</description>
    <label>Rescheduled Visit</label>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Rescheduled Visits</relationshipLabel>
    <relationshipName>Rescheduled_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <formula>Appointment__r.Schedule__r.Name</formula>
    <label>Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CoreSchedulerHandlerTest.cls
@IsTest
public class CoreSchedulerHandlerTest {
    final static Integer AMOUNT_OF_DONORS = 50;
    final static Integer BASE_CAPACITY = 2;

    @TestSetup
    static void createTestData() {
        Account centerAccount = TestUtil.createMiramarCenter();
        insert centerAccount;

        Center_Donation_Type__c testCenterDonationType = TestUtil.createCenterDonationType(centerAccount.Id);
        insert testCenterDonationType;

        Datetime testDateTime = Datetime.now();
        Schedule__c testSchedule = TestUtil.createTestSchedule(centerAccount.Id, testDateTime);
        insert testSchedule;

        List<Account> donors = new List<Account>();
        List<Appointment__c> appointments = new List<Appointment__c>();

        Datetime currentDatetime = testDateTime;
        for (Integer i = 0; i < AMOUNT_OF_DONORS; i++) {
            donors.add(TestUtil.createDonor(String.valueOf(i)));

            Appointment__c testAppointment = TestUtil.createTestAppointment(testSchedule.Id, currentDatetime);
            testAppointment.Capacity__c = BASE_CAPACITY;

            appointments.add(testAppointment);
            currentDatetime = testDateTime.addDays(1);
        }

        // Add one more appointment to allow shifting while rescheduling
        appointments.add(TestUtil.createTestAppointment(testSchedule.Id, currentDatetime));

        insert donors;
        insert appointments;
    }

    @IsTest 
    static void testRescheduleVisit() {
        List<Appointment__c> targetAppointments = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 2];
        Contact targetDonor = [SELECT Id FROM Contact LIMIT 1];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        Visit__c testVisit = new Visit__c(
            Appointment__c = targetAppointments[0].Id,
            Donor__c = targetDonor.Id,
            Center_Donation_Type__c = targetCenterDonationType.Id,
            Status__c = 'Scheduled'
        );
        insert testVisit;

        Test.startTest();
        CoreSchedulerHandler.rescheduleVisit(new CoreSchedulerHandler.RescheduleRequest(
            testVisit.Id,    
            targetAppointments[1].Id
        ));
        Test.stopTest();

        Visit__c updatedOriginalVisit = [SELECT Id, Status__c, Outcome__c FROM Visit__c WHERE Id = :testVisit.Id LIMIT 1];
        Assert.areEqual('Complete', updatedOriginalVisit.Status__c, 'Original visit should be marked as complete.');
        Assert.areEqual('Rescheduled', updatedOriginalVisit.Outcome__c, 'Original visit should be marked as rescheduled.');

        Visit__c newRescheduledVisit = [SELECT Id, Status__c FROM Visit__c WHERE Appointment__c = :targetAppointments[1].Id LIMIT 1];
        Assert.areEqual('Scheduled', newRescheduledVisit.Status__c, 'New visit should be marked as scheduled.');
    }

    @IsTest
    static void testRescheduleVisits() {
        List<Appointment__c> targetAppointments = [SELECT Id FROM Appointment__c ORDER BY Datetime__c ASC];
        List<Contact> targetDonors = [SELECT Id FROM Contact];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        List<Visit__c> originalVisits = new List<Visit__c>();
        Integer visitCounter = 0;

        for(Contact targetDonor : targetDonors) {
            originalVisits.add(new Visit__c(
                Appointment__c = targetAppointments[visitCounter++].Id,
                Donor__c = targetDonor.Id,
                Center_Donation_Type__c = targetCenterDonationType.Id,
                Status__c = 'Scheduled'
            ));
        }
        insert originalVisits;

        Map<Id, CoreSchedulerHandler.RescheduleRequest> rescheduleRequests = new Map<Id, CoreSchedulerHandler.RescheduleRequest>();

        for (Integer i = 0; i < originalVisits.size(); i++) {
            rescheduleRequests.put(originalVisits[i].Id, new CoreSchedulerHandler.RescheduleRequest(
                originalVisits[i].Id,
                targetAppointments[i + 1].Id
            ));
        }

        Test.startTest();
        CoreSchedulerHandler.rescheduleVisits(new CoreSchedulerHandler.RescheduleBatchRequest(rescheduleRequests.values()));
        Test.stopTest();

        List<Visit__c> updatedOriginalVisits = [SELECT Id, Status__c, Outcome__c FROM Visit__c WHERE Id IN :originalVisits];
        for (Visit__c updatedOriginalVisit : updatedOriginalVisits) {
            Assert.areEqual('Complete', updatedOriginalVisit.Status__c, 'Original visit should be marked as complete.');
            Assert.areEqual('Rescheduled', updatedOriginalVisit.Outcome__c, 'Original visit should be marked as rescheduled.');
        }

        List<Visit__c> newRescheduledVisits = [SELECT Id, Status__c, Rescheduled_Visit__c FROM Visit__c WHERE Appointment__c IN :targetAppointments AND Id NOT IN :originalVisits];
        Assert.areEqual(originalVisits.size(), newRescheduledVisits.size(), 'There should be the same amount of new visits as there were original visits.');

        for (Visit__c newRescheduledVisit : newRescheduledVisits) {
            Assert.areEqual('Scheduled', newRescheduledVisit.Status__c, 'New visit should be marked as scheduled.');
            Assert.isNotNull(newRescheduledVisit.Rescheduled_Visit__c, 'New visit should have a reference to an old visit');
            
            CoreSchedulerHandler.RescheduleRequest rescheduleRequest = rescheduleRequests.get(newRescheduledVisit.Rescheduled_Visit__c);
            Assert.areEqual(rescheduleRequest.originalVisitId, newRescheduledVisit.Rescheduled_Visit__c, 'New visit should have a reference to the old visit');
        }
    }

    @IsTest 
    static void testCreateVisit() {
        List<Appointment__c> targetAppointments = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];
        Contact targetDonor = [SELECT Id FROM Contact LIMIT 1];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        Visit__c createdVisit, testVisit = new Visit__c(
            Appointment__c = targetAppointments[0].Id,
            Donor__c = targetDonor.Id,
            Center_Donation_Type__c = targetCenterDonationType.Id,
            Status__c = 'Scheduled'
        );

        Test.startTest();
        createdVisit = CoreSchedulerHandler.createVisit(testVisit);
        Test.stopTest();

        Assert.isNotNull(createdVisit.Id, 'Visit should be created.');

        List<Appointment__c> updatedAppointments = [SELECT Id, Booked__c, Availability__c FROM Appointment__c WHERE Id IN :targetAppointments];
        Assert.areEqual(1, updatedAppointments[0].Booked__c, 'Appointment should be marked as booked.');
        Assert.areEqual(BASE_CAPACITY - 1, updatedAppointments[0].Availability__c, 'Appointment should have ' + (BASE_CAPACITY - 1) + ' available slot.');
    }

    @IsTest 
    static void testCreateVisits() {
        List<Appointment__c> targetAppointments = [SELECT Id, Datetime__c FROM Appointment__c];
        List<Contact> targetDonors = [SELECT Id FROM Contact];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        List<Visit__c> testVisits = new List<Visit__c>();
        Set<Id> bookedAppointmentsSlots = new Set<Id>();

        for (Integer i = 0; i < targetDonors.size(); i++) {
            testVisits.add(new Visit__c(
                Appointment__c = targetAppointments[i].Id,
                Donor__c = targetDonors[i].Id,
                Center_Donation_Type__c = targetCenterDonationType.Id,
                Status__c = 'Scheduled'
            ));

            bookedAppointmentsSlots.add(targetAppointments[i].Id);
        }

        Test.startTest();
        CoreSchedulerHandler.createVisits(testVisits);
        Test.stopTest();

        List<Visit__c> createdVisits = [SELECT Id FROM Visit__c WHERE Appointment__c IN :bookedAppointmentsSlots];
        Assert.areEqual(testVisits.size(), createdVisits.size(), 'There should be the same amount of created visits as there were test visits.');

        List<Appointment__c> updatedAppointments = [SELECT Id, Booked__c, Availability__c, Capacity__c FROM Appointment__c WHERE Id IN :bookedAppointmentsSlots];
        for (Appointment__c updatedAppointment : updatedAppointments) {
            Assert.areEqual(1, updatedAppointment.Booked__c, 'Appointment should be marked as booked.');
            Assert.areEqual(updatedAppointment.Capacity__c - 1, updatedAppointment.Availability__c, 'Appointment should have ' + (updatedAppointment.Capacity__c - 1) + ' available slot.');
        }
    }

    @IsTest 
    static void testCancelVisit() {
        Appointment__c targetAppointment = [SELECT Id, Datetime__c FROM Appointment__c LIMIT 1];
        Contact targetDonor = [SELECT Id FROM Contact LIMIT 1];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        Visit__c testVisit = CoreSchedulerHandler.createVisit(new Visit__c(
            Appointment__c = targetAppointment.Id,
            Donor__c = targetDonor.Id,
            Center_Donation_Type__c = targetCenterDonationType.Id,
            Status__c = 'Scheduled'
        ));

        Test.startTest();
        CoreSchedulerHandler.cancelVisit(testVisit.Id);
        Test.stopTest();

        Visit__c canceledVisit = [SELECT Id, Status__c, Outcome__c FROM Visit__c WHERE Id = :testVisit.Id LIMIT 1];
        Assert.areEqual('Complete', canceledVisit.Status__c, 'Visit status should be marked as complete.');
        Assert.areEqual('Canceled', canceledVisit.Outcome__c, 'Visit outcome should be marked as canceled.');

        targetAppointment = [SELECT Id, Booked__c FROM Appointment__c WHERE Id = :testVisit.Appointment__c LIMIT 1];
        Assert.areEqual(0, targetAppointment.Booked__c, 'Appointment should be marked as not booked.');
    }

    @IsTest 
    static void testCancelVisits() {
        List<Appointment__c> targetAppointments = [SELECT Id, Datetime__c FROM Appointment__c];
        List<Contact> targetDonors = [SELECT Id FROM Contact];
        Center_Donation_Type__c targetCenterDonationType = [SELECT Id FROM Center_Donation_Type__c LIMIT 1];

        List<Visit__c> testVisits = new List<Visit__c>();
        Set<Id> bookedAppointmentsSlots = new Set<Id>();

        for (Integer i = 0; i < targetDonors.size(); i++) {
            testVisits.add(new Visit__c(
                Appointment__c = targetAppointments[i].Id,
                Donor__c = targetDonors[i].Id,
                Center_Donation_Type__c = targetCenterDonationType.Id,
                Status__c = 'Scheduled'
            ));

            bookedAppointmentsSlots.add(targetAppointments[i].Id);
        }

        CoreSchedulerHandler.createVisits(testVisits);

        List<Id> createdVisitIds = new List<Id>();
        for (Visit__c testVisit : testVisits) {
            createdVisitIds.add(testVisit.Id);
        }

        Test.startTest();
        CoreSchedulerHandler.cancelVisits(createdVisitIds);
        Test.stopTest();

        for(Visit__c testVisit : [SELECT Id, Status__c, Outcome__c FROM Visit__c WHERE Id IN :createdVisitIds]) {
            Assert.areEqual('Complete', testVisit.Status__c, 'Visit status should be marked as complete.');
            Assert.areEqual('Canceled', testVisit.Outcome__c, 'Visit outcome should be marked as canceled.');
        }

        for (Appointment__c updatedAppointment : [SELECT Id, Booked__c FROM Appointment__c WHERE Id IN :bookedAppointmentsSlots]) {
            Assert.areEqual(0, updatedAppointment.Booked__c, 'Appointment should be marked as booked.');
        }
    }

    @IsTest
    static void testGetSoonestNextRescheduleVisitDate() {
        // Contact targetDonor = [SELECT Id, Soonest_Next_Visit__c FROM Contact WHERE Soonest_Next_Visit__c != null LIMIT 1];
        // Datetime returnedSoonestNextVisitDate;

        // Test.startTest();
        // System.runAs(TestUtil.createAdminUser()) {
        //     returnedSoonestNextVisitDate = CoreSchedulerHandler.getSoonestNextRescheduleVisitDate(targetDonor.Id);
        // }
        // Test.stopTest();

        // Assert.areEqual(targetDonor.Soonest_Next_Visit__c, returnedSoonestNextVisitDate, 'The soonest next visit date should be returned');
    }
}