force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Center_Donation_Type__c/Center_Donation_Type__c.object-meta.xml
<CustomObject>
    <description>The types of Donations supported by a Center</description>
    <label>Center Donation Type</label>
    <nameField>
        <displayFormat>CDT-{0}</displayFormat>
        <label>Center Donation Type Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Donation Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>PII;HIPAA</complianceGroup>
    <description>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</description>
    <inlineHelpText>New: Transient state when record is first created
Registered: Are in the system as a potential donor
Verified: Has filled out basic profile information and have passed initial criteria
Applicant: Has an appointment to assess their fitness for donation
Eligible: Has met all criteria for donation and Eligiblity datetime is today or in the past
Deferred: Has met all critieria for donation and Eligibility datetime is in the future
Excluded: Can never* give plasma for various reasons that are PHI</inlineHelpText>
    <label>Status</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Donor_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Appointment_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Datetime__c</fullName>
    <description>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</description>
    <inlineHelpText>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</inlineHelpText>
    <label>Appointment Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Center_Donation_Type__c.field-meta.xml
<CustomField>
    <fullName>Center_Donation_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Center Donation Type associated with this Visit</description>
    <label>Center Donation Type</label>
    <referenceTo>Center_Donation_Type__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>The result of the Visit</description>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Previous_Donation__c.field-meta.xml
<CustomField>
    <fullName>Previous_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The previous Visit that was donation Complete</description>
    <inlineHelpText>The previous Visit that was a successful Donation</inlineHelpText>
    <label>Previous Donation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Visit__c.Status__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </filterItems>
        <filterItems>
            <field>Visit__c.Donation_Volume__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visits (Previous Donation)</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Captures the state of a Visit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Donor_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Verified</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <description>All status options for a Donor except Lead:
Donor&lt;Registered&gt; Are in the system as a potential donor Q: Do we need in between states Pending Qualification
Donor&lt;Verified&gt; Has filled out all Profile Info, Social Pic, and has verified email and SMS Donor&lt;Scheduled&gt; Has an appointment to assess their fitness for donation
Donor&lt;Eligible&gt; Has met all criteria for donation and eligibility datetime is today or in the past.
Donor&lt;Ineligible&gt; Has met all criteria for donation, but has become ineligible for numerous medical reasons e.g. has the flu, pregnant, etc. thus Eligibility datetime in the future.
Donor&lt;Excluded&gt; Can never donate blood; eligibility date -&gt; 9999
 Donor&lt;Lead&gt; (not a part of this object def but is a Lead RT)</description>
    <masterLabel>Donor Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FdaVisitValidator.cls
public without sharing class FdaVisitValidator {
    final Set<String> VALID_VISIT_STATUSES = new Set<String>{'New', 'Scheduled', 'Checked-In'};
    final Set<String> VALID_VISIT_OUTCOMES = new Set<String>{'Donation', 'No Donation'};
    
    public List<FdaValidationRequest> createVisitRequests;
    
    private Map<Id, List<Visit__c>> donorIdToNewVisits;
    private Map<Id, DateTime> appointmentIdToDateTime;
    private Map<String, FdaValidationRequest> createVisitRequestMap;

    private Set<Id> appointmentIds;
    private Set<Id> donorContactIds;

    private Datetime minimumDateTime;
    private Datetime maximumDateTime;

    public FdaVisitValidator(FdaValidationRequest createVisitRequest) {
        this(new List<FdaValidationRequest>{createVisitRequest});
    }

    public FdaVisitValidator(List<FdaValidationRequest> createVisitRequests) {
        this.createVisitRequests = createVisitRequests;
        buildCreateVisitRequestMap();

        this.appointmentIdToDateTime = new Map<Id, DateTime>();
        this.donorIdToNewVisits = new Map<Id, List<Visit__c>>();
        this.appointmentIds = new Set<Id>();
        this.donorContactIds = new Set<Id>();

        gatherIdSets();
        calculateValidationStartAndEndDatetimes();
        buildRequestedVisitSObjectsForValidation();
    }

    public List<FdaValidationRequest> validateCreateVisitRequests() {
        for(Contact donorContact : [
            SELECT Id, (
                SELECT Id, Appointment_Datetime__c, Appointment__c 
                FROM Visits__r
                WHERE Appointment_Datetime__c >= :minimumDateTime AND 
                    Appointment_Datetime__c <= :maximumDateTime AND 
                    (Status__c IN :VALID_VISIT_STATUSES OR (Status__c = 'Complete' AND Outcome__c IN :VALID_VISIT_OUTCOMES))
                ORDER BY Appointment_Datetime__c ASC
            )
            FROM Contact
            WHERE Id IN :donorContactIds
        ]) {
            List<Visit__c> allDonorVisits = getAllDonorVisits(donorContact);
            
            // No possible rule violations in this case
            if (allDonorVisits.size() < 2) {
                continue;
            }

            // Analyze the visit list in chuncks of 7 days, starting with the earliest visit date to visit date + 6 days
            // If any donor has more than 2 visits in a 7 day period OR more than 1 visit in a 48 hour period, throw an error

            Datetime currentSevenDayPeriodStart = allDonorVisits[0].Appointment_Datetime__c;
            Datetime currentSevenDayPeriodEnd = currentSevenDayPeriodStart.addDays(6);

            Integer visitsInCurrentSevenDayPeriod = 0;
            Datetime lastVisitInCurrentSevenDayPeriod = null;
            Boolean isPeriodStillValid = true; // If we find a rule violation, we can automatically mark the rest of the visits in the period as invalid

            for (Visit__c visit : allDonorVisits) {
                if (visit.Appointment_Datetime__c > currentSevenDayPeriodEnd) {
                    currentSevenDayPeriodStart = visit.Appointment_Datetime__c;
                    currentSevenDayPeriodEnd = currentSevenDayPeriodStart.addDays(6);

                    visitsInCurrentSevenDayPeriod = 0;
                    lastVisitInCurrentSevenDayPeriod = null;
                    isPeriodStillValid = true;
                }

                // This should only be caused by the donor having more than 2 visits in a 7 day period
                if (!isPeriodStillValid) {
                    FdaValidationRequest createVisitRequest = getCreateVisitRequest(visit.Appointment__c, donorContact.Id);
                    if (createVisitRequest != null) {
                        createVisitRequest.addValidationResult(false, 'Donor has more than 2 visits in a 7 day period');
                    }

                    continue;
                }

                visitsInCurrentSevenDayPeriod++;
                if (visitsInCurrentSevenDayPeriod > 2) {
                    isPeriodStillValid = false;

                    FdaValidationRequest createVisitRequest = getCreateVisitRequest(visit.Appointment__c, donorContact.Id);
                    if (createVisitRequest != null) {
                        createVisitRequest.addValidationResult(false, 'Donor has more than 2 visits in a 7 day period');
                    }

                    continue;
                }

                if (
                    lastVisitInCurrentSevenDayPeriod != null && 
                    visitsInCurrentSevenDayPeriod > 1 &&
                    visit.Appointment_Datetime__c.addDays(-2) < lastVisitInCurrentSevenDayPeriod
                ) {
                    FdaValidationRequest createVisitRequest = getCreateVisitRequest(visit.Appointment__c, donorContact.Id);
                    if (createVisitRequest != null) {
                        createVisitRequest.addValidationResult(false, 'Donor has more than 1 visit in a 48 hour period');
                    }

                    continue;
                }

                lastVisitInCurrentSevenDayPeriod = visit.Appointment_Datetime__c;

                FdaValidationRequest createVisitRequest = getCreateVisitRequest(visit.Appointment__c, donorContact.Id);
                if (createVisitRequest != null) {
                    createVisitRequest.addValidationResult(true, '');
                }
            }
        }

        return createVisitRequests;
    }

     private void buildCreateVisitRequestMap() {
        this.createVisitRequestMap = new Map<String, FdaValidationRequest>();
        for (FdaValidationRequest createVisitRequest : createVisitRequests) {
            createVisitRequestMap.put(createVisitRequest.appointmentId + '-' + createVisitRequest.donorContactId, createVisitRequest);
        }

        System.debug(createVisitRequestMap);
    }

    private FdaValidationRequest getCreateVisitRequest(String appointmentId, String donorContactId) {
        return createVisitRequestMap.get(appointmentId + '-' + donorContactId);
    }

    private void gatherIdSets() {
        for (FdaValidationRequest createVisitRequest : createVisitRequests) {
            appointmentIds.add(createVisitRequest.appointmentId);
            donorContactIds.add(createVisitRequest.donorContactId);
        }
    }

    private void calculateValidationStartAndEndDatetimes() {
        for(Appointment__c appointment : [SELECT Id, Datetime__c FROM Appointment__c WHERE Id IN :appointmentIds]) {
            Datetime newMinimumDateTime = appointment.Datetime__c.addDays(-6);
            if (minimumDateTime == null || newMinimumDateTime < minimumDateTime) {
                minimumDateTime = newMinimumDateTime;
            }

            Datetime newMaximumDateTime = appointment.Datetime__c.addDays(6);
            if (maximumDateTime == null || newMaximumDateTime > maximumDateTime) {
                maximumDateTime = newMaximumDateTime;
            }

            appointmentIdToDateTime.put(appointment.Id, appointment.Datetime__c);
        }
    }

    private void buildRequestedVisitSObjectsForValidation() {
        for(FdaValidationRequest createVisitRequest : createVisitRequests) {
            List<Visit__c> newVisitsForDonor = donorIdToNewVisits.get(createVisitRequest.donorContactId);

            if (newVisitsForDonor == null) {
                newVisitsForDonor = new List<Visit__c>();
                donorIdToNewVisits.put(createVisitRequest.donorContactId, newVisitsForDonor);
            }

            newVisitsForDonor.add(new Visit__c(
                Appointment__c = createVisitRequest.appointmentId,
                Donor__c = createVisitRequest.donorContactId,
                Center_Donation_Type__c = createVisitRequest.centerDonationTypeId,
                Status__c = 'Scheduled',
                Appointment_Datetime__c = appointmentIdToDateTime.get(createVisitRequest.appointmentId)
            ));
        }
    }

    private List<Visit__c> getAllDonorVisits(Contact donorContact) {
        List<Visit__c> allDonorVisits = donorContact.Visits__r;
        if (allDonorVisits == null) {
            allDonorVisits = new List<Visit__c>();
        }

        List<Visit__c> newVisitsForDonor = donorIdToNewVisits.get(donorContact.Id);
        if (newVisitsForDonor != null) {
            allDonorVisits.addAll(newVisitsForDonor);
        }

        return allDonorVisits;
    } 

    public class FdaValidationRequest {
        public Id appointmentId;
        public Id donorContactId;
        public Id centerDonationTypeId;

        public ValidationResult validationResult;

        public FdaValidationRequest(Id appointmentId, Id donorContactId, Id centerDonationTypeId) {
            this.appointmentId = appointmentId;
            this.donorContactId = donorContactId;
            this.centerDonationTypeId = centerDonationTypeId;
        }

        public void addValidationResult(Boolean isValid, String errorMessage) {
            this.validationResult = new ValidationResult(isValid, errorMessage);
        }
    }

    public class ValidationResult {
        public Boolean isValid;
        public String errorMessage;

        public ValidationResult(Boolean isValid, String errorMessage) {
            this.isValid = isValid;
            this.errorMessage = errorMessage;
        }
    }
}