force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration in minutes, set by the Schedule Template used to generate the Schedule</description>
    <label>Duration</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <description>A summary level object that represents a time frame of Appointment child records.</description>
    <label>Schedule</label>
    <nameField>
        <displayFormat>SCH-{0}</displayFormat>
        <label>Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <description>The beginning date for the Schedule inclusive.</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <description>The Center associated with this Schedule</description>
    <label>Center</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schedules</relationshipLabel>
    <relationshipName>Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last day for this Schedule inclusive.</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ScheduleUtils.cls
public with sharing class ScheduleUtils {
  

    public static Appointment__c[] createDailySlots(Id centerId, Date day, Time startTime, Time endTime, Integer incrementInMinutes, Integer slotsPerIncrement){
        DateTime startDT = DateTime.newInstance(day, startTime);
        DateTime endDT = DateTime.newInstance(day, endTime);

        Schedule__c schedule = [
            SELECT id 
            FROM Schedule__c
            WHERE Center__c =: centerId
            AND Begin_Date__c <=: day
            AND End_Date__c >=: day
        ];
        system.debug('schedule' + schedule);
        
        Long startMS = startDT.getTime();
        Long endMS = endDT.getTime();

        Long milliseconds = endMS - startMS;
        Long seconds = milliseconds / 1000;
        Long minutes = seconds / 60;
        Long hours = minutes / 60;

        Long incrementsPerDay = (minutes / incrementInMinutes) ;
        
        Appointment__c[] appointments = new Appointment__c[]{
            new Appointment__c(
                Datetime__c = startDT,
                Schedule__c = schedule.Id,
                Duration__c = incrementInMinutes
            )
        };
        for(Integer i=1; i< incrementsPerDay; i++){
            DateTime incrementDT = appointments[i-1].Datetime__c.addMinutes(incrementInMinutes);
    
            for(Integer j=0;j< slotsPerIncrement; j++){
                system.debug('add slots');
                appointments.add(new Appointment__c(
                    Datetime__c = incrementDT,
                    Schedule__c = schedule.Id,
                    Duration__c = incrementInMinutes
                ));
            }
        }

        for(Appointment__c app: appointments){
            system.debug(app);
        }
        

        system.debug('Total hours: '+ hours);
        system.debug('Total Minutes: '+ minutes);
        system.debug('Increments per Day: '+ incrementsPerDay);
       
        Long totalSlotsCreated =  incrementsPerDay * slotsPerIncrement;
        system.debug('Slots per Day: '+ totalSlotsCreated);
        system.assertEquals(totalSlotsCreated, appointments.size());
        for (Appointment__c app: appointments){
            system.debug(app.Schedule__c);
        }
        
        return appointments;
    }
    
}