force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <description>Represents an available time slot in a Clinic Schedule</description>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Datetime__c.field-meta.xml
<CustomField>
    <fullName>Datetime__c</fullName>
    <description>The date and time of this Appointment.</description>
    <label>Datetime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Physical_Exam_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Physical_Exam_Date__c</fullName>
    <description>Indicates the last date a donor had a physical exam. Updated from Visits with the Physical Exam checkbox checked.</description>
    <inlineHelpText>Indicates the last date a donor had a physical exam. Updated from Visits with the Physical Exam checkbox checked.</inlineHelpText>
    <label>Last Physical Exam Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_SPE_Sample_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_SPE_Sample_Date__c</fullName>
    <description>Indicates the last date a donor had a SPE Sample. Updated from Visits with the SPE Sample checkbox checked.</description>
    <inlineHelpText>Indicates the last date a donor had a SPE Sample. Updated from Visits with the SPE Sample checkbox checked.</inlineHelpText>
    <label>Last SPE Sample Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <description>A Visit by a Donor at a specific Appointment date and time.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Appointment__c.field-meta.xml
<CustomField>
    <fullName>Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Appointment associated with this Visit.</description>
    <label>Appointment</label>
    <referenceTo>Appointment__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Appointment_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Datetime__c</fullName>
    <description>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</description>
    <inlineHelpText>The datetime of the Appointment slot where this Visit is scheduled. This is a field that must be updated via trigger/flow to support the Donor.Next Visit field which is the minimum rollup of Scheduled Visits.</inlineHelpText>
    <label>Appointment Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Donor associated with this Visit.</description>
    <label>Donor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/isFirstVisit__c.field-meta.xml
<CustomField>
    <fullName>isFirstVisit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates this Visit is the first for a donor</description>
    <label>First Visit?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Physical_Exam__c.field-meta.xml
<CustomField>
    <fullName>Physical_Exam__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a physical exam is due for a donor.</description>
    <inlineHelpText>Indicates whether a physical exam is due for a donor.</inlineHelpText>
    <label>Physical Exam?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Previous_Donation__c.field-meta.xml
<CustomField>
    <fullName>Previous_Donation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The previous Visit that was donation Complete</description>
    <inlineHelpText>The previous Visit that was a successful Donation</inlineHelpText>
    <label>Previous Donation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Visit__c.Status__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </filterItems>
        <filterItems>
            <field>Visit__c.Donation_Volume__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Visit__c</referenceTo>
    <relationshipLabel>Visits (Previous Donation)</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/SPE_Analysis__c.field-meta.xml
<CustomField>
    <fullName>SPE_Analysis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether an SPE analysis is due for a donor.</description>
    <inlineHelpText>Indicates whether an SPE analysis is due for a donor.</inlineHelpText>
    <label>SPE Analysis?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VisitTriggerHelper.cls
public with sharing class VisitTriggerHelper {
    public static void updateAppointmentDateTime(List<Visit__c> visitRecordsToUpdate) {
        Map<Id, List<Visit__c>> appointmentIdToVisitRecord = new Map<Id, List<Visit__c>>(); 
        
        for(Visit__c targetVisit : visitRecordsToUpdate) {
            if (targetVisit.Appointment__c != null) {
                List<Visit__c> existingVisits = appointmentIdToVisitRecord.get(targetVisit.Appointment__c);
                if (existingVisits == null) {
                    existingVisits = new List<Visit__c>();
                }

                existingVisits.add(targetVisit);
                appointmentIdToVisitRecord.put(targetVisit.Appointment__c, existingVisits);
            }
        }

        // No Appointment DateTimes to Link
        if (appointmentIdToVisitRecord.size() == 0) {
            return;
        }

        for (Appointment__c queriedAppointment : [
            SELECT Id, Datetime__c
            FROM Appointment__c
            WHERE Id IN :appointmentIdToVisitRecord.keyset()
        ]) {
            if (queriedAppointment.Datetime__c == null) {
                continue;
            }

            List<Visit__c> relatedVisits = appointmentIdToVisitRecord.get(queriedAppointment.Id);
            if (relatedVisits == null || relatedVisits.size() == 0) {
                continue;
            }

            for(Visit__c relatedVisit : relatedVisits) {
                relatedVisit.Appointment_Datetime__c = queriedAppointment.Datetime__c;
            }
        }
    }

    public static void updateDonorVisitDates(List<Visit__c> visits) {
        List<Id> donorIds = new List<Id>();
        List<Id> appointmentIds = new List<Id>();
    
        for (Visit__c visit : visits) {
            if (visit.Physical_Exam__c || visit.SPE_Analysis__c) {
                if (visit.Donor__c == null || visit.Appointment__c == null) {
                    continue;
                }

                donorIds.add(visit.Donor__c);
                appointmentIds.add(visit.Appointment__c);
            }
        }
        
        if (!donorIds.isEmpty()) {
            Map<Id, Contact> visitIdToDonorRecord = new Map<Id, Contact>([SELECT Id, Last_Physical_Exam_Date__c, Last_SPE_Sample_Date__c FROM Contact WHERE Id IN :donorIds]);
            Map<Id, Appointment__c> visitIdToAppointmentRecord = new Map<Id, Appointment__c>([SELECT Id, DateTime__c FROM Appointment__c WHERE Id IN :appointmentIds]);
            
            for (Visit__c visit : visits) {
                Contact donor = visitIdToDonorRecord.get(visit.Donor__c);
                Appointment__c appointment = visitIdToAppointmentRecord.get(visit.Appointment__c);
                
                if (donor != null && appointment.DateTime__c != null) {
                    if (visit.Physical_Exam__c) {
                        donor.Last_Physical_Exam_Date__c = appointment.DateTime__c.date();
                    }
                    
                    if (visit.SPE_Analysis__c) {
                        donor.Last_SPE_Sample_Date__c = appointment.DateTime__c.date();
                    }
                    
                    visitIdToDonorRecord.put(donor.Id, donor);
                }
            }
            
            update visitIdToDonorRecord.values();
        }
    }

    public static void setIsFirstVisitFlag(List<Visit__c> visits) {
        Map<Id, Visit__c> donorIdToNewVisit = new Map<Id, Visit__c>();
        for (Visit__c visit : visits) {
            if (visit.Donor__c != null) {
                donorIdToNewVisit.put(visit.Donor__c, visit);
            }
        }

        if (donorIdToNewVisit.size() != 0) {
            for(Contact donor : [SELECT Id, (SELECT Id, Appointment_Datetime__c, isFirstVisit__c FROM Visits__r) FROM Contact WHERE Id IN :donorIdToNewVisit.keyset()]) {
                donorIdToNewVisit.get(donor.Id).isFirstVisit__c = (donor.Visits__r == null || donor.Visits__r.size() == 0);
            }
        }
    }
}